### ISSUE TITLE
rename gg_scrapper to gg_scraper

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#101]
Originally reported by: **Matěj Cepl (Bitbucket: [mcepl](https://bitbucket.org/mcepl), GitHub: [mcepl](https://github.com/mcepl))**

----------------------------------------

I got to the bottom of many jokes on the thread where I have announced the project
https://mail.python.org/pipermail/python-list/2014-January/663846.html

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/101

**Comment by berkerpeksag** [comment]
Already renamed to gg_scraper: https://pypi.python.org/pypi/gg_scraper
