### ISSUE TITLE
password using ":" colon symbol allowed to be set but fails on auth at https://pypi.python.org/

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#104]
Originally reported by: **m dub (Bitbucket: [herebox](https://bitbucket.org/herebox), GitHub: Unknown)**

---

Tried a short and long password with and without the colon ":" symbol.  All were allowed to be set, but only those containing ":" fail when attempting to login at https://pypi.python.org/

Tried and successfully used a single quote ' and a semicolon ; 

Chromium 31.0.1650.63 Ubuntu 13.04

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/104

**Comment by di** [comment]
WONTFIX for pypi-legacy, but this is fixed at `pypi.org`.
