### ISSUE TITLE
issue with removing a version from pypi

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#11]
Originally reported by: **Guy Rozendorn (Bitbucket: [guyroz](https://bitbucket.org/guyroz), GitHub: Unknown)**

---

When a package contains multiple versions and the last one is removed by the owner, the older versions of the package are still installable and visible from the '/simple' interface but the package itself disappears from the API and from the '/pypi' interface, returning "Not Found" in both.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/11

**Comment by ewdurbin** [comment]
still an issue.

**Comment by di** [comment]
This is "fixed" for https://pypi.org, which has no concept of hidden releases:

https://pypi.org/project/agic/
https://pypi.org/simple/agic/
