### ISSUE TITLE
certain passwords not working

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#111]
Originally reported by: **Tim Tisdall (Bitbucket: [tisdall](https://bitbucket.org/tisdall), GitHub: [tisdall](https://github.com/tisdall))**

----------------------------------------

I tried creating an account with the password: `a=,j=8Y":>!T#6o`

When I tried logging in with standard HTTP auth it simply gave me the prompt again.  I was unable to log in with that password.

Also, after clicking cancel I was given a screen that allowed me to try logging in with Google, but when I clicked it it only downloaded a file named `id` (possibly http headers were wrong?).

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/111

**Comment by berkerpeksag** [comment]
This is a duplicate of #104.
