### ISSUE TITLE
Error when logging in to pypi using my google account

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#113]
Originally reported by: **Remco Haszing (Bitbucket: [remcohaszing](https://bitbucket.org/remcohaszing), GitHub: [remcohaszing](https://github.com/remcohaszing))**

---

When I try to log in to pypi using my google account, I get an error 502.
I am first redirected to a page to select my google account. After clicking my account I get this error.
The page I am redirected to is https://pypi.python.org/pypi?:action=openid_return&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fud&openid.response_nonce=2014-02-01T14%3A43%3A23ZDAf1uD9_yYfn-Q&openid.return_to=https%3A%2F%2Fpypi.python.org%2Fpypi%3F%3Aaction%3Dopenid_return&openid.assoc_handle=1.AMlYA9XFP28q-J7mmpEinavXicrtd-9IeVu-nWBD3on0fYZkMLengbljGc6NCg&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.first%2Cext1.value.first%2Cext1.type.last%2Cext1.value.last%2Cext1.type.email%2Cext1.value.email&openid.sig=z4NYzdCarkMItbI7GPqHEUa5wxI%3D&openid.identity=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawmhJ7gDuOkkaSql_NguPpFTbWstAE-E6DY&openid.claimed_id=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid%3Fid%3DAItOawmhJ7gDuOkkaSql_NguPpFTbWstAE-E6DY&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.first=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.first=<firstname>&openid.ext1.type.last=http%3A%2F%2Faxschema.org%2FnamePerson%2Flast&openid.ext1.value.last=<lastname>&openid.ext1.type.email=http%3A%2F%2Faxschema.org%2Fcontact%2Femail&openid.ext1.value.email=<email>#

I am still able to log in using my username and password

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/113

**Comment by di** [comment]
Login via OpenID is no longer supported.
