### ISSUE TITLE
Can not login to PyPi using Google ID

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#115]
Originally reported by: **adamatan (Bitbucket: [adamatan](https://bitbucket.org/adamatan), GitHub: [adamatan](https://github.com/adamatan))**

---

Yesterday I tried to change my password and add ssh keys in my PyPi account "Adam.Matan". I was redirected to the "Something went wrong" page:
![BgGvMh2CEAA15nN.jpg](https://bitbucket.org/repo/j9KaaX/images/3068490275-BgGvMh2CEAA15nN.jpg)

Today, I was unable to login to my account using my OpenId account (adam at matan.name, a Google Id).

Could you please check the login component?

https://twitter.com/adam_matan/status/432819668978372608

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/115

**Comment by di** [comment]
@adamatan seems to have been able to log in since this was created, if you are still having problems please open an issue at https://github.com/pypa/warehouse/issues.
