### ISSUE TITLE
Binary wheels for linux are not supported

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#120]
Originally reported by: **Thimo Kraemer (Bitbucket: [joonis](https://bitbucket.org/joonis), GitHub: [joonis](https://github.com/joonis))**

---

Uploading a binary wheel for linux results in an error:

400 Client Error: Binary wheel for an unsupported platform

Example file names:
- mypkg-1.0-cp27-none-linux_i686.whl
- mypkg-1.0-cp27-none-linux_x86_64.whl

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/120

**Comment by pylover** [comment]
https://github.com/pypa/manylinux

**Comment by jamadden** [comment]
It seems to me that the advent of [PEP 513](https://www.python.org/dev/peps/pep-0513/) (the manylinux specification) is the currently accepted answer about uploading binary wheels for linux, so this issue can be closed.
