### ISSUE TITLE
Logging in using delegated OpenID fails

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#121]
Originally reported by: **Barnaby Walters (Bitbucket: [barnabywalters](https://bitbucket.org/barnabywalters), GitHub: [barnabywalters](https://github.com/barnabywalters))**

---

Trying to log in to pypi using my own domain (http://waterpigs.co.uk), which uses OpenID delegation to http://indieauth.com for authentication, fails with the following cryptic error message:

> Cannot establish OpenID session: need more than 1 value to unpack

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/121

**Comment by di** [comment]
OpenID is no longer supported by PyPI.
