### ISSUE TITLE
Error in VCF package

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#125]
Originally reported by: **monty HS (Bitbucket: [mantiHS](https://bitbucket.org/mantiHS), GitHub: Unknown)**

----------------------------------------

import vcf
vcf_reader = vcf.Reader(open('file.vcf', 'r'))
for each in vcf_reader:
    print each

OUTPUT:
Traceback (most recent call last):
File "importvcf.py", line 3, in <module>
for each in vcf_reader:
File "/usr/local/lib/python2.7/dist-packages/PyVCF-0.6.4-py2.7.egg/vcf/parser.py", line 525, in next
pos = int(row[1])
IndexError: list index out of range

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/125

**Comment by berkerpeksag** [comment]
Please report this to PyVCF developers: https://github.com/jamescasbon/PyVCF
