### ISSUE TITLE
Link to upload docs is broken

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#132]
Originally reported by: **Thomas Güttler (Bitbucket: [thomas-guettler](https://bitbucket.org/thomas-guettler), GitHub: Unknown)**

----------------------------------------

On the "edit files" view the link to the upload docs is broken.

Example:

https://pypi.python.org/pypi?name=websocketrpc&version=0.1&:action=files

    
     1. Use the setup.py "upload" command. --> 
    

https://www.python.org/doc/dist/package-upload.html

404: not found.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/132

**Comment by berkerpeksag** [comment]
The URL has been updated to use https://packaging.python.org/en/latest/distributing/#uploading-your-project-to-pypi
