### ISSUE TITLE
Can't add #egg=package-dev URL for package in pypi-explicit mode

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#14]
Originally reported by: **Stein Magnus Jodal (Bitbucket: [jodal](https://bitbucket.org/jodal), GitHub: [jodal](https://github.com/jodal))**

---

If I add a new package to PyPI, it gets the pypi-explicit mode by default now. Thus, no URLs are extracted from the long_description to the simple index, including any #egg=package-dev URLs.

The obvious way to add a #egg=package-dev URL for my package now is to use the "Add a New URL" form on the package's Urls page on PyPI. Because that form requires a #hashtype=hashvalue suffix, that doesn't work.

Thus, the current workaround is to:
1. Register new package
2. Switch away from pypi-explicit
3. Upload a version of the package with a long_description with the wanted URL
4. Switch back to pypi-explicit
5. Remove any URLs from the "Additional File URLs" except the #egg=package-dev URL

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/14

**Comment by berkerpeksag** [comment]
Thank you for the report. Editing the `hosting_mode` field is no longer possible after https://github.com/pypa/pypi-legacy/commit/23f5ccc938295871c455308f186c9961a9f871a2 and https://github.com/pypa/pypi-legacy/commit/6072260cea1ac058a05429fcfe591b60cd434bad (`set_package_hosting_mode` has been deleted) so I'm going to close this one as 'outdated'.
