### ISSUE TITLE
Security concern - Stranger can take ownership of abandoned project

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#141]
Originally reported by: **David Burke (Bitbucket: [davidmburke](https://bitbucket.org/davidmburke), GitHub: Unknown)**

---
1. Project x of a popular project removes their account. 
2. Mean Person re-registers the project using the same name.
3. Mean Person uploads a new version with a new rm -rf / feature.
4. People with dependencies on the project have a bad day.

I registered odfpy after it just disappeared. Luckily I'm not mean. Seems like a security issue.

See discussion about odfpy here.
https://github.com/ldo/odfpy/issues/1#issuecomment-43021239

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/141

**Comment by di** [comment]
Since PyPI doesn't allow reuse of filenames, folks concerned about this can pin versions and use `--require-hashes` with `pip` to ensure that they don't get upgraded or switched to a malicious distribution.
