### ISSUE TITLE
Package pages should have clear "pip install" instructions near top of page

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#149]
Originally reported by: **Hickford (Bitbucket: [hickford](https://bitbucket.org/hickford), GitHub: [hickford](https://github.com/hickford))**

----------------------------------------

Take a look at any package page on the Ruby gems website (eg.  https://rubygems.org/gems/rails ).  At the top of the page, it has the installation instructions in large friendly letters (eg. `gem install rails`). Similarly, on any Nodejs package page (eg. https://www.npmjs.org/package/express ) the installation instructions are near the top and very clear (eg. `npm install express`)

However, browse to a package page on Python's package index PyPI (eg. https://pypi.python.org/pypi/lxml/3.3.5 ) and there's no installation instructions at all! There should be clear instructions at the top of the page (eg. `pip install lxml`. Pip is the Python package manager and the easiest way to install packages.). 

Don't underestimate the importance of clear instructions. They would be extremely helpful, particularly to new users. There's a huge amount of confusion about how to install Python packages, as evidenced by popular search queries and StackOverflow questions. This is the long shadow of Python's history of shipping without a package manager.

Now Python (from version 3.4) ships with the package manager Pip, packages can be installed easily, but **users need to be educated how**. 

If you doubt the problem, observe that a number of high-ranking web pages encourage the use of the obsolete and lacking `easy_install` script. And that the deprecated packaging library `distribute` still receives upwards of a million downloads per month. The confusion around packages is a real barrier to new users learning Python.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/149

**Comment by berkerpeksag** [comment]
The new PyPI now contains a `pip install` command in package detail page: https://pypi.io/project/lxml/
