### ISSUE TITLE
PyPI should warn and drop registered but unreleased packages

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#166]
Originally reported by: **Dustin Oprea (Bitbucket: [dsoprea](https://bitbucket.org/dsoprea), GitHub: [dsoprea](https://github.com/dsoprea))**

---

I regularly see projects that have been registered, but where no releases have been made, and there's no contact information.

It might be useful to sent out warnings after thirty- or sixty-days, and then remove it, if the state remains unchanged, a short period thereafter.

This might be widely unpopular, but we might also do a warn and remove for packages that have low volume and haven't been changed in a year or two. My two-cents.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/166

**Comment by di** [comment]
PEP 541 makes it possible to acquire squatted package names. Otherwise, they're harmless.
