### ISSUE TITLE
Request for new trove classifiers: Django versions

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#167]
Originally reported by: **anentropic (Bitbucket: [anentropic](https://bitbucket.org/anentropic), GitHub: [anentropic](https://github.com/anentropic))**

----------------------------------------

I found this list:
https://pypi.python.org/pypi?%3Aaction=list_classifiers

I assumed it was a list of suggestions to avoid people creating duplicates etc, setting out a format. But it seems a hard coded list that setup.py classifiers are validated against when uploading to PyPI.

In that case it's weird that Django only gets a single entry "Framework :: Django", while something called 'Plone' gets a bunch of specific versions.

If trove classifiers are useful for anything (?) then I guess it would be useful for authors of Django apps to be able to specify which versions of Django their package works against, since there can be breaking changes between point versions.

I'd suggest:

* 1.0 (earliest tag on github)
* 1.1
* 1.2
* 1.3
* 1.4
* 1.5
* 1.6
* 1.7 

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/167

**Comment by berkerpeksag** [comment]
I can now see the following classifiers at https://pypi.python.org/pypi?%3Aaction=list_classifiers:

```
Framework :: Django
Framework :: Django :: 1.4
Framework :: Django :: 1.5
Framework :: Django :: 1.6
Framework :: Django :: 1.7
Framework :: Django :: 1.8
Framework :: Django :: 1.9
```

Django 1.4 is the earliest LTS version of Django so I don't think there is anything left to be done here.

**Comment by tkimnguyen** [comment]
I did want to add that Plone uses the version classifiers *a lot*. It is how we distinguish compatibility of add-ons and themes, and we are building an add-ons listing that uses these classifiers heavily.
