### ISSUE TITLE
Ability to search packages within category

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#172]
Originally reported by: **Michał Podeszwa (Bitbucket: [michalpodeszwa](https://bitbucket.org/michalpodeszwa), GitHub: [michalpodeszwa](https://github.com/michalpodeszwa))**

---

You should be able to search through packages within one category.

Most importantly, you should be able to search through packages for Python3 only.
Trying to select category and then searching for a package in search box results in unselecting category.

I've also tried adding `&c=` argument to search query, but that does not work.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/172

**Comment by di** [comment]
This is possible now with `pypi.org` search classifiers, e.g.:

* Python 3 compatible projects: https://pypi.org/search/?c=Programming+Language+%3A%3A+Python+%3A%3A+3
