### ISSUE TITLE
Pypi hides stable releases when unstable/dev releases are uploaded

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#18]
Originally reported by: **vmalloc (Bitbucket: [vmalloc](https://bitbucket.org/vmalloc), GitHub: [vmalloc](https://github.com/vmalloc))**

---

New versions of distribute support the .dev suffix to versions. This is useful to enable some developers to experiment with new unstable releases, while the rest of the world gets the stable version when using easy_install or pip.

It seems, however, that pypi's default behavior hinders this feature - it automatically hides the stable versions when a .dev release is uploaded, thus probably breaking things for most of the people looking for the stable version.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/18

**Comment by di** [comment]
The new PyPI at `pypi.org` has no concept of hidden releases, so this is a WONTFIX if it hasn't been fixed already.
