### ISSUE TITLE
Request for Trove classifiers for iOS and Android

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#184]
Originally reported by: **Russell Keith-Magee (Bitbucket: [freakboy3742](https://bitbucket.org/freakboy3742), GitHub: [freakboy3742](https://github.com/freakboy3742))**

----------------------------------------

Given that Kivy and Toga both run on mobile platforms, it seems like there should be ``Operating System`` classifiers for those platforms. Suggested:
```
Operating System :: iOS
Operating System :: iOS :: 1
Operating System :: iOS :: 2
Operating System :: iOS :: 3
Operating System :: iOS :: 4
Operating System :: iOS :: 5
Operating System :: iOS :: 6
Operating System :: iOS :: 7
Operating System :: iOS :: 8 
Operating System :: Android
Operating System :: Android :: 1.0
Operating System :: Android :: 1.1
Operating System :: Android :: 1.5
Operating System :: Android :: 1.6
Operating System :: Android :: 2.0
Operating System :: Android :: 2.0.1
Operating System :: Android :: 2.1
Operating System :: Android :: 2.2
Operating System :: Android :: 2.3
Operating System :: Android :: 2.3.3
Operating System :: Android :: 3.0
Operating System :: Android :: 3.1
Operating System :: Android :: 3.2
Operating System :: Android :: 4.0
Operating System :: Android :: 4.0.3
Operating System :: Android :: 4.1
Operating System :: Android :: 4.2
Operating System :: Android :: 4.3
Operating System :: Android :: 4.4
```

It's unclear to me if a new ``Environment`` classifier is also required; ``Environment :: Handhelds/PDA\'s`` exists, but seems like an anachronistic description of a modern mobile device.

Notes:

* If the number of classifiers here is a concern, iOS versions prior to 5 and Android prior to 2.3.3 could be omitted as being of historical interest only.

* I've chosen version numbers, rather than API levels for the Android classifiers - that's why versions like 2.3.3  and 4.0.3 exist, but other micro versions do not. In those cases, the micro version corresponds to the earliest version exhibiting the new API version.

Refs:

* http://en.wikipedia.org/wiki/History_of_iOS

* http://en.wikipedia.org/wiki/Android_version_history

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/184

**Comment by berkerpeksag** [comment]
Android and iOS has already been added. Any new proposal needs to be referred to https://github.com/pypa/warehouse
