### ISSUE TITLE
Too many categories gives 500 error

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#187]
Originally reported by: **Simeon Visser (Bitbucket: [svisser_ometria](https://bitbucket.org/svisser_ometria), GitHub: Unknown)**

---

The following link is fine:

https://pypi.python.org/pypi?:action=browse&c=19&c=30&c=33&c=54&c=103&c=372&c=373&c=551

But the following link gives 500 error:

https://pypi.python.org/pypi?:action=browse&c=19&c=30&c=33&c=54&c=103&c=135&c=372&c=373&c=551

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/187

**Comment by berkerpeksag** [comment]
The latter link returns 400 since https://github.com/pypa/pypi-legacy/commit/e354867feeb2e964571680a53ad8ff6faf15d7d6. Thank you for the report!
