### ISSUE TITLE
Bad release metadata for FieldPy

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#189]
Originally reported by: **Aaron Meurer (Bitbucket: [asmeurer](https://bitbucket.org/asmeurer), GitHub: [asmeurer](https://github.com/asmeurer))**

---

I hope this is the right place to open this issue. At https://pypi.python.org/pypi/FieldPy/json, you can see two releases for FieldPy, 0.1.4 and 0.1.5. But the xmlrpc interface gives:

In [1]: import xmlrpc.client

In [2]: s = xmlrpc.client.ServerProxy('https://pypi.python.org/pypi')

In [3]: s.package_releases("FieldPy", True)
Out[3]: ['0.1.0']

In [4]: s.release_urls("FieldPy", "0.1.0")
Out[4]: []

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/189

**Comment by rainwoodman** [comment]
Hi, I recently ran into the same problem on package `mpi4py_test`.

**Comment by jamadden** [comment]
Can you be more specific about why you believe this is the same issue? FWIW, I can't replicate a problem using the XML-RPC interface:
```
>>> rels = s.package_releases("mpi4py_test", True):
>>> urls = {}
>>> for rel in rels:
...   urls[rel] = s.release_urls("mpi4py_test", rel)[0]['url']
...
>>> import pprint
>>> pprint.pprint(urls)
{'0.0.1': 'https://pypi.python.org/packages/f6/d6/b05027865d8223545e843f990439da8d538fff9bafb264aa5d7a04df37a7/mpi4py_test-0.0.1.tar.gz',
 '0.0.1.dev0': 'https://pypi.python.org/packages/c5/ac/b3403d74254fc3ae04ac85ea452fbdf0ab6f7bd1b29f151333cd8f8eede5/mpi4py_test-0.0.1.dev0.tar.gz',
 '0.0.3': 'https://pypi.python.org/packages/53/b2/7468c2964fe51fefa3694355926a9465775455c06ae9160dfb445838e744/mpi4py_test-0.0.3.tar.gz',
 '0.0.4': 'https://pypi.python.org/packages/b9/13/cf6eec3b40eea1a3e0e90dadd02309672b5829655266495e40b71842f574/mpi4py_test-0.0.4.tar.gz',
 '0.0.5': 'https://pypi.python.org/packages/4a/18/8c4e0197b4e0c1cabfa782faf8563d70deed9b1cc7af67e0ebfd2d3a90e8/mpi4py_test-0.0.5.tar.gz',
 '0.0.6': 'https://pypi.python.org/packages/5d/fb/e9bda018d198dd469a5586f99e6e45cd0001d0a52c1e48016896a4494d09/mpi4py_test-0.0.6.tar.gz',
 '0.0.7': 'https://pypi.python.org/packages/71/e9/ebe44eb091c9e212998f3753022be92af2194b197c91ace2828e9e6ad135/mpi4py_test-0.0.7.tar.gz',
 '0.0.8': 'https://pypi.python.org/packages/4d/8b/97a65e5c23820e653ca8938aaac975373693dfa20e4634fe5f48b1c8884a/mpi4py_test-0.0.8.tar.gz'}
```

**Comment by rainwoodman** [comment]
Thanks for looking -- but version 0.0.10 is missing from this list.

**Comment by jamadden** [comment]
Good point. That's because I used `True` instead of `False` for `show_hidden`:
```
>>> for rel in s.package_releases("mpi4py_test", False):
...   print(rel, s.release_urls("mpi4py_test", rel)[0]['url'])
...
0.0.10 https://pypi.python.org/packages/19/e0/568d6a015728d1d56cd367d7a647f7ef203cec160e764299115516571a8e/mpi4py_test-0.0.10.tar.gz
0.0.9 https://pypi.python.org/packages/04/82/fd706f7cbe42a5ab87bfa43fb34c7278240fd5288a9c71f553182090baa7/mpi4py_test-0.0.9.tar.gz
```

The [docs](https://wiki.python.org/moin/PyPIXmlRpc) seem to claim that the two sets should overlap, but they clearly don't always, so that's probably the underlying bug.

As a workaround, you might try toggling the hidden status of some versions and see what happens.

**Comment by rainwoodman** [comment]
No. It doesn't help much. It only affects packages without binary extensions apparently (zip OK)?

**Comment by di** [comment]
The `show_hidden` flag is now ignored entirely in the XML-RPC API on `pypi.org`, so this is no longer an issue:

```
>>> import xmlrpclib
>>> client = xmlrpclib.ServerProxy("https://pypi.org/pypi")
>>> client.package_releases("mpi4py_test")
['0.0.1.dev0', '0.0.1', '0.0.3', '0.0.4', '0.0.5', '0.0.6', '0.0.7', '0.0.8', '0.0.9', '0.0.10']
>>> client.package_releases("mpi4py_test", True)
['0.0.1.dev0', '0.0.1', '0.0.3', '0.0.4', '0.0.5', '0.0.6', '0.0.7', '0.0.8', '0.0.9', '0.0.10']
>>> client.package_releases("mpi4py_test", False)
['0.0.1.dev0', '0.0.1', '0.0.3', '0.0.4', '0.0.5', '0.0.6', '0.0.7', '0.0.8', '0.0.9', '0.0.10']
```
