### ISSUE TITLE
HTTP Basic Auth fails intermittently with correct password

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#195]
Originally reported by: **jab (Bitbucket: [jab](https://bitbucket.org/jab), GitHub: [jab](https://github.com/jab))**

---

Not sure exactly what's going on. Seems to happen more frequently with passwords beyond a certain length (what length though I'm not sure). Erroneously assumed it was a bug in Chrome but looks like it's actually a bug in PyPI:

https://code.google.com/p/chromium/issues/detail?id=416872

@EWDurbin was able to reproduce earlier today as was a member of the Chromium team.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/195

**Comment by di** [comment]
Seems to have been resolved (not sure how), and not an issue for `pypi.org`, so closing.
