### ISSUE TITLE
Addition of EPL and CDDL to trove

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#20]
Originally reported by: **Trevor Wennblom (Bitbucket: [trevorw](https://bitbucket.org/trevorw), GitHub: [trevorw](https://github.com/trevorw))**

---

Requesting the addition of EPL and CDDL to the trove classifiers:
- http://opensource.org/licenses/CDDL-1.0
- http://en.wikipedia.org/wiki/Common_Development_and_Distribution_License
- http://opensource.org/licenses/EPL-1.0
- http://en.wikipedia.org/wiki/Eclipse_Public_License

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/20

**Comment by trevor** [comment]
github: @trevor

**Comment by ewdurbin** [comment]
added.
