### ISSUE TITLE
Need API to get list of all packages with current version

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#203]
Originally reported by: **Tom Bechtold (Bitbucket: [toabctl](https://bitbucket.org/toabctl), GitHub: [toabctl](https://github.com/toabctl))**

---

There is currently no API (at I don't know one) to get a list with all available packages and the latest version of the package.
I want to improve a software to track the status (outdated, uptodate) of python packages (in this case rpm packages) . This is currently only possible if I get for every package the version which doesn't scale if I have a lot of packages I want to check. The list with packages could also be static (and generated once a day or so). This is i.e. done for cpan (http://www.cpan.org/modules/02packages.details.txt.gz).

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/203

**Comment by di** [comment]
Captured in https://github.com/pypa/warehouse/issues/347.
