### ISSUE TITLE
Download count probably broken

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#204]
Originally reported by: **niles_rogoff (Bitbucket: [niles_rogoff](https://bitbucket.org/niles_rogoff), GitHub: Unknown)**

---

I am on this page: [here](https://pypi.python.org/pypi?name=BTEdb&version=6.00&:action=display) and it says there have been 231 downloads today, this week and this month. This is almost entirely impossible. I uploaded this only a few hours ago and told no one. I installed it using pip3 on a linux machine only once. 

Reloading it after I started writing this and the number has jumped to 315.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/204

**Comment by jamadden** [comment]
Download counts have been removed from the legacy PyPI interface. See https://github.com/pypa/pypi-legacy/issues/484 for an explanation.
