### ISSUE TITLE
Request for new PyPI trove classifier for Jupyter Framework

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#210]
Originally reported by: **Douglas Blank (Bitbucket: [dblank](https://bitbucket.org/dblank), GitHub: [dblank](https://github.com/dblank))**

---

IPython has developed a new project called Jupyter. This takes the Python-specific parts and makes a framework that is language agnostic, but still written in Python. IPython would make the Jupyter system available under this, and we would like to be able to classify components for Jupyter which are written in Python under this classifier.

Thanks!

References:

https://github.com/jupyter/

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/210

**Comment by Carreau** [comment]
Hi there ! We now have more than 60 packages that use the jupyter prefix, it would be great to have that in the trove classifier !  Thanks !

**Comment by fperez** [comment]
Pitching in from Jupyter here: our ecosystem is growing quite a bit, and it would be tremendously helpful for our users and the entire project to be able to easily find, list, track, etc., tools designed to work with Jupyter-related tools and ideas.

If there's anything we can do from our side to help, please let us know, we'd be happy to.

**Comment by berkerpeksag** [comment]
I think the main pain point for the PyPI maintainers is that there's no UI to add new classifiers so the only way to add or update them is to write raw SQL queries (they can correct me if I'm wrong)

My plan was to create a UI to this make process much easier for [Warehouse](https://github.com/pypa/warehouse), but I don't really have much free time these days :(

**Comment by westurner** [comment]
@fperez 
https://github.com/pypa/warehouse/labels/classifier%20request

- https://github.com/pypa/warehouse/issues/new
 "Request trove classifier for Jupyter"

**Comment by westurner** [comment]
... are these like URIs?

**Comment by ewdurbin** [comment]
added `Framework :: Jupyter`

**Comment by Carreau** [comment]
> added Framework :: Jupyter

Thanks you !

**Comment by westurner** [comment]
Thanks!

**Comment by fperez** [comment]
Don't want to be noisy here, but this is worth more than just an emoji 👍 ... 

We're *very* grateful this was done, as it will really help us organize our ecosystem and track its growth.  Kudos to the team for making this happen!!
