### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#211]
Originally reported by: **adrian_n (Bitbucket: [adrian_n](https://bitbucket.org/adrian_n), GitHub: Unknown)**

----------------------------------------

* [This link](https://packaging.python.org/en/latest/tutorial.html#uploading-your-project-to-pypi) from the [start page](https://pypi.python.org/pypi) points to something that has moved.
* In the [PyPi tutorial](https://wiki.python.org/moin/CheeseShopTutorial):
    * [information about packages of python software](https://docs.python.org/dist/meta-data.html) is broken
    * ``meta-data docs`` is broken
    * ``setup.py file`` and ``docs`` is broken
    * ``source dist`` and ``build dist`` is broken

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/211

**Comment by berkerpeksag** [comment]
The first item has already been fixed. The link now goes to https://packaging.python.org/en/latest/distributing/#uploading-your-project-to-pypi

The CheeseShopTutorial has been deprecated in favor of https://packaging.python.org/en/latest/
