### ISSUE TITLE
PKG-INFO should be able to be pulled from a source dist file

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#212]
Originally reported by: **Douglas Thor (Bitbucket: [dougthor42](https://bitbucket.org/dougthor42), GitHub: [dougthor42](https://github.com/dougthor42))**

---

It would be very convenient if the PKG-INFO file was pulled from an uploaded .zip source dist (or any other compressed file).

Here's my current process flow for uploading a new source dist version of a package*:
1. Create the source distribution: `python setup.py sdist`
2. Extract the PKG-INFO file from the source dist folder
3. Upload the PKG-INFO file to PyPI `Package -> Edit -> Option 2: Upload PKG-INFO file`
4. Upload the source dist file to PyPI: `Package -> Files -> Upload new file`

Now, if the Upload new file option automagically pulled PKG-INFO from the .zip, then the process flow would be two steps shorter:
1. Create source distribution
2. Upload source dist file to PyPI.

.

.

***Note:** Yes, I know that I can use the `setup.py register` and `upload` commands, but I don't like to because it saves (.pypirc file) and sends credentials as **plaintext**. [source](https://packaging.python.org/en/latest/distributing.html#uploading-your-project-to-pypi).

Twine will send encrypted credentials, but that only solves half of the problem. `setup.py register` still stores them as plaintext.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/212

**Comment by di** [comment]
Uploading metadata by itself is no longer supported, the `register` command is no longer supported, and `twine` sends up metadata to `pypi.org` along with source distributions, so this is a cross between resolved and WONTFIX.
