### ISSUE TITLE
rst rendering is too strict

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#214]
Originally reported by: **Marc Abramowitz (Bitbucket: [msabramo](https://bitbucket.org/msabramo), GitHub: [msabramo](https://github.com/msabramo))**

---

Even the slightest mistake -- e.g.:

```
README.rst:2: (WARNING/2) Title underline too short.
```

will cause it to render the input wrapped in a `<PRE>` with no formatting.

It would be nice if PyPI could be a little bit more lenient, as a lot of PyPI project pages look not that great because the author had a small error in their markup.

I would imagine this is generating a lot of emails and issues that suck your time.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/214

**Comment by di** [comment]
rST is still strict, but users now have the [option to use Markdown descriptions on pypi.org](https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi), so anyone getting frustrated by this will likely prefer to use Markdown instead.
