### ISSUE TITLE
Broken links for PythonMagick

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#216]
Originally reported by: **Vladislav Bugaev (Bitbucket: [an_authentic](https://bitbucket.org/an_authentic), GitHub: Unknown)**

----------------------------------------

https://pypi.python.org/simple/pythonmagick/ 404 on both. for now sources are here: http://www.imagemagick.org/download/python/

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/216

**Comment by berkerpeksag** [comment]
You should report this to the pythonmagick developers. PyPI does not have any control over user packages.
