### ISSUE TITLE
Checking current PyPI version fails

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#219]
Originally reported by: **Kay Hayen (Bitbucket: [kayhayen](https://bitbucket.org/kayhayen), GitHub: [kayhayen](https://github.com/kayhayen))**

---

Hello,

I am using code like this:

---

``` py
assert 0 == os.system("python setup.py sdist upload")

import xmlrpclib
import time

# A delay might be necessary before making the check.

# Wait some time for PyPI to catch up with us. Without delay
# the old version will still appear. Since this is running
# in a Buildbot, we need not be optimal.
time.sleep(360)

pypi = xmlrpclib.ServerProxy('http://pypi.python.org/pypi')
pypi_versions = pypi.package_releases("Nuitka")

assert len(pypi_versions) == 1, pypi_versions
assert nuitka_version == pypi_versions[0], (nuitka_version, pypi_versions)

print("Uploaded OK:", pypi_versions[0])
```

---
## This outputs:

```
creating dist
Creating tar archive
removing 'Nuitka-0.5.6.1' (and everything under it)
running upload
Submitting dist/Nuitka-0.5.6.1.tar.gz to https://pypi.python.org/pypi
Server response (200): OK
Traceback (most recent call last):
  File "./misc/make-pypi-upload.py", line 51, in <module>
    assert nuitka_version == pypi_versions[0], (nuitka_version, pypi_versions)
AssertionError: ('0.5.6.1', ['0.5.5.3'])
program finished with exit code 1
```

---

So this still gives the old release, despite waiting a minute. I would like to be able to check if the upload really succeeds independent from  the "upload" command exit code.

Please advise, will increasing timeouts work, should I poll in a loop for some time (will it need a new connection).

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/219

**Comment by di** [comment]
Uploads are now done through `pypi.org`, which should have a much shorter response time between uploading a distribution and it being available.

This client should migrate to using the XML-RPC API at `pypi.org`: https://packaging.python.org/guides/migrating-to-pypi-org/

Or just switch to using the JSON API: https://warehouse.readthedocs.io/api-reference/json/
