### ISSUE TITLE
PySHA3 build against debug python

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#220]
Originally reported by: **tinloaf (Bitbucket: [tinloaf](https://bitbucket.org/tinloaf), GitHub: [tinloaf](https://github.com/tinloaf))**

----------------------------------------

Hi everyone,

I hope that this is the right place to file this bug. The python bug tracker obviously wasn't. ;)

The current pysha3 package is built against a debug version of python and will not run when imported in a non-debug python. The error message is "undefined symbol: _PyUnicode_CheckConsistency"

For reference, see: http://bugs.python.org/issue23108

Kind regards,
Lukas

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/220

**Comment by berkerpeksag** [comment]
> The python bug tracker obviously wasn't. ;)

Unfortunately, PyPI tracker is also the wrong place to report this :( Please report your problem to https://github.org/tiran/pysha3
