### ISSUE TITLE
Terms of Service should be readable outside the sign-up flow

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#221]
Originally reported by: **Nick Coghlan (Bitbucket: [ncoghlan](https://bitbucket.org/ncoghlan), GitHub: [ncoghlan](https://github.com/ncoghlan))**

---

Currently, the terms of service uploaders are asked to agree to can only be referenced through https://bitbucket.org/pypa/pypi/src/3f152fc78f36784ed8c3cecce050c46779a9c939/templates/confirm.pt?at=default

This is a problem for legal review, since it's a Zope template, rather than a human readable page, and the connection between it and the software distribution service running at pypi.python.org is entirely implicit.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/221

**Comment by ncoghlan** [comment]
Local GitHub link for the ToS template: https://github.com/pypa/pypi-legacy/blob/master/templates/confirm.pt

**Comment by ewdurbin** [comment]
All set! thanks for the reminder @ncoghlan

**Comment by ewdurbin** [comment]
https://pypi.python.org/tos
