### ISSUE TITLE
django-daterange-filter 1.0.0

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#222]
Originally reported by: **shan3tala (Bitbucket: [shan3tala](https://bitbucket.org/shan3tala), GitHub: [shan3tala](https://github.com/shan3tala))**

----------------------------------------

The "Clear" button of the DateRangeForm is inactive.  Each time I have to clear the "From date" and "To date" manually i.e. <input type="reset" value="{% trans "Clear " %}">  does nothing.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/222

**Comment by berkerpeksag** [comment]
This needs to be reported to https://github.com/tzulberti/django-datefilterspec
