### ISSUE TITLE
setup.py: Version string not updated since 2005 :)

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#224]
Originally reported by: **Marc Abramowitz (Bitbucket: [msabramo](https://bitbucket.org/msabramo), GitHub: [msabramo](https://github.com/msabramo))**

----------------------------------------

This should probably be updated, or if it's not being used anymore, then maybe the `setup.py` should be removed.

```
[marca@marca-mac2 pypi]$ hg path
default = ssh://hg@bitbucket.org/pypa/pypi

[marca@marca-mac2 pypi]$ hg pull && hg update
running ssh hg@bitbucket.org 'hg -R pypa/pypi serve --stdio'
pulling from ssh://hg@bitbucket.org/pypa/pypi
searching for changes
no changes found
resolving manifests
0 files updated, 0 files merged, 0 files removed, 0 files unresolved

[marca@marca-mac2 pypi]$ hg branch
default

[marca@marca-mac2 pypi]$ ag version setup.py
10:    version = '2005-08-01',
```

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/224

**Comment by berkerpeksag** [comment]
I'm inclined to close this as 'won't fix'. The old PyPI soon to be replaced by Warehouse and the setup.py doesn't have any effect on the current PyPI (e.g. no release on PyPI). It was probably used to test the service back in 2005.
