### ISSUE TITLE
Latest version of s3cmd package is missing metadata metadata and download info.

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#229]
Originally reported by: **Daniel Beckham (Bitbucket: [daniel_beckham](https://bitbucket.org/daniel_beckham), GitHub: Unknown)**

----------------------------------------

The s3cmd package was updated to 1.5.0 in the PyPi repository, but it's metadata is empty.  You can see it here in the json API:

https://pypi.python.org/pypi/s3cmd/json

This has the affect of repository queries showing a "newer" version is available, but the version previous to 1.5.0 (1.5.0-alpha3) is installed instead.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/229

**Comment by berkerpeksag** [comment]
I can see 1.5.0, 1.5.2, 1.6.0 and 1.6.1 now and I was able to install the latest version (1.6.1) successfully.
