### ISSUE TITLE
Persistent "Connection reset by peer" when uploading wheel to pypi.python.org

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#234]
Originally reported by: **Alan Franzoni (Bitbucket: [Alan](https://bitbucket.org/Alan), GitHub: [Alan](https://github.com/Alan))**

---

Hello,
I would normally not open a ticket like that, but I'm unable to understand what's happening without feedback from the other side; I suppose there's something strange going on on pypi CDN (fastly.net). I wonder whether my box, which is quite new, has an ip address which has been used for spam/ddos attacks and it entered a sort of "blacklist" on fastly.net or pypi.python.org which kills networks connection after a while.

**Problem:**
whenever I try to upload a wheel from my CI box on 91.121.87.43 to pypi.python.org, I get a connection reset by peer. Every time. Sometimes it happens on the sdist uploading as well. My impression is that the RST happens when the connection takes a bit "too long" (e.g. more than a few seconds, as could happen when uploading files)

pcap attached.

```
/tmp/workspace$ devenv/bin/python setup.py sdist bdist_wheel register upload
running sdist
running egg_info
writing requirements to pypi104.egg-info/requires.txt
writing pypi104.egg-info/PKG-INFO
writing top-level names to pypi104.egg-info/top_level.txt
writing dependency_links to pypi104.egg-info/dependency_links.txt
writing entry points to pypi104.egg-info/entry_points.txt
[...] omitted [...]
running install_egg_info
Copying pypi104.egg-info to build/bdist.linux-x86_64/wheel/pypi104-1.10.dev0-py2.7.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/pypi104-1.10.dev0.dist-info/WHEEL
running register
Registering pypi104 to https://pypi.python.org/pypi
Server response (200): OK
running upload
Submitting dist/pypi104-1.10.dev0.tar.gz to https://pypi.python.org/pypi
Server response (200): OK
Submitting /tmp/workspace/dist/pypi104-1.10.dev0-py2-none-any.whl to https://pypi.python.org/pypi
[Errno 104] Connection reset by peer
```

**Some facts:**
- It's an Ubuntu 14.04 fully up-to-date 64 bit box, ip address: 91.121.87.43
- The same box is used to build python packages, and I NEVER get errors when downloading them from pypi.
- I've tried with twine, same result
- The artifacts, both wheel and sdist, are around 700K, nothing huge
- Another box in a neighbouring datacenter (37.187.23.76), as well as my other machines, correctly succeed in uploading files.
- Python 2.7.6, virtualenv 12.0.7, pip 6.0.8
- I've tried using the other box as an http proxy from the problem box and the upload succeeds;
- I've tried find out different ips for pypi.python.org from the CDN, and the same issue happens on EVERY IP I'VE TRIED (this is very unlikely to be a single-route connection issues)
- I wasn't able to reproduce the networking issue from my box with any other website at all. Everything seems to work properly, even when downloading or uploading large files
- I've tried to download as large a file as possible from something using the CDN, and it works; Downloading a Python release Windows debug information file succeeds, even though it takes more time than the upload I'm trying to do (tested with both wget and urllib.urlopen)
- Nothing is logged by my box's firewall about the issue, nor by the kernel.

Of course this is extremely annoying since I'd like to use that box for CI purposes and for performing stable releases as well for my software :-(

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/234

**Comment by di** [comment]
Uploads are now handled by `pypi.org`, which should not have these timeout issues. Anyone still experiencing this should open an issue at https://github.com/pypa/warehouse/issues
