### ISSUE TITLE
Limit length of description?

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#236]
Originally reported by: **Marc Abramowitz (Bitbucket: [msabramo](https://bitbucket.org/msabramo), GitHub: [msabramo](https://github.com/msabramo))**

---

The description for some packages is super long and makes the layout look bad. 

E.g.: see Deployapp in screenshot below. I think they might've confused `description` with `long_description`. 

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/236

**Comment by di** [comment]
[The limit for `Summary` is now 512 characters on `pypi.org`.](https://github.com/pypa/warehouse/blob/0a63ca66c204890cbaf4ff787380810780d9c728/warehouse/forklift/legacy.py#L375)
