### ISSUE TITLE
Request for new PyPI trove classifier for Pelican

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#238]
Originally reported by: **j (Bitbucket: [j](https://bitbucket.org/j), GitHub: [j](https://github.com/j))**

----------------------------------------

As Pelican's popularity has grown over the years, there has been a proliferation of related components made for this burgeoning community (at least 44 items in this list are directly related to Pelican): https://pypi.python.org/pypi?%3Aaction=search&term=pelican&submit=search

Moreover, the above list consists of just the packages that other folks have submitted to PyPI; there are many more in the [plugins](https://github.com/getpelican/pelican-plugins) and [themes](https://github.com/getpelican/pelican-themes) repositories that we maintainers plan to package and submit to PyPI in the months to come.

From the perspective of efficient discovery, finding Pelican plugins, themes, and other components on PyPI would be much easier for folks if the following trove classifiers were available:

```
Framework :: Pelican :: Plugins
Framework :: Pelican :: Themes
Framework :: Pelican
```

Would you please consider adding these classifiers?

Many thanks,

Justin

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/238

**Comment by berkerpeksag** [comment]
Per https://github.com/pypa/pypi-legacy/issues/301#issuecomment-226940147, this needs to be reported to https://github.com/pypa/warehouse now.
