### ISSUE TITLE
Allow deleting project documentation from pythonhosted.org

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#24]
Originally reported by: **Alex Grönholm (Bitbucket: [agronholm](https://bitbucket.org/agronholm), GitHub: [agronholm](https://github.com/agronholm))**

---

It seems like there is no way to remove the project's documentation from pythonhosted.org. Some kind of a delete button would be nice.

The "Documentation" link is admittedly useful, like the "Bug Tracker" link, but it seems like Pythonhosted is the only possible place where I can have such documentation? How about making that link editable too?

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/24

**Comment by ewdurbin** [comment]
we don't actually keep a recored of what has been uploaded to the backend for python hosted at this time... we should probably consider addressing this in the future with warehouse.

**Comment by nandoflorestan** [comment]
It is very annoying that pypi adds a link to the documentation automatically to the top of the project's description, but there is no way to remove it. Please fix this!

**Comment by ssbarnea** [comment]
Indeed, current PYPI behaviour is extremely annoying and confusing for our users. If we followed the recommendation to move the documentation to another place, like RTD now we are doomed to get notifications from our users regarding outdated documentation.

**Comment by agronholm** [comment]
Where would the outdated documentation be if you used the meta-refresh trick mentioned above?

**Comment by ssbarnea** [comment]
Example for "jira" python package published at https://pypi.python.org/pypi/jira the updated documentation is hosted at https://jira.readthedocs.io

**Comment by agronholm** [comment]
If this is your project, why haven't you used the meta-refresh trick to redirect people to the current documentation site?

**Comment by ssbarnea** [comment]
@agronholm I just did but is clearly not a pleasant experience. I will have to do the same of quite a few other packages. Also is not very search engine friendly.

**Comment by agronholm** [comment]
The whole problem is going to go away when Warehouse replaces Cheeseshop as the Python Package Index.

**Comment by ssbarnea** [comment]
I am looking forward for this moment! All my hopes are there, I checked and the web interface looks really modern. 

Any expectation regarding when this will happen? I checked https://github.com/pypa/warehouse/milestones and it seems to be a little bit over the deadlines :)

BTW, I tried to login and it only asked me to go to current pypi, I assumed that will login me on both but it didn't, so far I was not able to login to the Warehouse. Not sure if that's expected or a bug.

**Comment by di** [comment]
@ssbarnea That's expected. There's currently not much to do once logged into Warehouse besides log out. :)

**Comment by mistercrunch** [comment]
+1

**Comment by ewdurbin** [comment]
this was completed! https://github.com/pypa/pypi-legacy/issues/516
