### ISSUE TITLE
Login page should redirect to the page I was on

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#240]
Originally reported by: **Andrew Pennebaker (Bitbucket: [mcandre](https://bitbucket.org/mcandre), GitHub: [mcandre](https://github.com/mcandre))**

---

On many websites, a successful login will redirect to the page the user was on. PyPi neglects to do this (at least in Google Chrome), making me forget which page I was on, forcing me to manually adjust my browser navigation to work around this.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/240

**Comment by di** [comment]
WONTFIX for legacy, but this is the default behavior for `pypi.org` now.
