### ISSUE TITLE
setuptools-12.2.zip used by ez-setup.py is empty

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#242]
Originally reported by: **Lewis Bailey (Bitbucket: [lb0608](https://bitbucket.org/lb0608), GitHub: [lb0608](https://github.com/lb0608))**

---

The setuptools-12.2.zip file used in the ez-setup.py script is empty. This is preventing installation of setuptools (which is in turn preventint me from installing sphinx)

Also, the copy of ez-setup.py linked to by:

 https://pypi.python.org/pypi/setuptools 

has had all the whitespace removed. fortunately it is available here (found through sphinx-doc.org):

https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/242

**Comment by jamadden** [comment]
setuptools is at version 36 now, and [ez_setup.py is deprecated](https://github.com/pypa/setuptools/issues/581) so it seems to be we can consider this issue obsolete.
