### ISSUE TITLE
Trove classifiers for testing frameworks

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#247]
Originally reported by: **Ionel Cristian Mărieș (Bitbucket: [ionelmc](https://bitbucket.org/ionelmc), GitHub: [ionelmc](https://github.com/ionelmc))**

----------------------------------------

Like nose and pytest.

I'm not sure what would be a good classifier. Most packages would qualify as plugins.

Maybe `Framework :: Nose` and `Framework :: PyTest` ?

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/247

**Comment by ionelmc** [comment]
This can be closed (see https://github.com/pypa/warehouse/issues/542).
