### ISSUE TITLE
register/verify fails when providing metadata 1.2 fields, no clear error

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#248]
Originally reported by: **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**

---

I'm working on a new packaging tool, and I tried to supply some of the metadata fields from [metadata 1.2](https://www.python.org/dev/peps/pep-0345/) when registering to PyPI ('submit' and 'verify' actions). In particular, I tried `requires_python`, `requires_dist` and `project_urls`. The response was a 500 error with the generic message "Internal Server Error". (This should be in the logs of testpypi - I can cause some more of them if you need to find it)

I don't mind whether the metadata fields work, but it would be nice if the error message said something like "unrecognised data field 'requires_python'".

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/248

**Comment by di** [comment]
Uploads are now handled by `pypi.org`, which should fully support Metadata 1.2. Any new problems should be reported at https://github.com/pypa/warehouse/issues.
