### ISSUE TITLE
disable file deletion

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#252]
Originally reported by: **Mike Bayer (Bitbucket: [zzzeek](https://bitbucket.org/zzzeek), GitHub: [zzzeek](https://github.com/zzzeek))**

---

the "delete" feature of a file now does something completely different than it has done for many years, because that filename is permanently stored in the pypi system and can never be replaced.   Users who have for years known they can just press "remove" on a package and try their upload again are in for a surprise now that it's been turned off.   The flow of "Removal" should be highly modified so that it is clear that nothing is really being "deleted" here, the filename is forever and it is simply being taken off the list as something that can be downloaded.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/252

**Comment by di** [comment]
The new PyPI at `pypi.org` still has the ability to delete releases and release files, but it has some mechanisms to make sure this is not done accidentally or unintentionally:

* big red buttons and danger box
* confirm modal
* user must type the project name or release version to confirm

The new PyPI also has no notion of "hiding" a release, but adding the ability to "deprecate" a release is being considered in https://github.com/pypa/warehouse/issues/345.
