### ISSUE TITLE
Don't Create Release if Upload Rejected

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#253]
Originally reported by: **Will Bond (Bitbucket: [wbond](https://bitbucket.org/wbond), GitHub: [wbond](https://github.com/wbond))**

---

Don't create a release if the file that is attempting to be uploaded is rejected due to being a previously used name.

I experienced this using twine upload.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/253

**Comment by di** [comment]
Uploads are now done through `pypi.org`, which won't create a release if it will fail for any reason. Any outstanding problems should be raised at https://github.com/pypa/warehouse/issues.
