### ISSUE TITLE
Better download analytics for package owners

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#254]
Originally reported by: **craigcitro (Bitbucket: [craigcitro](https://bitbucket.org/craigcitro), GitHub: [craigcitro](https://github.com/craigcitro))**

---

as a package owner/maintainer, it'd be fantastic if there was any way to get something more fine-grained than "downloads per month/week/day".

i recognize that privacy concerns that put some limitations on here, but a few things i think might still be doable, in priority order:

1/ what package install led to me being installed? 

this one would be huge -- if i'm maintaining a package that's a common dependency for several packages, which ones are driving my installs? in particular, if i need to change/deprecate something, which dependencies am i most likely to break?

2/ breakdowns by OS/python version

the biggest win here would of course be py2 vs. py3 -- how many of my users have already switched? on top of that, OS information (even just linux/mac/win) would be good, esp. around testing priorities.

3/ support for user-provided data in the install request

this one's quite general, but opens up all kinds of uses. my motivation: i'd love to know (eg) all installs that come as part of a google-owned tool. these are different from a "how many people use my package" POV, and in this case, any nontrivial number probably points to somewhere we should be caching. but i can't see the breakdown, so i don't know.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/254

**Comment by jamadden** [comment]
Some of this information (OS/python versions) is available in the Google BigTable data referenced in #484.

More information on what is included in the user agent of pip is at https://github.com/pypa/pip/issues/4265

**Comment by di** [comment]
Captured in https://github.com/pypa/warehouse/issues/787.
