### ISSUE TITLE
Bad tag escaping in long_description rendering

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#259]
Originally reported by: **Ionel Cristian Mărieș (Bitbucket: [ionelmc](https://bitbucket.org/ionelmc), GitHub: [ionelmc](https://github.com/ionelmc))**

---

Seems that some tags are erroneously escaped. See https://pypi.python.org/pypi/pytest-benchmark

It displays things like `<kbd>--benchmark-min-time=<var>BENCHMARK_MIN_TIME</var></kbd>`

![Clipboard01.png](https://bitbucket.org/repo/j9KaaX/images/3206221723-Clipboard01.png)

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/259

**Comment by di** [comment]
This is fixed on `pypi.org`.
