### ISSUE TITLE
pip3 install --upgrade pip

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#260]
Originally reported by: **Jiří Navrátil (Bitbucket: [plavcik](https://bitbucket.org/plavcik), GitHub: [plavcik](https://github.com/plavcik))**

----------------------------------------

upgrade is reporting wrong version

I see Successfully installed pip-1.5.6
I expect 6.1.1

sudo pip3 install --upgrade pip
The directory '/Users/plavcik/Library/Logs/pip' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/Users/plavcik/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The directory '/Users/plavcik/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
Collecting pip from https://pypi.python.org/packages/py2.py3/p/pip/pip-6.1.1-py2.py3-none-any.whl#md5=172eb5abab25a5e0f7a7b63c7a49378d
  Downloading pip-6.1.1-py2.py3-none-any.whl (1.1MB)
    100% |################################| 1.1MB 368kB/s 
Installing collected packages: pip
  Found existing installation: pip 6.0.8
    Uninstalling pip-6.0.8:
      Successfully uninstalled pip-6.0.8

Successfully installed pip-1.5.6

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/260

**Comment by berkerpeksag** [comment]
Thanks for the report. I think the message is pretty clear, but if you think this is an unexpected behavior, please report it to the pip developers: https://github.com/pypa/pip/issues
