### ISSUE TITLE
Lost password on pypi and email no longer working - please help

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#261]
Originally reported by: **Rufus Pollock (Bitbucket: [rgrp](https://bitbucket.org/rgrp), GitHub: [rgrp](https://github.com/rgrp))**

---

Hi, I want to recover access to my account (rgrp) on pypi. I've tried password reset but I think my email is to a domain I lost control of.

How can I go about getting access to my account again?

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/261

**Comment by jamadden** [comment]
Because this was a user request regarding an account issue, and which has sat dormant for more than two years, I suspect it's safe to assume that this is obsolete and can be closed.
