### ISSUE TITLE
Getting 500 Error When Uploading Python Package

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#262]
Originally reported by: **quandyfactory (Bitbucket: [quandyfactory](https://bitbucket.org/quandyfactory), GitHub: [quandyfactory](https://github.com/quandyfactory))**

---

I'm trying to upload dicttoxml version 1.6.5 to pypi, but when I run setup.py sdist upload, I get the following response:

```
Upload failed (500): Internal Server Error
error: Upload failed (500): Internal Server Error
```

Is there something wrong with pypi or am I doing something wrong?

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/262

**Comment by Galithil** [comment]
Update : tried to update genologics-0.3.6b and this time I got a 200 OK. Im not sure it can be replicated.

**Comment by di** [comment]
Uploads are now handled by `pypi.org`, any new or existing issues should be reported at https://github.com/pypa/warehouse/issues.
