### ISSUE TITLE
can't replace a uploaded version: "Upload failed (400)"

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#263]
Originally reported by: **Jens Diemer (Bitbucket: [jedie](https://bitbucket.org/jedie), GitHub: [jedie](https://github.com/jedie))**

----------------------------------------

It's seems to be impossible to replace a uploaded release. You will get: Upload failed (400): This filename has previously been used, you should use a different version.

You can try:
* delete the uploaded file via webpage pypi.python.org
* delete the complete release via pypi.python.org

Seems that the only was is to change the version number :(

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/263

**Comment by berkerpeksag** [comment]
> Seems that the only was is to change the version number :(

Yes, this was done to improve security of users (in other words, it's a feature, not a bug :)).
