### ISSUE TITLE
‘Updated’ column of the table in the PyPI home isn’t precise enough

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#265]
Originally reported by: **Hong Minhee (Bitbucket: [dahlia](https://bitbucket.org/dahlia), GitHub: [dahlia](https://github.com/dahlia))**

---

Currently _Updated_ column of the table in the PyPI home only shows date, but nowadays so many packages are uploaded, so it shows all the same date — the date of today.

I think it would be more useful if it shows more precise date/time instead.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/265

**Comment by di** [comment]
Good point. The new PyPI at `pypi.org` doesn't show dates or times at all, so for legacy this is WONTFIX.

**Comment by di** [comment]
(to be clear, I meant "doesn't show dates or times at all for these projects on the home page")
