### ISSUE TITLE
python3 setup.py upload_docs fails

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#266]
Originally reported by: **Barry Warsaw (Bitbucket: [warsaw](https://bitbucket.org/warsaw), GitHub: [warsaw](https://github.com/warsaw))**

---

I'm trying to push the documentation for mailman 3.0.0rc1 and here's what I get:

% python3 setup.py upload_docs
running upload_docs
Submitting documentation to https://pypi.python.org/pypi
Upload failed (503): backend read error

This is kind of a blocker for the Mailman 3 release (though we're still at rc1).

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/266

**Comment by berkerpeksag** [comment]
Thank you for the report. Uploading package documentation to PyPI has been deprecated and its code has been removed:

https://github.com/pypa/pypi-legacy/blob/ce8cc966bf7f012b7012b89d70e64583a78ca464/webui.py#L2501-L2512

Closing this as 'outdated'.
