### ISSUE TITLE
Default submit action when editing package is "Remove this project"

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#267]
Originally reported by: **Rick van Hattem (Bitbucket: [WoLpH](https://bitbucket.org/WoLpH), GitHub: [WoLpH](https://github.com/WoLpH))**

---

When editing the summary for a package release, pressing enter defaults to the "submit_remove" button instead of the "submit_submit" button.

The remove button should be a type="button", not type="submit" so browsers won't use it as the default submit button.

Since this defaults to deleting the entire package and the "OK" button on the confirm page has the same issue, pressing enter twice could potentially (obviously I didn't try to test it) REMOVE the package.

To reproduce:
1. Go to the edit page for any package
2. Select one of the release summary fields (so you can update the summary)
3. Press enter

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/267

**Comment by di** [comment]
This is not a problem for the new PyPI at `pypi.org`, and since legacy is going away soon, this is a WONTFIX.
