### ISSUE TITLE
Something Went Wrong (Browse Package page)

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#268]
Originally reported by: **Aamir Khan (Bitbucket: [syst3mw0rm](https://bitbucket.org/syst3mw0rm), GitHub: [syst3mw0rm](https://github.com/syst3mw0rm))**

---

I was trying to browse the packges here - https://pypi.python.org/pypi?%3Aaction=browse. Spits out 500 error.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/268

**Comment by jamadden** [comment]
I can't currently reproduce a problem with that URL, and since the last information on this issue is over two years old I believe we can close this as obsolete.
