### ISSUE TITLE
requests 2.6.1 and 2.6.2 causes ResponseNotReady error for 303 answers

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#269]
Originally reported by: **asetyaev (Bitbucket: [asetyaev](https://bitbucket.org/asetyaev), GitHub: [asetyaev](https://github.com/asetyaev))**

---

now I've got for redirections:

```
#!python

  File "bin/eggs/requests-2.6.2-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "bin/eggs/requests-2.6.2-py2.7.egg/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', ResponseNotReady())
```

requests 2.6 works fine.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/269

**Comment by jamadden** [comment]
requests is currently at [version 2.17.3](https://pypi.python.org/pypi/requests), and this issue tracker is just for issues with PyPI itself, not the packages hosted there, so I believe we can close this. If there are further issues with requests, please report them to [the requests issue tracker](https://github.com/requests/requests/issues).
