### ISSUE TITLE
Request to remove scriptnado from PyPI

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#270]
Originally reported by: **Skip Montanaro (Bitbucket: [skip_montanaro](https://bitbucket.org/skip_montanaro), GitHub: Unknown)**

----------------------------------------

Got this at webmaster@python.org:

Scott Nesmith <scott@ign.com>

to webmaster 
Hello,

We have determined that an ex-employee has submitted to the Python Software Foundation a copy of scripts "Scriptnado" containing sensitive IGN-internal keys, without authorization

https://pypi.python.org/pypi/scriptnado

Please remove this package and any copies of it.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/270

**Comment by berkerpeksag** [comment]
It looks like the scriptnado project has already been removed from PyPI.
