### ISSUE TITLE
Wrong error message when uploading package without PKG-INFO

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#271]
Originally reported by: **anatoly techtonik (Bitbucket: [techtonik](https://bitbucket.org/techtonik), GitHub: [techtonik](https://github.com/techtonik))**

---

It is

```
Error processing form

Invalid version, cannot be parsed as a valid PEP 440 version.
```

the upload is through online form.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/271

**Comment by di** [comment]
Uploads are now done through `pypi.org`, if this is still a problem raise an issue at https://github.com/pypa/warehouse/issues.
