### ISSUE TITLE
Broken nav if all releases are hidden

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#272]
Originally reported by: **anatoly techtonik (Bitbucket: [techtonik](https://bitbucket.org/techtonik), GitHub: [techtonik](https://github.com/techtonik))**

---

If all package releases are hidden, clicking edit link in top breadcrumb gives an error.

For example:
https://pypi.python.org/pypi?name=bablos&version=%28latest+release%29&:action=submit_form

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/272

**Comment by di** [comment]
The new PyPI at `pypi.org` has no notion of hidden releases, so this only happens on legacy which is going away soon.
