### ISSUE TITLE
Wrong url HomePage on pyHook

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#273]
Originally reported by: **GoldenKlaus (Bitbucket: [GoldenKlaus](https://bitbucket.org/GoldenKlaus), GitHub: Unknown)**

----------------------------------------

Hi!

On page https://pypi.python.org/pypi/pyHook
is wrong web address (Home Page: http://pyhook.wiki.sourceforge.net/). Url not respond. True http://sourceforge.net/p/pyhook/wiki/Main_Page/

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/273

**Comment by berkerpeksag** [comment]
Please report this at https://sourceforge.net/p/pyhook/bugs/
