### ISSUE TITLE
Restore removed file

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#275]
Originally reported by: **anatoly techtonik (Bitbucket: [techtonik](https://bitbucket.org/techtonik), GitHub: [techtonik](https://github.com/techtonik))**

----------------------------------------

I accidentally removed my release, and when I upload it again, it complains that "This filename has previously been used, you should use a different version."

It should be possible to restore the filename with the same checksum, size and name or reupload it again.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/275

**Comment by berkerpeksag** [comment]
This is a duplicate of #263.
