### ISSUE TITLE
xmlrpc should support `until`, `limit` parameters too

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#276]
Originally reported by: **Antti Haapala (Bitbucket: [antti_haapala](https://bitbucket.org/antti_haapala), GitHub: Unknown)**

---

The xmlrpc interface only supports `since` for various log modes; now the problem is that the results are built into a list on the server side; anything that has _too_ many entries possibly has a chance to make the pypi rpc server grind to halt; adding a until/limit could mitigate this.

E.g., what will happen if I execute `client.changelog_since_serial(0)`.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/276

**Comment by di** [comment]
We won't be adding any new features to XML-RPC since it will be deprecated. [Migrating to using `pypi.org`](https://packaging.python.org/guides/migrating-to-pypi-org/) might help for problematic requests.
