### ISSUE TITLE
Reporting bug in package hosted on PyPi

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#277]
Originally reported by: **Mohak  Sukhwani (Bitbucket: [mohakPy](https://bitbucket.org/mohakPy), GitHub: Unknown)**

----------------------------------------

How do I report bug in 'package' downloaded from PyPi. ? :O  (Even not sure if this is the correct place to ask this question :O )

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/277

**Comment by berkerpeksag** [comment]
This is basically a duplicate of #3.
