### ISSUE TITLE
Show top downloaded packages in site

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#281]
Originally reported by: **Allan Daemon (Bitbucket: [AllanDaemon](https://bitbucket.org/AllanDaemon), GitHub: [AllanDaemon](https://github.com/AllanDaemon))**

----------------------------------------

There are 2 lists in the site. One of the latest updated packages and another for the newest packages.

I think it would be nice to have a list of top downloaded packages, split by all time, latest month and latest week.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/281

**Comment by berkerpeksag** [comment]
https://pypi.io/ now lists top projects so I don't think we need to add the same functionality to pypi-legacy. Further improvements should reported at https://github.com/pypa/warehouse
