### ISSUE TITLE
More trove classifiers: Python 3.5, Apache Licenses

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#287]
Originally reported by: **Antti Haapala (Bitbucket: [antti_haapala](https://bitbucket.org/antti_haapala), GitHub: Unknown)**

----------------------------------------

Python 3.5 lacks classifier; I have been testing my package for Python 3.5 alphas and will be testing it against betas; it would be nice to show this on PyPI too.

Another issue is the Apache License: currently there is a trove classifier for 
"License :: OSI Approved :: Apache Software License"; which I take to refer to the version 1.0; there is also Apache Software License 1.1 which is actually wildly different with 1.0.

There is also completely different "Apache License 2.0", which is *not* a license for Apache Software, but a generally usable license. This would definitely need a different trove classifier.

The latter is notable in that it is listed, along with the Academic Free License, as [the only acceptable licenses](https://wiki.python.org/moin/PythonSoftwareFoundationLicenseFaq#Contributing_Code_to_Python) for code that could be merged into Python or the Standard library.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/287

**Comment by berkerpeksag** [comment]
Python 3.5 has already been added. The Apache part of the issue is basically a duplicate of #91.
