### ISSUE TITLE
Deleting a package preserves its pythonhosted.org documentation

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#288]
Originally reported by: **Vincent Jacques (Bitbucket: [jacquev6](https://bitbucket.org/jacquev6), GitHub: [jacquev6](https://github.com/jacquev6))**

---

Hello,

I recently deleted the package AnotherPyGraphvizAgain, but its documentation is still available: http://pythonhosted.org/AnotherPyGraphvizAgain/

This is related to #24 (and maybe #192), but in my case I can't upload an empty doc: the package is gone.

Thanks,

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/288

**Comment by ewdurbin** [comment]
if #516 is merged, I'll add the `doc_destroy` method to `remove_pkg`

**Comment by berkerpeksag** [comment]
PR #516 has been merged. Closing this as 'fixed'.
