### ISSUE TITLE
Add license field to DOAP

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#29]
Originally reported by: **Anonymous**

---

This is a follow-up ticket of http://sourceforge.net/p/pypi/bugs/361/

The request is to add DOAP license information extracted from the categories when possible/available.

The problem is that DOAP expects a URI for the license and it turns out that http://spdx.org/licenses/ provides some.

Attached in a patch that browse the categories of a package, check if one of them is a license and if so, check if the license is known to the license table allowing mapping the category to a URI.

/!\ patch not tested (but I don't expect it breaks anything).

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/29

**Comment by di** [comment]
DOAP is no longer supported by PyPI.
