### ISSUE TITLE
django-core lib is throwing a 500

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#290]
Originally reported by: **Troy Grosfield (Bitbucket: [troygrosfield](https://bitbucket.org/troygrosfield), GitHub: [troygrosfield](https://github.com/troygrosfield))**

----------------------------------------

When I go to:

- https://pypi.python.org/pypi/django-core

I see:

![Screen Shot 2015-05-25 at 2.45.05 PM.png](https://bitbucket.org/repo/j9KaaX/images/2156924064-Screen%20Shot%202015-05-25%20at%202.45.05%20PM.png)

This is blocking a critical release to prod for me.  I am the repo owner.  Let me know if there's anything I can do.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/290

**Comment by berkerpeksag** [comment]
Thanks for the report. The problem probably wasn't related to the django-core itself. Looking at the commit history from May 24th to May 26th might help to find the actual cause.
