### ISSUE TITLE
Table on contents of packages is now simple text

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#292]
Originally reported by: **Luca Fabbri (Bitbucket: [keul](https://bitbucket.org/keul), GitHub: [keul](https://github.com/keul))**

---

Not sure when this begun (at least a week ago) but on packages that use restrucutred text table of contents directive is now displaying a simple text section, not a list of internal links to sections.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/292

**Comment by jamadden** [comment]
It seems to me that the last comment on this issue ("Typos") identified the problem (incorrect ReST leads to plain-text rendering). Since it's been two years without further updates, I believe we can close this issue.
