### ISSUE TITLE
Yet another recover lost password for an old and invalid email

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#294]
Originally reported by: **David Douard (Bitbucket: [douardda](https://bitbucket.org/douardda), GitHub: [douardda](https://github.com/douardda))**

---

Sorry for the inconvenience but I also cannot reset my password for my pypi account. The login is douardda (same as my accounts on bitbucket and github).

I'd like to upload a new version (1.3.0) of chaussette I released today.

I can send a gpg signed message to prove (kind of) I'm the "real douardda", if necessary.

Thank you very very much,

David Douard

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/294

**Comment by jamadden** [comment]
1.3.0 of chaussette was uploaded a few days after this request was entered, so presumably we can consider the issue resolved.
