### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#296]
Originally reported by: **Samuel Riolo (Bitbucket: [codeix](https://bitbucket.org/codeix), GitHub: [codeix](https://github.com/codeix))**

---

Hey everyone,
I try to reuse my old account name "codeix" on PyPI. It's important to me  because I use the same name everywhere (e.g. github). Sadly I have forgotten my password  and the email that the account was registered to, sriolo@raptus.com, is not active anymore as it was from a former employer of mine.
Could you help me?

Thanks in advance

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/296

**Comment by di** [comment]
@codeix If this is still a problem for you, could you send me an email at di@python.org?
