### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#298]
Originally reported by: **Miki Tebeka (Bitbucket: [tebeka](https://bitbucket.org/tebeka), GitHub: [tebeka](https://github.com/tebeka))**

---

After confirming email I can't login to PyPI with the password and when trying to rest I get: user "Cyberint" is unknwon to me. However when trying to re-register it says the user is already there. 

The forums at https://sourceforge.net/p/pypi/support-requests/ (which is linked from "PyPI Support") seems pretty deserted. What is the right location for these kind of issues? 

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/298

**Comment by di** [comment]
@tebeka it looks like you've been able to log in recently so I'm assuming this has been resolved.
