### ISSUE TITLE
Cannot login into other services using pypi openID

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#299]
Originally reported by: **Sven Bartscher (Bitbucket: [IchUndNichtDu](https://bitbucket.org/IchUndNichtDu), GitHub: [IchUndNichtDu](https://github.com/IchUndNichtDu))**

---

For a long time I used to login to other services using my PyPI openID. One example is StackExchange.

Recently I tried to login into StackExchange. So I logged in into pypi and then directed the StackExchange login to pypi.python.org. To my surprise it just said "Something went wrong". (The URL I was directed to is this: https://pypi.python.org/pypi?:action=openid_endpoint&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.return_to=https%3A%2F%2Fstackexchange.com%2Fusers%2Fauthenticate%2F%3Fs%3D916a332e-f319-438f-b396-86a43fed36db%26dnoa.userSuppliedIdentifier%3Dpypi.python.org&openid.realm=https%3A%2F%2Fstackexchange.com%2Fusers%2Fauthenticate%2F&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.alias3=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.alias3.if_available=alias1%2Calias2%2Calias3%2Calias4&openid.alias3.mode=fetch_request&openid.alias3.type.alias1=http%3A%2F%2Fschema.openid.net%2FnamePerson&openid.alias3.count.alias1=1&openid.alias3.type.alias2=http%3A%2F%2Fschema.openid.net%2Fcontact%2Femail&openid.alias3.count.alias2=1&openid.alias3.type.alias3=http%3A%2F%2Faxschema.org%2FnamePerson&openid.alias3.count.alias3=1&openid.alias3.type.alias4=http%3A%2F%2Faxschema.org%2Fcontact%2Femail&openid.alias3.count.alias4=1)

My pypi login is "ichundnichtdu" (without quotes).

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/299

**Comment by di** [comment]
PyPI is no longer an OpenID provider.
