### ISSUE TITLE
Request new Trove Classifier for pytest plugins

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#301]
Originally reported by: **Bruno Oliveira (Bitbucket: [nicoddemus](https://bitbucket.org/nicoddemus), GitHub: [nicoddemus](https://github.com/nicoddemus))**

----------------------------------------

Currently pytest contains dozens of plugins on PyPI (100+), as a simple [search](https://pypi.python.org/pypi?%3Aaction=search&term=pytest&submit=search) for "pytest" shows.

We would like to make it easier for users to find these plugins, as some plugins are left out for not following this naming scheme (e.g. [backports.unittest_mock](https://pypi.python.org/pypi/backports.unittest_mock), [jaraco.mongodb](https://pypi.python.org/pypi/jaraco.mongodb)), so we request to include a new trove classifier:

```
Framework :: Pytest :: Plugin
```

Pytest's maintainers (myself included) [demonstrated interest](https://github.com/pytest-dev/plugincompat/issues/16) of supporting this officially by advertising it in the documentation and the [plugincompat]() service (which automatically finds plugins and check compatibility against different pytest versions).

(I created a duplicate of this issue at [warehouse](https://github.com/pypa/warehouse/issues/542) as I'm not sure which repository handles the classifiers).

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/301

**Comment by berkerpeksag** [comment]
Per https://github.com/pypa/pypi-legacy/issues/301#issuecomment-226940147 and https://github.com/pypa/warehouse/issues/542, I'm closing this as 'fixed'.
