### ISSUE TITLE
Deleting a release does not remove it from warehouse

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#302]
Originally reported by: **Raffi Enficiaud (Bitbucket: [renficiaud](https://bitbucket.org/renficiaud), GitHub: Unknown)**

---

I just deleted yayi 0.8.7.dev0 from pypi, but the version on warehouse is still listed. 

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/302

**Comment by berkerpeksag** [comment]
I guess by deleting you mean files not the 0.8.7.dev0 release itself. I can see 0.8.7dev0 on both legacy and future PyPI:

* https://pypi.python.org/pypi/Yayi/0.8.7.dev0
* https://pypi.io/project/Yayi/0.8.7.dev0/

But I can't install 0.8.7.dev0 since the files are gone.

**Comment by raffienficiaud** [comment]
Hi,

To be honest, I do not remember. I believe that at that time, there was no way to "remove" a package from warehouse, while it is possible from pypi. 

The 0.8.7.dev0 was I believe removed and then re-uploaded.

Is it possible to remove versions/packages from the warehouse now?

**Comment by berkerpeksag** [comment]
Warehouse and legacy PyPI now use the same database so I think this is not an issue anymore. Please let me know if you still reproduce the problem. Thank you for the report!

> Is it possible to remove versions/packages from the warehouse now?

I don't think this is implemented in Warehouse yet, but removing it via legacy PyPI should do the trick.
