### ISSUE TITLE
My newly created packages is giving a "Something went wrong" error

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#304]
Originally reported by: **Joel Weirauch (Bitbucket: [mathamoz](https://bitbucket.org/mathamoz), GitHub: [mathamoz](https://github.com/mathamoz))**

---

I added this package yesterday and it looks like something went wrong somewhere.  I followed the directions for uploading packages, so I'm not sure what is wrong.

https://pypi.python.org/pypi/convertiq/0.1.1

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/304

**Comment by di** [comment]
Project had been deleted, nothing else to do here.
