### ISSUE TITLE
My package is not downloadable even though it was succesfully uploaded

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#307]
Originally reported by: **endre bakken stovner (Bitbucket: [endre_bakken_stovner](https://bitbucket.org/endre_bakken_stovner), GitHub: Unknown)**

---

When I try to download it it just says package not found or st similar.

https://pypi.python.org/pypi?name=biomartian&version=0.0.1&:action=display

The dl counter is also at 0 so no bots have succeeded in doing so either.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/307

**Comment by di** [comment]
[Seems to have been resolved](https://pypi.org/project/biomartian/).
