### ISSUE TITLE
Probable name conflict in the regex module

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#308]
Originally reported by: **pnugues (Bitbucket: [pnugues](https://bitbucket.org/pnugues), GitHub: [pnugues](https://github.com/pnugues))**

----------------------------------------

I wrote a small tokenizing program that uses a unicode class: p{L} and regex.split(). I named this program tokenize.py. The program crashes. In addition, it is impossible to load the regex package from the interpreter.

When I rename the program tokenize_aux.py, everything works fine.

There is no such a problem with the re package, but I can't use the unicode class...

I use Python 3.5.0b3 on a Mac 10.10.4

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/308

**Comment by berkerpeksag** [comment]
You are getting the error because tokenize is a module in the Python standard library and you can't shadow the standard library modules.
