### ISSUE TITLE
Unable to register/upload package to pypi

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#311]
Originally reported by: **Amjith Ramanujam (Bitbucket: [amjith](https://bitbucket.org/amjith), GitHub: [amjith](https://github.com/amjith))**

----------------------------------------

I'm trying to upload a new version of my package https://pypi.python.org/pypi/mycli via command line. 

Whenever I run python setup.py register or python setup.py sdist upload, I get an error: 

```
#!python

running upload
Submitting dist/mycli-1.1.1.tar.gz to https://pypi.python.org/pypi
Upload failed (500): Internal Server Error
error: Upload failed (500): Internal Server Error
```

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/311

**Comment by berkerpeksag** [comment]
This is a duplicate of #148. The `setup.py` mentioned by OP has been changed to use `long_description` instead of `README.md` in https://github.com/dbcli/mycli/commit/c230fc69e2509c79190e53589457f161accd1626.
