### ISSUE TITLE
Add link to setup.py on package homepage

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#312]
Originally reported by: **yaccz (Bitbucket: [yaccz](https://bitbucket.org/yaccz), GitHub: [yaccz](https://github.com/yaccz))**

---

Add link to setup.py on package homepage.

Hackage (haskell pypi) package homepage: http://hackage.haskell.org/package/text
Notice the link `Package description`_. This can be very helpful.

Also links to source code http://hackage.haskell.org/package/text-1.2.1.3/docs/Data-Text.html .

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/312

**Comment by berkerpeksag** [comment]
Thank you for the report. Since this is a feature request, it would be better to open it in [Warehouse](https://github.com/pypa/warehouse)'s issue tracker.
