### ISSUE TITLE
Register/upload throws a 502 when classifiers are incorrect

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#317]
Originally reported by: **Lynn Root (Bitbucket: [roguelynn](https://bitbucket.org/roguelynn), GitHub: [roguelynn](https://github.com/roguelynn))**

---

Hey folks -

I've only tested this on the testpypi site, but I've seen the behavior on the regular PyPI as well.

I noticed that when running `python setup.py register` and `python setup.py upload`, I would get a 502 error.  

I would manually circumvent this by uploading the package via the web UI, including hand-writing the PKG-INFO details.  

However, I noticed when I tried to attach my own PKG-INFO file to the web form, I would get parser errors (e.g. invalid classifier).  It was merely some typos since I hand-wrote a few within my setup.py.

Once corrected, attaching my own PKG-INFO to the web form worked fine, as well as the `python setup.py register` and `upload` commands.

I'm thinking a 502 should probably not be returned in this case, maybe a 400 with a better description.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/317

**Comment by econchick** [comment]
just FYI I'm @econchick here

**Comment by di** [comment]
Fixed in Warehouse 🙂

(and all uploads now go through Warehouse, so this will always give a nice error message when classifiers are invalid now)
