### ISSUE TITLE
authkit problems

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#319]
Originally reported by: **James Michael DuPont (Bitbucket: [h4ck3rm1k3](https://bitbucket.org/h4ck3rm1k3), GitHub: [h4ck3rm1k3](https://github.com/h4ck3rm1k3))**

----------------------------------------

pip install authkit

Downloading/unpacking authkit from
https://pypi.python.org/packages/source/A/AuthKit/AuthKit-0.4.5.tar.gz#md5=0336ba96de32ea97f6058bed5549b30c
  Downloading AuthKit-0.4.5.tar.gz (114kB): 114kB downloaded
  Running setup.py (path:/tmp/pip-build-5o_VwD/authkit/setup.py)
egg_info for package authkit

....

Downloading/unpacking elementtree<=1.3,>=1.2 (from authkit)
  Could not find any downloads that satisfy the requirement
elementtree<=1.3,>=1.2 (from authkit)
  Some externally hosted files were ignored (use --allow-external
elementtree to allow).
Cleaning up...
No distributions at all found for elementtree<=1.3,>=1.2 (from authkit)

And it seems that all the websites for this project are offline/broken.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/319

**Comment by berkerpeksag** [comment]
You should report this to authkit developers (elementtree is in the standard library since forever so they should fix their packaging).
