### ISSUE TITLE
Some packages not showing up when searching by name

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#326]
Originally reported by: **MattDMo (Bitbucket: [MattDMo](https://bitbucket.org/MattDMo), GitHub: [MattDMo](https://github.com/MattDMo))**

---

Some packages are not showing up in the search results, even though entering the URL directly works. For example:

Search: [`pandas`](https://pypi.python.org/pypi?%3Aaction=search&term=pandas&submit=search)

Direct: [`pandas`](https://pypi.python.org/pypi/pandas)

---

Search: [`patsy`](https://pypi.python.org/pypi?%3Aaction=search&term=patsy&submit=search)

Direct: [`patsy`](https://pypi.python.org/pypi/patsy)

---

Search: [`pytz`](https://pypi.python.org/pypi?%3Aaction=search&term=pytz&submit=search)

Direct: [`pytz`](https://pypi.python.org/pypi/pytz)

---

Search: [`prettytable`](https://pypi.python.org/pypi?%3Aaction=search&term=prettytable&submit=search)

Direct: [`prettytable`](https://pypi.python.org/pypi/prettytable)

---

Search: [`alabaster`](https://pypi.python.org/pypi?%3Aaction=search&term=alabaster&submit=search)

Direct: [`alabaster`](https://pypi.python.org/pypi/alabaster)

---

Search: [`blaze`](https://pypi.python.org/pypi?%3Aaction=search&term=blaze&submit=search)

Direct: [`blaze`](https://pypi.python.org/pypi/blaze)

---

Search: [`bottleneck`](https://pypi.python.org/pypi?%3Aaction=search&term=bottleneck&submit=search)

Direct: [`bottleneck`](https://pypi.python.org/pypi/bottleneck)

---

Search: [`biopython`](https://pypi.python.org/pypi?%3Aaction=search&term=biopython&submit=search)

Direct: [`biopython`](https://pypi.python.org/pypi/biopython)

---

Search: [`cherrypy`](https://pypi.python.org/pypi?%3Aaction=search&term=cherrypy&submit=search)

Direct: [`cherrypy`](https://pypi.python.org/pypi/cherrypy)

---

Search: [`django`](https://pypi.python.org/pypi?%3Aaction=search&term=django&submit=search)

Direct: [`django`](https://pypi.python.org/pypi/django)

---

Search: [`ipython`](https://pypi.python.org/pypi?%3Aaction=search&term=ipython&submit=search)

Direct: [`ipython`](https://pypi.python.org/pypi/ipython)

---

Search: [`mahotas`](https://pypi.python.org/pypi?%3Aaction=search&term=mahotas&submit=search) (redirects to [SeedWaterSegmenter](https://pypi.python.org/pypi/SeedWaterSegmenter/0.5.8.0))

Direct: [`mahotas`](https://pypi.python.org/pypi/mahotas)

---

And there are many more. I can't find any rhyme or reason to what is found and what isn't.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/326

**Comment by MikimotoH** [comment]
## My package is searchable by pypi or pip3
I created a package, named [furigana](https://pypi.python.org/pypi/furigana) . This package page can be browsed by a user not logined to pypi. However, if I search "furigana" in the homepage of [pypi](https://pypi.python.org/pypi), it can not find my package "furigana".
I also used `pip3 search` to search it, and it find nothing.

I ran below commands to create archive and upload it by **twine**:
```
python3 setup.py test
python3 setup.py sdist
twine upload dist/furigana-0.0.7.tar.gz
```

The output message of twine is:
```
Uploading distributions to https://upload.pypi.org/legacy/
Uploading furigana-0.0.7.tar.gz
```

My ~/.pypirc is
```
[distutils]
index-servers =
    pypi

[pypi]
repository: https://upload.pypi.org/legacy/
username:<my_username>
password:<my_password>
```

My [setup.py](https://github.com/MikimotoH/furigana/blob/3529fc51434ca3bc12366daa16ce709f9ba800d6/setup.py) is
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from setuptools import setup
from os import path

here = path.abspath(path.dirname(__file__))

# Get the long description from the relevant file
with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
    long_description = f.read()

setup(name='furigana',
        version='0.0.7',
        description='''convert Kanji in Japanese into Kanji attached with Hiragana (Furigana(振り仮名))
        For example, "澱んだ街角" => "澱(よど)んだ街角(まちかど)" ''',
        long_description = long_description,
        author='Miki.Liu',
        author_email='mikimotoh@gmail.com',
        url='https://github.com/MikimotoH/furigana',
        packages=['furigana'],
        classifiers=[
            # How mature is this project? Common values are
            #   3 - Alpha
            #   4 - Beta
            #   5 - Production/Stable
            'Development Status :: 3 - Alpha',
            'Environment :: Console',
            'Intended Audience :: Developers',
            'Intended Audience :: Science/Research',
            'License :: OSI Approved :: MIT License',
            'Programming Language :: Python :: 3',
            'Topic :: Software Development :: Libraries :: Python Modules',
            'Topic :: Text Processing :: Linguistic',
            ],
        keywords='Japanese Language Processing',
        )
```
