### ISSUE TITLE
unable to upload documentation

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#334]
Originally reported by: **cmorisset (Bitbucket: [cmorisset](https://bitbucket.org/cmorisset), GitHub: [cmorisset](https://github.com/cmorisset))**

----------------------------------------

Hi,

I'm trying to upload documentation at http://pythonhosted.org/PyNeb using the same kind of  .zip file as always, but systematicaly failed (with Error 503 backend read error). I tried from different IPs and locations, no way.
Thanks for any tip or info.
Cheers,
Christophe

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/334

**Comment by berkerpeksag** [comment]
This is a duplicate of #266.
