### ISSUE TITLE
Omniture Package installation failing

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#337]
Originally reported by: **Som shekar (Bitbucket: [somapatel](https://bitbucket.org/somapatel), GitHub: Unknown)**

----------------------------------------

Omniture pyhon package installation is failing with below error.

    long_description=open('README.md').read(),
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/337

**Comment by berkerpeksag** [comment]
This is a packaging issue (they need to add `README.md` to `MANIFEST.in`) in the Omniture package and it should be reported to them.
