### ISSUE TITLE
Request for a new XMPP classifier in the "chat" namespace

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#339]
Originally reported by: **Sam Whited (Bitbucket: [SamWhited](https://bitbucket.org/SamWhited), GitHub: [SamWhited](https://github.com/SamWhited))**

----------------------------------------

I would like to request that the `Topic :: Communications :: Chat` namespace have a new classifer for XMPP added:

```
Topic :: Communications :: Chat :: XMPP
```

This would make the full namespace (at the time of this writing):

```
Topic :: Communications :: Chat
Topic :: Communications :: Chat :: AOL Instant Messenger
Topic :: Communications :: Chat :: ICQ
Topic :: Communications :: Chat :: Internet Relay Chat
Topic :: Communications :: Chat :: Unix Talk
Topic :: Communications :: Chat :: XMPP
```

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/339

**Comment by SamWhited** [comment]
Following up on this (sorry it fell off my radar), I agree with your reasoning there, `Topic :: Internet :: XMPP` is probably enough for now. What would it take to get this moving forward? Is it agreed that it should be a thing? Would a PR be enough?

**Comment by berkerpeksag** [comment]
Per https://github.com/pypa/pypi-legacy/issues/301#issuecomment-226940147, this needs to be reported to https://github.com/pypa/warehouse now.

**Comment by ewdurbin** [comment]
completed.
