### ISSUE TITLE
Broken link in package submission

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#345]
Originally reported by: **Alan Rominger (Bitbucket: [AlanCoding](https://bitbucket.org/AlanCoding), GitHub: [AlanCoding](https://github.com/AlanCoding))**

----------------------------------------

Say I'm going to submit a package to PyPI, so I log in and go to the [package submission link](https://pypi.python.org/pypi?%3Aaction=submit_form). First option is:

```
#!html

<p id="submitheader">1. Use the setup.py "<a href="https://packaging.python.org/en/latest/distributing.html#uploading-your-project-to-pypi">register</a>" command.</p>

```
The "register" link goes to a broken URL. I believe that it should be the following:

[http://python-packaging-user-guide.readthedocs.org/en/latest/distributing/#uploading-your-project-to-pypi](http://python-packaging-user-guide.readthedocs.org/en/latest/distributing/#uploading-your-project-to-pypi)

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/345

**Comment by berkerpeksag** [comment]
The URL https://packaging.python.org/en/latest/distributing/#uploading-your-project-to-pypi works now.
