### ISSUE TITLE
Modern items under Topic :: Software Development :: Version Control

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#346]
Originally reported by: **Marcin Kasperski (Bitbucket: [Mekk](https://bitbucket.org/Mekk), GitHub: [Mekk](https://github.com/Mekk))**

---

I suggest adding

```
    Topic :: Software Development :: Version Control :: Mercurial
```

Rationale: 
- there exist `:: CVS`, `:: RCS`, and `:: SCCS` in this space, if they are worth it, Mercurial deserves it too
- people (including myself) publish to PyPi Mercurial extensions and Mercurial related tools (Mercurial itself is writen in Python, so Python is it's native language)

As we are on it, it may also make sense to add 

```
    Topic :: Software Development :: Version Control :: Git
    Topic :: Software Development :: Version Control :: Subversion
```

Those tools aren't Python-related, but surely more pupular than SCCS, which also isn't ;-)

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/346

**Comment by di** [comment]
This classifier has already been added.
