### ISSUE TITLE
Search still not working

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#353]
Originally reported by: **Benjamin Gathmann (Bitbucket: [abulhol](https://bitbucket.org/abulhol), GitHub: [abulhol](https://github.com/abulhol))**

----------------------------------------

See problem depicted in #326.

E.g. packages cybox and maec are not showing up in the search:

* https://pypi.python.org/pypi/cybox/2.1.0.12
* https://pypi.python.org/pypi/maec

It is also strange that the latest version for these is not showing in PyPI, but when I run pip install, I get them (2.1.0.13 for cybox and 4.1.0.13 for maec)

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/353

**Comment by berkerpeksag** [comment]
This is still valid. I was able to find them via Warehouse:

* https://pypi.io/search/?q=cybox
* https://pypi.io/search/?q=maec

**Comment by ewdurbin** [comment]
this is bizarre, i'll have to take a look at what's causing these to confuse our elastic search index.

**Comment by ewdurbin** [comment]
resolved. was same issue as #517
