### ISSUE TITLE
Typo in Ukrainian language classifier

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#355]
Originally reported by: **Alexander Shepetko (Bitbucket: [ashep](https://bitbucket.org/ashep), GitHub: [ashep](https://github.com/ashep))**

---

In https://pypi.python.org/pypi?%3Aaction=list_classifiers Ukrainian language specified as 'Ukranian', which is inccorect.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/355

**Comment by di** [comment]
I've deprecated the `Natural Language :: Ukranian` classifier, and added `Natural Language :: Ukrainian`.
