### ISSUE TITLE
Bug in request password reset

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#356]
Originally reported by: **Enrique Garcia (Bitbucket: [garcianavalon](https://bitbucket.org/garcianavalon), GitHub: [garcianavalon](https://github.com/garcianavalon))**

----------------------------------------

Hi,

When I try to reset my password in PyPI I get a fatal error and nothing happens. I can't register again because it says the username is already taken. Is there anything I can do to reset my password?

My username is garcianavalon

Thanks for any help.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/356

**Comment by berkerpeksag** [comment]
I think this has already been resolved. I was able to reset my password successfully.
