### ISSUE TITLE
"logging" package breaks pip

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#360]
Originally reported by: **Giles Thomas (Bitbucket: [gpjt](https://bitbucket.org/gpjt), GitHub: [gpjt](https://github.com/gpjt))**

---

If you "pip install logging", it installs a logging package (I'm guessing one that pre-dates or became the system package) that is incompatible with pip.  From that point onwards, you cannot use pip, even to uninstall logging.  

The workaround is to manually remove the logging directory from your site-packages.  But this is very much non-obvious for non-experts, who therefore have a single-line command that will (from their perspective) trash their Python setup until they can get an expert to fix it.

Not sure what the ideal solution would be, as I don't know what use cases the version on PyPI is useful for, if any.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/360

**Comment by jamadden** [comment]
There is an ongoing discussion around this. See https://github.com/pypa/pypi-legacy/issues/585 specifically (and similarly https://github.com/pypa/pypi-legacy/issues/644 and [this distutils thread](https://mail.python.org/pipermail/distutils-sig/2017-June/030592.html) that focus more on security aspects). I think we can close this issue in favor of the others that are getting more eyeballs (I'll be sure to comment to cross-reference.)
