### ISSUE TITLE
the home page of pyh 0.1 is error

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#362]
Originally reported by: **Kim Kong (Bitbucket: [kim_kong](https://bitbucket.org/kim_kong), GitHub: Unknown)**

----------------------------------------

the home page of [pyh](https://pypi.python.org/pypi/PyH/0.1) should not be http://code/google.com/p/pyh/, so that "easy_install pyh" will report an error 
It should be http://sourceforge.net/projects/pyh/

error log:
```
#!

Searching for pyh
Reading https://pypi.python.org/simple/pyh/
Reading http://code/google.com/p/pyh/
Download error on http://code/google.com/p/pyh/: [Errno 8] nodename nor servname provided, or not known -- Some packages may not be found!
No local packages or download links found for pyh
error: Could not find suitable distribution for Requirement.parse('pyh')
```

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/362

**Comment by berkerpeksag** [comment]
Please report this to the pyh developers.
