### ISSUE TITLE
Cannot change email address in "User profile" page ("Your details") page of PyPi site

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#363]
Originally reported by: **pekrau (Bitbucket: [pekrau](https://bitbucket.org/pekrau), GitHub: [pekrau](https://github.com/pekrau))**

---

I am trying to change the email address associated with the account **scilifelab** at PyPi, because the current email points to a person who has left us.

For a long time we believed that the password to have been lost, but yesterday it was found, and it has now been changed successfully.

But the email address appear impossible to change. When I try to change it and press "Update details", I get a page saying "Something went wrong...". When I go back, no change has been made.

Note that it is just the email that cannot be changed. The password change worked fine.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/363

**Comment by di** [comment]
Email addresses should be changed at pypi.org now.
