### ISSUE TITLE
many packages have empty list of links

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#365]
Originally reported by: **Russell Ballestrini (Bitbucket: [russellballestrini](https://bitbucket.org/russellballestrini), GitHub: [russellballestrini](https://github.com/russellballestrini))**

----------------------------------------

For example markdown package causes pip to fail.

https://pypi.python.org/simple/markdown/

The cached version that google has looks like this:

http://webcache.googleusercontent.com/search?q=cache:f5dJ5EkBLVwJ:https://pypi.python.org/simple/markdown/+&cd=1&hl=en&ct=clnk&gl=us

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/365

**Comment by ewdurbin** [comment]
This was an unintentional and temporary issue during a migration of data

**Comment by GLMeece** [comment]
I was just trying to download [which](https://pypi.python.org/pypi/which/), but `pip` complains:
>  Could not find a version that satisfies the requirement which (from versions: )
> No matching distribution found for which

After turning on `--verbose` I see that it find any links in https://pypi.python.org/simple/which/

What is the recommended solution to this? As a user, I cannot update the simple page for referenced links.
