### ISSUE TITLE
Unable to install TurboJson 1.3.2 using easy_install.

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#370]
Originally reported by: **Radhika Grover (Bitbucket: [radhika_grover](https://bitbucket.org/radhika_grover), GitHub: Unknown)**
---

easy_install -U TurboJson is failing with the below error-

user@ubuntu-dev:~$ sudo easy_install -U TurboJSON
Searching for TurboJSON
Reading https://pypi.python.org/simple/TurboJSON/
Best match: TurboJson 1.3.2
Downloading https://pypi.python.org/packages/2.7/T/TurboJson/TurboJson-1.3.2-py2.7.egg#md5=8708fcb8979c661104c9b444e5428484
Processing TurboJson-1.3.2-py2.7.egg
Moving TurboJson-1.3.2-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding TurboJson 1.3.2 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/TurboJson-1.3.2-py2.7.egg
Processing dependencies for TurboJSON
Searching for simplejson>=1.9.1
Reading https://pypi.python.org/simple/simplejson/
Best match: simplejson 3.8.1
Downloading https://pypi.python.org/packages/source/s/simplejson/simplejson-3.8.1.tar.gz#md5=b8441f1053edd9dc335ded8c7f98a974
Processing simplejson-3.8.1.tar.gz
Writing /tmp/easy_install-4VcmRi/simplejson-3.8.1/setup.cfg
Running simplejson-3.8.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-4VcmRi/simplejson-3.8.1/egg-dist-tmp-K89rCq
zip_safe flag not set; analyzing archive contents...
simplejson.tests.**init**: module references **file**
Adding simplejson 3.8.1 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/simplejson-3.8.1-py2.7-linux-x86_64.egg
Searching for PEAK-Rules>=0.5a1.dev-r2600
Reading https://pypi.python.org/simple/PEAK-Rules/
No local packages or download links found for PEAK-Rules>=0.5a1.dev-r2600
error: Could not find suitable distribution for Requirement.parse('PEAK-Rules>=0.5a1.dev-r2600')
user@ubuntu-dev:~$

**https://pypi.python.org/simple/peak-rules/ seems to be broken.**  Is it? Earlier, it was mostly providing PEAK-Rules>=0.5a1.dev-r2713.
---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/370

**Comment by berkerpeksag** [comment]
Thanks for the report. PyPI doesn't support external downloads anymore so you either need to download it from http://peak.telecommunity.com/snapshots/ or contact the author to ask if they can upload a new release to PyPI.
