### ISSUE TITLE
pymysql 0.70 connection errors

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#372]
Originally reported by: **Julian Barnett (Bitbucket: [jbarnett1981](https://bitbucket.org/jbarnett1981), GitHub: [jbarnett1981](https://github.com/jbarnett1981))**

----------------------------------------

Script have suddenly stopped working, and reviewing the docs it's unclear whether or not there were any changes to creating the pymysql connection objects. Looking at the underlying source, it doesn't seem like much has changed there.

Where I used to be able to create a connection object like so:

db = pymysql.connect(host=db_host, user=db_username, passwd=db_password, db=db_name)

Now that pip is installing 0.70 by default, creating the connection objects results in the following errors:

In [15]: db = pymysql.connect(host=db_host, user=db_username, password=db_password, db=db_name)
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
<ipython-input-15-416496995c08> in <module>()
----> 1 db = pymysql.connect(host='<IP_OBSCURED>', user=db_username, password=db_password, db=db_name, charset='utf8', port=3306)

/Library/Python/2.7/site-packages/pymysql/__init__.pyc in Connect(*args, **kwargs)
     86     """
     87     from .connections import Connection
---> 88     return Connection(*args, **kwargs)
     89
     90 from pymysql import connections as _orig_conn

/Library/Python/2.7/site-packages/pymysql/connections.pyc in __init__(self, host, user, password, database, port, unix_socket, charset, sql_mode, read_default_file, conv, use_unicode, client_flag, cursorclass, init_command, connect_timeout, ssl, read_default_group, compress, named_pipe, no_delay, autocommit, db, passwd, local_infile, max_allowed_packet, defer_connect, auth_plugin_map)
    676             self.socket = None
    677         else:
--> 678             self.connect()
    679
    680     def _create_ssl_ctx(self, sslp):

/Library/Python/2.7/site-packages/pymysql/connections.pyc in connect(self, sock)
    888
    889             self._get_server_information()
--> 890             self._request_authentication()
    891
    892             if self.sql_mode is not None:

/Library/Python/2.7/site-packages/pymysql/connections.pyc in _request_authentication(self)
   1096
   1097         self.write_packet(data)
-> 1098         auth_packet = self._read_packet()
   1099
   1100         # if authentication method isn't accepted the first byte

/Library/Python/2.7/site-packages/pymysql/connections.pyc in _read_packet(self, packet_type)
    963
    964         packet = packet_type(buff, self.encoding)
--> 965         packet.check_error()
    966         return packet
    967

/Library/Python/2.7/site-packages/pymysql/connections.pyc in check_error(self)
    392             errno = self.read_uint16()
    393             if DEBUG: print("errno =", errno)
--> 394             err.raise_mysql_exception(self._data)
    395
    396     def dump(self):

/Library/Python/2.7/site-packages/pymysql/err.pyc in raise_mysql_exception(data)
    118 def raise_mysql_exception(data):
    119     errinfo = _get_error_info(data)
--> 120     _check_mysql_exception(errinfo)

/Library/Python/2.7/site-packages/pymysql/err.pyc in _check_mysql_exception(errinfo)
    110     errorclass = error_map.get(errno, None)
    111     if errorclass:
--> 112         raise errorclass(errno, errorvalue)
    113
    114     # couldn't find the right error number

OperationalError: (1045, u"Access denied for user 'readonly'@'<IP_OBSCURED>' (using password: NO)")

----
It also notes on the last line that using password: NO...shouldn't it be YES?

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/372

**Comment by berkerpeksag** [comment]
> Is there any way to get 0.7.0 to support MySQL 5.1?

Please report this to pymysql developers. Thanks!
