### ISSUE TITLE
unittest subtest() causing execution stop after the first failure

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#373]
Originally reported by: **ke camilla (Bitbucket: [camillake](https://bitbucket.org/camillake), GitHub: [camillake](https://github.com/camillake))**

----------------------------------------

environment:
python 3.4
nose1.3.7

I have a test in the format of subtests

def test_even(self):
    for i in range(0, 6):
        with self.subTest(i=i):
                self.assertEqual(i % 2, 0)
According to the official document, the test execution loop will be done whether any of assertion is pass or failed.

I use nose to execution tests programmed using unittest framework. The tests with self.subTest stop after first failure.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/373

**Comment by berkerpeksag** [comment]
This is not a problem with PyPI and the unittest module. Please report it to nose developers. Thanks!
