### ISSUE TITLE
clang 3.4.dev192547 cannot used with python 3.4 64bits

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#374]
Originally reported by: **Ashish Kumar Sahu (Bitbucket: [chauashish](https://bitbucket.org/chauashish), GitHub: Unknown)**

----------------------------------------

formatting is not properly followed according to python 3 

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/374

**Comment by berkerpeksag** [comment]
This doesn't look like an issue with PyPI to me. Please report this to clang developers.
