### ISSUE TITLE
Installation PyMongo cannot find the register, but it is there

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#377]
Originally reported by: **Daniel Silva (Bitbucket: [netdaniels](https://bitbucket.org/netdaniels), GitHub: [netdaniels](https://github.com/netdaniels))**

----------------------------------------

pymongo-3.2.win32-py3.5.msi

When trying to install.
*****
Python version 3.5 required, wich was not found in the registry.*******

I believe that by the time you find this issue, I'll be already lost my deadline in the course I'm currently taking on https://university.mongodb.com

But it's a very ugly bug, so, I decided to report.

Regards,

Daniel.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/377

**Comment by berkerpeksag** [comment]
This was a Python issue and it has already been fixed in https://bugs.python.org/issue26071.
