### ISSUE TITLE
gmpy2: numerical error in simple addition?

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#378]
Originally reported by: **Jaideep Ramachandran (Bitbucket: [jaideepr](https://bitbucket.org/jaideepr), GitHub: [jaideepr](https://github.com/jaideepr))**

----------------------------------------

A simple floating-point addition x+y in with precision 4 (i.e. IEEE mantissa width 3), with 3 bits for exponent (emax=3, emin=-4) for x = mpfr('0.75'), y = mpfr('0.03125') incorrectly gives mpfr('0.75') as result when it should be mpfr('0.8125'). Note that 0.3125 is a subnormal number for this reduced precision format. Terminal interaction attached, am I doing something wrong?

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/378

**Comment by jaideepr** [comment]
Tons of apologies, I did n't actually request to close (I thought I had done so): this is not a bug, it was my error in interpreting the result of the operation (I did the operation bit-wise separately). I think the result that gmpy2 produces in the reported case is correct.
