### ISSUE TITLE
Spyware packages

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#379]
Originally reported by: **Adrian Klaver (Bitbucket: [aklaver](https://bitbucket.org/aklaver), GitHub: [aklaver](https://github.com/aklaver))**

---

The below is one of many packages that are dummy packages for spyware:

https://pypi.python.org/pypi/docker/2.1.8

They lead to this:

http://svs-repo.informatik.uni-hamburg.de/

where you find the following:

What kind of information is collected in the process of this thesis?
"
Currently, we are collecting the following information. No sensitive data, that reveals personal information, is ever sent to this server.

```
The package manager name and version that triggered the operation. Example: pip
The operating system and architecture of the host. Example: Linux-3.14.48
Boolean flag that indicates whether the code was run with administrative rights.
The past command history that involved the package manager. Example: Output of history | grep pip
A list of installed modules/packages that were installed with the package manager.
Hardware information of the host. Example: Outputs of lspci for linux. On OS X, we grab the outputs of system_profiler -detailLevel mini
```

"

Seems fairly benign on the surface, but it is a precedent I do not think is healthy or wise. 

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/379

**Comment by giacgbj** [comment]
Thesis related to this issue: http://incolumitas.com/data/thesis.pdf .

**Comment by jamadden** [comment]
Related to https://github.com/pypa/pypi-legacy/issues/644. A similar discussion is ongoing in [this distutils thread](https://mail.python.org/pipermail/distutils-sig/2017-June/030592.html)  and #585. 

This particular package is now run by the official docker group, and the offending version has been removed, so I think this issue can be closed.
