### ISSUE TITLE
Very easy to accidentally list all packages

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#383]
Originally reported by: **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**

----------------------------------------

https://pypi.python.org/pypi is the homepage. But https://pypi.python.org/pypi/ (with a trailing slash) is a list of every package on PyPI. I occasionally go to the second URL accidentally, and then quickly try to close the tab as it slows right down. My general expectation in web browsing is that trailing slashes should be insignificant.

Could it be made a bit harder to accidentally land on the enormous list? The link in the sidebar already points to https://pypi.python.org/pypi?%3Aaction=index .

Apologies if this has already been discussed, I did try searching and didn't find it.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/383

**Comment by berkerpeksag** [comment]
Per https://github.com/pypa/pypi-legacy/issues/383#issuecomment-226940466, I think we can close this as "won't fix" now.
