### ISSUE TITLE
"Use the source..." link on Selenium 2.70. page throws a 404

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#384]
Originally reported by: **Amit Paunikar (Bitbucket: [AmitPaunikar](https://bitbucket.org/AmitPaunikar), GitHub: Unknown)**

----------------------------------------

On the Selenium module page (https://pypi.python.org/pypi/selenium/2.7.0), when I clicked on the link "Use the source Luke" it showed me a 404 error-

404. That’s an error.

The requested URL /p/selenium/source/browse/trunk/py/selenium/webdriver/remote/webdriver.py was not found on this server. That’s all we know. 

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/384

**Comment by berkerpeksag** [comment]
PyPI doesn't control what to show in package metadata (it just reads package's metadata) so this needs to be reported to the Selenium developers: https://github.com/seleniumhq/selenium

Thanks!
