### ISSUE TITLE
git package for pip is missing

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#393]
Originally reported by: **Yotam Praag (Bitbucket: [netyou](https://bitbucket.org/netyou), GitHub: Unknown)**

----------------------------------------

When trying to access the git package via pip there is a 404 page.
Also, the package is not found when performring a pip install git

MISSING:
https://pypi.python.org/pypi/git/3.2.4

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/393

**Comment by berkerpeksag** [comment]
This is a duplicate of #352.
