### ISSUE TITLE
search for workfront or python-workfront does not return my package

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#394]
Originally reported by: **Chris Withers (Bitbucket: [chrisw](https://bitbucket.org/chrisw), GitHub: [chrisw](https://github.com/chrisw))**

----------------------------------------

Hi Guys,

If I search for "python-workfront", I get a list of all packages
If I search for "workfront", I get nothing.

In both cases, I'd expect https://pypi.python.org/pypi/python-workfront to be returned.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/394

**Comment by cjw296** [comment]
I'm actually @cjw296 on GitHub, not sure what I am on BitBucket...

But yeah, indexing is basically totally broken on pypi, and has been for months...

**Comment by berkerpeksag** [comment]
It looks like this has been fixed by https://github.com/pypa/pypi-legacy/commit/6e96e374004ca9a854ca541b1b90144d6e72ac92.
