### ISSUE TITLE
Download Stats Have Stopped Working (again)

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#396]
Originally reported by: **Matthias Manhertz (Bitbucket: [madmat3001](https://bitbucket.org/madmat3001), GitHub: [madmat3001](https://github.com/madmat3001))**

---

I noticed at the start of February that the download stats for my package twistml were stagnating. They have not increased since. 
I use the vanity package to track the downloads and its developer sent me here, as this has happened before. ([Issue #330](https://bitbucket.org/pypa/pypi/issues/330/download-stats-have-stopped-working), [Vanity Issue on github](https://github.com/aclark4life/vanity/issues/18))
On 12/02/16 I checked the total downloads for Django to make sure this was not related to my project. According to vanity, django has not had a single download since then.

Interestingly the download counters on the packages' pypi pages keep updating. (The ones showing last day, week and month)

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/396

**Comment by jantman** [comment]
I don't like to be a bad person and comment on a closed issue, but... where do we go to find out when Warehouse will be live? I can't seem to find any public information on it.

I was relying on pypi's download counters to gauge usage of my public projects... with them broken, I'm tempted to be a Bad Person and try to put some sort of phone-home logic in my libraries, just to try and get an idea of how many people are using it and what versions.

I also still don't see any information on how to volunteer help. I'd be more than happy to assist with the current infrastructure if there's need for more hands/eyeballs.

**Comment by ewdurbin** [comment]
@jantman the stats in warehouse are an accurate reflection. you can use them for the same purposes.

**Comment by libeclipse** [comment]
@ewdurbin As far as I can tell, there are no stats at warehouse anymore.

**Comment by ewdurbin** [comment]
well shit.

**Comment by ewdurbin** [comment]
@jantman @libeclipse

for the time being, the details on the big query (publicly accessible, just login with google) are available here: https://mail.python.org/pipermail/distutils-sig/2016-May/028986.html that will _actually_ answer questions like "how many people are using it and what versions", where as the previous download stats were highly volatile and provided no insight into versions. they were arguably just vanity numbers.

if someone is interested in proposing a cron job or something similar to restore the stats into pypi-legacy i'll happily review.

**Comment by ewdurbin** [comment]
@jantman as a point of order, i understand your concerns and what you are trying to accomplish but wanted to state that vague threats of doing "bad things" like "phoning home" on install and such are really not productive in encouraging maintainers or contributors, it really just makes us feel bad that we do not have more time to contribute to specific needs.

**Comment by ewdurbin** [comment]
for instance here is a _useful_ download query representing download counts _by version_ _by day_ since July 1st for one of my projects.

```sql
SELECT
  DATE(timestamp) as day,
  file.project,
  file.version,
  COUNT(*) as total_downloads,
FROM
  TABLE_DATE_RANGE(
    [the-psf:pypi.downloads],
    TIMESTAMP("20160701"),
    CURRENT_TIMESTAMP()
  )
WHERE
  file.project = 'clandestined'
GROUP BY
  day, file.project, file.version
ORDER BY
  day asc
LIMIT 100
```

**Comment by ewdurbin** [comment]
<img width="525" alt="screen shot 2016-08-04 at 2 27 35 pm" src="https://cloud.githubusercontent.com/assets/1200832/17413552/a0e438d8-5a4f-11e6-8f5c-044e455d50bf.png">

**Comment by ewdurbin** [comment]
@dstufft @berkerpeksag i'm going to lock this conversation for now, feel free to unlock if you believe it warrants further discussion.
