### ISSUE TITLE
My package doesn't appear in the search results anymore

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#397]
Originally reported by: **Luca Rebuffi (Bitbucket: [lucarebuffi](https://bitbucket.org/lucarebuffi), GitHub: [lucarebuffi](https://github.com/lucarebuffi))**

----------------------------------------

I am maintaining packages named "Oasys" and "ShadowOui" in the Pypi site since several months. These packages are available by query with the keyword "oasys".

Since a couple of weeks the result of the query with the keyword and eventually with their names directly does not contain the last versions. On the contrary, all the previous versions, also the ones I deleted are shown. Paradoxically, the command "pip install <package>" finds the correct last version.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/397

**Comment by farrokhi** [comment]
Same problem with [dnsdiag](https://pypi.python.org/pypi/dnsdiag) package

**Comment by nickjacobson** [comment]
For https://pypi.python.org/pypi/testresources package the search turns up 2 old versions (0.2.7 and 1.0.0) instead of the newest, 2.0.1

**Comment by ewdurbin** [comment]
want to be clear that the pypi maintainers *are* aware and motivated to work on resolving these concerns. there have just been many more pressing concerns in the maintenance of PyPI and development of the next generation codebase [warehouse](https://github.com/pypa/warehouse)

**Comment by divad** [comment]
Is there a likely ETA for fixing the search and similar issues, or an ETA for warehouse to replace the existing pypi? I don't think many people know just how broken pypi is, despite it being vitally important to so many projects and services and underpins so much of python!

**Comment by icemac** [comment]
What about already using https://pypi.io (aka warehouse)? Its index seems to be complete and correct. For many parts (aka searching a package) it should be sufficient.

**Comment by farrokhi** [comment]
@icemac how to instruct pip to use this as default?

**Comment by icemac** [comment]
@farrokhi: Why do you want to use https://pypi.io with `pip`? I thought this issue is about the web search on http://pypi.python.org.

**Comment by divad** [comment]
Its about both, surely... (the pip search is broken too...)

**Comment by farrokhi** [comment]
@icemac they use the same backend afaik

**Comment by icemac** [comment]
It seems that there was an update in the search index lately. Yesterday I was able to find the current version of my package named `toll` using all three searches. (No older versions showed up.) This was not the case before: It did not appear at all.

**Comment by ewdurbin** [comment]
Search has been patched up on PyPI. I'm triaging search related issues right now and most of the issues flagged in this thread have been resolved.

Please open a new issue with any ongoing search related bugs.
