### ISSUE TITLE
Package not appearing in search results

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#399]
Originally reported by: **Stuart George (Bitbucket: [bigmassa](https://bitbucket.org/bigmassa), GitHub: [bigmassa](https://github.com/bigmassa))**

----------------------------------------

Hi sorry if a duplicate but the following package which i look after has never appeared in the search results. Am guessing the only reason its ever downloaded is from appearing on the home page. 

djangocms-site-search

Ty 

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/399

**Comment by ewdurbin** [comment]
This is resolved.

**Comment by davaya** [comment]
What does "This is resolved"mean?  I don't see any further comments here, but by email I have a message saying status changed from "resolved" to "wontfix".    Is the problem resolved because the bugs causing it have been removed, or because they are going to be ignored?

**Comment by ewdurbin** [comment]
@davaya the issue was resolved. there was a mishandling of the transition from bitbucket to GitHub. see https://pypi.python.org/pypi?%3Aaction=search&term=django+site+search&submit=search for instance.

**Comment by ewdurbin** [comment]
if you continue to have issues with search indexing please note the following I ndexing is periodic, it may take 15-30 minutes for packages and releases to appear in results.

if you continue to see issues or have a new report, please file a new issue.
