### ISSUE TITLE
wrapt doesn't work for inherited classes

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#405]
Originally reported by: **Xin Guan (Bitbucket: [xinvar](https://bitbucket.org/xinvar), GitHub: [xinvar](https://github.com/xinvar))**

----------------------------------------

wrapt libary is awesome! However for class annotations, it only works if the annotated class is the leaf class. Any parent class cannot be annotated.

Error message:
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/405

**Comment by berkerpeksag** [comment]
Please use wrapt's issue tracker to report your problem. I think your problem has already been reported at https://github.com/GrahamDumpleton/wrapt/issues/51
