### ISSUE TITLE
unable to register pytsk3 package on pypitest

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#406]
Originally reported by: **Joachim Metz (Bitbucket: [joachimmetz](https://bitbucket.org/joachimmetz), GitHub: [joachimmetz](https://github.com/joachimmetz))**

----------------------------------------

I'm one of the maintainer of the pytsk3 package on pypi (https://pypi.python.org/pypi?%3Aaction=pkg_edit&name=pytsk3). I'm trying to register the same package on pypitest but I'm running into:

Forbidden

You are not allowed to store 'pytsk3' package information

I do not see a pytsk3 on pypitest and have no additional information why the project registration is failing.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/406

**Comment by berkerpeksag** [comment]
You will need to create a separate account for testpypi and add a new entry in your `,pypirc`:

```ini
[test]
repository = https://testpypi.python.org/pypi
username = <YOUR_USERNAME>
password = <YOUR_PASSWORD>
```

Then pass `-r test` to your `setup.py` command or use `twine`.
