### ISSUE TITLE
Packaged added, is available, but no index search results

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#411]
Originally reported by: **Jenda Mudron (Bitbucket: [jenmud](https://bitbucket.org/jenmud), GitHub: [jenmud](https://github.com/jenmud))**

----------------------------------------

I have successfully added my packages `ruruki` and `ruruki-eye`,** I am able** to pip install them with no issues, but when I search for the packages, I get no results !

**BUT** I do get results if I search for them in [Warehouse](https://warehouse.python.org/search/?q=ruruki)

Packages on Pypi:

* https://pypi.python.org/pypi/ruruki/0.0.5
* https://pypi.python.org/pypi/ruruki-eye/0.1.1

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/411

**Comment by ewdurbin** [comment]
search seems to be returning reasonable results on PyPI for `ruruki` and `ruruki-eye` on pypi.

**Comment by jenmud** [comment]
Yip I pushed out a new release and it seems to be working now. Not sure
what or why it happened.

Jenda

On Sat, 2 Jul 2016 21:31 Ernest W. Durbin III <notifications@github.com>
wrote:

> Closed #411 <https://github.com/pypa/pypi-legacy/issues/411>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pypa/pypi-legacy/issues/411#event-711172262>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA5broxuvS_n3mMAvqYYDPJzY8z-o2Dbks5qRkwcgaJpZM4JDqB7>
> .
>
-- 


Thanks
Jenda Mudron
(phone)
