### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#413]
Originally reported by: **qwerty (Bitbucket: [tupak](https://bitbucket.org/tupak), GitHub: [tupak](https://github.com/tupak))**

----------------------------------------

When I try to use pip to install .WHl files that I download from gohike I get this print out:

Processing c:\users\owner\downloads\ta_lib-0.4.9-cp27-none-win_amd64.whl
	Complete output from command python setup.py egg_info:
	Traceback <most recent call last>:
	  File "<string>", line 1, in <module>
	IOError: [Errno 2] No such file or directory: 'c:\\users\\owner\\appdata\\local\\temp\
\pip-9gwk2c-build\\setup.py'
	-----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\owner\appdata\local\temp\pip-9gwk2c-build\

I'm using python 2.7.11 and pip 8.1.0.  I was able to install the files a few weeks ago but then I updated numpy and pandas broke and then pip wouldn't work, I don't know exactly what happened other than later I figured out that pandas has to be reinstalled with every numpy update.  I also updated systemtools/distutils and I don't know if that caused the problem with installing a WHL. I uninstalled python and then reinstalled it but that didn't fix the problem.  When I go 'pip install <module>' it works, but the module TA-Lib is just a wrapper for a library that its hard to install so I have to use the pre-compiled WHL which contains the library.  I posed 2 questions on SO but wasn't able to get a solution:

http://stackoverflow.com/questions/35837241/pip-wont-install-whl-files
http://stackoverflow.com/questions/35811104/python-2-7-11-pip-8-0-3-cant-install-gohike-whl-of-ta-lib-0-4-9?lq=1

Thanks to anyone who can help me!

EDIT:
I had a backup of my python folder and I tried copy pasting the ta-lib folder into new python folder and now it works!  Still working on hdf5/h5py.  I checked the date-modified on my files, and at about the time I started having problems this file was updated, the only file in its folder to be updated at that time:
Python27\Lib\encodings\string_escape

Also, later on these folders and their contents were updates, I don't know if they were updated earlier or not: 
pkg_resources , setuptools.

Hope it helps that maybe I narrowed the problem down to one file!

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/413

**Comment by berkerpeksag** [comment]
Please report this to pip issue tracker. Thanks!
