### ISSUE TITLE
cx_oracle 5.21 win32 installer does not work

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#415]
Originally reported by: **Tealduck (Bitbucket: [Tealduck](https://bitbucket.org/Tealduck), GitHub: Unknown)**

----------------------------------------

I have a fresh install of Python 3.5 (32-bit) on my Windows 8 system. Everything seems to work fine regarding Python except for this installer. When you attempt to run the program it immediately claims that Python 3.5 is required and that it cannot find the registry key.

**Tip for Developer**: If you are not 100% certain of what the registry key is then simply prompt the user so we can tell you. BTW - The key you are looking for is HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Python\PythonCore\3.5-32 and not HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Python\PythonCore\3.5

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/415

**Comment by berkerpeksag** [comment]
This looks like either an installer or distutils problem to me. The problem has already been reported to the cx_Oracle mailing list: https://sourceforge.net/p/cx-oracle/mailman/message/34855467/
