### ISSUE TITLE
Claim package: agithub

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#417]
Originally reported by: **Jonathan Paugh (Bitbucket: [jpaugh](https://bitbucket.org/jpaugh), GitHub: [jpaugh](https://github.com/jpaugh))**

---

I am the author of the [agithub](https://github.com/jpaugh/agithub/) package, and current maintainer.
 I've tried to upload a new version, but I have apparently lost access to update the PyPi listing somehow; perhaps I added up with a different account?

My user base would [like to see](https://github.com/jpaugh/agithub/issues/17) the new version uploaded to PyPi. 
Can you help with that? Thanks!

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/417

**Comment by justinclift** [comment]
@ewdurbin Is there literally no-one who can give access to @jpaugh, so he can update his agithub package on PyPi.

It's heading towards 6 months outstanding... which seems like a bit of a wait for an "I'm locked out of the system, please let me in!" type admin task. :wink:

**Comment by ewdurbin** [comment]
@justinclift thanks for your feedback. this issue was ported over from bitbucket in an automated script, i appreciate the ping on it. but please remember that "admin tasks" are still volunteer based and effectively best effort.

i'll look into this now.

**Comment by justinclift** [comment]
Thanks.  @ewdurbin The sound of crickets was getting of my nerves. :wink:

**Comment by ewdurbin** [comment]
if you'd like to contribute to help move things along, feel free to begin triaging existing issues here.

**Comment by ewdurbin** [comment]
@justinclift if you'd like to contribute to help move things along, feel free to begin triaging existing issues here.

**Comment by justinclift** [comment]
Like you, I'm pretty flat out [volunteering on projects too](https://github.com/sqlitebrowser/sqlitebrowser). :wink:

**Comment by ewdurbin** [comment]
@jpaugh it looks like @jaredhobbs uploaded releases for the package. i don't see anything in our audit logs that you ever controlled the package on PyPI.

we don't make changes like this by fiat in general, so i'll ask kindly that @jaredhobbs add you as a maintainer or transfer ownership of the package on github.

**Comment by jpaugh** [comment]
Thanks! I understand, and I appreciate the effort.
Although, I'd be just as happy if @jaredhobbs were continue maintaining it. ;-)

**Comment by jaredhobbs** [comment]
@jpaugh I'll look into transferring ownership to you as soon as I get home!

**Comment by jaredhobbs** [comment]
@jpaugh: is your pypi username the same as github?

**Comment by jamadden** [comment]
It looks like this is resolved as far as PyPI admin tasks go, leaving only coordination between @jaredhobbs and @jpaugh , so I think we can close the PyPI issue to help clean up the tracker.
