### ISSUE TITLE
PyPI XML API Does not handle package name normalization

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#418]
Originally reported by: **Andrew Gross (Bitbucket: [andrewgross](https://bitbucket.org/andrewgross), GitHub: [andrewgross](https://github.com/andrewgross))**

---

Hey,

I was debugging some issues with a private python package service that I run.  I was having issues install the package "Flask-Login" if I tried to install it using "--index-url" to point to my service:

```
#!bash

pip install Flask-Login --index-url https://my.localshop.server/simple/
```

I realized that the issue is because I am using a recent version of `pip`.  Starting around 6.0 it will automatically normalize package names, so `Flask-Login` becomes `flask-login`.  This is fine when talking to PyPI since the `simple` and `JSON` APIs will properly resolve the package name back to `Flask-Login`.  

However, if you use the XMLRPC API, you will not get these corrections.  Instead you will receive no results for `flask-login`.  Since `pip` is now automatically converting package names, this means you will never get the package if your resolver uses the XML api.

Here is a demonstration of the issue:

```
#!python

>>> import xmlrpclib
>>> client = xmlrpclib.ServerProxy('https://pypi.python.org/pypi')
>>> client.package_releases('flask-login')
[]
>>> client.package_releases('Flask-Login')
['0.3.2']
```

However, if we use the JSON API via cURL (and trim some of the extra varnish headers), we see a 301 redirect to the capitalization corrected URL.

```
#!bash

curl -I https://pypi.python.org/pypi/flask-login/json

HTTP/1.1 301 Moved Permanently
Server: nginx/1.8.1
Location: /pypi/Flask-Login/json
Content-Length: 0
Accept-Ranges: bytes
Date: Thu, 17 Mar 2016 22:14:56 GMT
Via: 1.1 varnish
Age: 3
Connection: keep-alive

```

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/418

**Comment by andrewgross** [comment]
If this is biting anyone else, you can try pointing to the warehouse installation at `pypi.io`.  It properly normalizes queries before returning results.

```python
>>> import xmlrpclib
>>> client = xmlrpclib.ServerProxy('https://pypi.io/pypi')
>>> package = "backports.shutil_get_terminal_size"
>>> client.package_releases(package)
['1.0.0']
>>> package = "backports.shutil-get-terminal-size"
>>> client.package_releases(package)
['1.0.0']
```

**Comment by andrewgross** [comment]
Unfortunately this endpoint does not support the `.package_urls` endpoint.

```python
....
>>> package = "backports.shutil_get_terminal_size"
>>> client.package_releases(package)
['1.0.0']
>>> client.package_urls(package, '1.0.0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1482, in parse_response
    return u.close()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 794, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault -32601: 'server error; requested method not found'>
```

**Comment by ewdurbin** [comment]
it seems that matching the behavior of warehouse is a good option for now, since that _will_ be replacing this codebase in the future. i'll get that moving.

**Comment by ewdurbin** [comment]
i've pushed these changes up to testpypi. please give testpypi a @andrewgross and let me know if you find any issues.

**Comment by ewdurbin** [comment]
welp, seems there are more subtleties to this than expected. i've reverted that change in testpypi. hold for further digging :(

**Comment by di** [comment]
This is fixed for https://pypi.org:

```
>>> import xmlrpclib
>>> client = xmlrpclib.ServerProxy('https://pypi.org/pypi')
>>> client.package_releases('flask-login')
['0.1.1', '0.1.2', '0.1.3', '0.2.0', '0.2.1', '0.2.2', '0.2.3', '0.2.4', '0.2.5', '0.2.6', '0.2.7', '0.2.8', '0.2.9', '0.2.10', '0.2.11', '0.3.0', '0.3.1', '0.3.2', '0.4.0', '0.4.1']
>>> client.package_releases('Flask-Login')
['0.1.1', '0.1.2', '0.1.3', '0.2.0', '0.2.1', '0.2.2', '0.2.3', '0.2.4', '0.2.5', '0.2.6', '0.2.7', '0.2.8', '0.2.9', '0.2.10', '0.2.11', '0.3.0', '0.3.1', '0.3.2', '0.4.0', '0.4.1']
```

[Please migrate any APIs for which this is a problem.](https://warehouse.readthedocs.io/api-reference/integration-guide/#migrating-to-the-new-pypi)

**Comment by andrewgross** [comment]
👏
