### ISSUE TITLE
version-less page for numpy broken, Error 404 Not Found

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#423]
Originally reported by: **peterjc (Bitbucket: [peterjc](https://bitbucket.org/peterjc), GitHub: [peterjc](https://github.com/peterjc))**

----------------------------------------

Working:

https://pypi.python.org/pypi/numpy/1.11.0rc2
https://pypi.python.org/pypi/numpy/1.10.4

These all have a link to the version-less URL, but this currently fails:

https://pypi.python.org/pypi/numpy

e.g.

```
$ wget https://pypi.python.org/pypi/numpy
--2016-03-25 10:04:21--  https://pypi.python.org/pypi/numpy
Resolving pypi.python.org... 185.31.18.223
Connecting to pypi.python.org|185.31.18.223|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-03-25 10:04:21 ERROR 404: Not Found.
```

A trailing slash makes no difference, https://pypi.python.org/pypi/numpy/ also gives me a 404 error.

Most other packages seem to be working, e.g. https://pypi.python.org/pypi/scipy or https://pypi.python.org/pypi/scipy/

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/423

**Comment by peterjc** [comment]
Both https://pypi.python.org/pypi/numpy/ and https://pypi.python.org/pypi/numpy seem to be working now, so this can be closed.
