### ISSUE TITLE
pyemd 0.2.0: missing file in archive

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#428]
Originally reported by: **AntoineMaleprade (Bitbucket: [AntoineMaleprade](https://bitbucket.org/AntoineMaleprade), GitHub: Unknown)**

----------------------------------------

In the package provided by pypi at this address:
https://pypi.python.org/pypi/pyemd/0.2.0
package download link:
https://pypi.python.org/packages/source/p/pyemd/pyemd-0.2.0.tar.gz#md5=1cd8428384903939e596fc5bd2bb688a

the file :
pyemd/emd.pyx
is missing compared to the 0.2.0 github release (https://github.com/wmayner/pyemd/releases/tag/0.2.0)

This missing file prevent the user from building the extension.
Pip is also unable to build this extension when it downloads the package from this link.

workaround: install last developer version:
pip install "git+https://github.com/wmayner/pyemd@develop#egg=pyemd"

You should re-upload the archive from the github 0.2.0 release

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/428

**Comment by berkerpeksag** [comment]
This is not an issue with PyPI and it looks like the maintainer of the pyemd package has already been fixed the main problem in https://github.com/wmayner/pyemd/commit/43ef3bfd73e5c9f7c0acfa1f2adc61079f80165e and released 0.3.0 on 2016-06-02.
