### ISSUE TITLE
Backwards-compatible un-hashed package paths

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#438]
Originally reported by: **Johannes Löthberg (Bitbucket: [kyrias](https://bitbucket.org/kyrias), GitHub: [kyrias](https://github.com/kyrias))**

---

Hello,

For Arch Linux packages we very often use PyPI URLs to download the tarballs of software.  The old process for updating was generally just changing the package version and updating the hash, and it would Just Work™.  But with the new hashed package paths we need to go to the PyPI website manually and copy the URL to be able to update.  This gets really annoying when having to update a lot of python packages.

Is there any chance that you could add a new URL path that lets you get all files without having to specify the hash?  I understand why it was added, but it's useless for us since we check the checksum of the file ourselves, and just makes the process more annoying.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/438

**Comment by toddrme2178** [comment]
I am getting a 404 when I try to download a wheel from the following address: `https://files.pythonhosted.org/packages/py2.py3/n/numericalunits/numericalunits-1.17-py2.py3-none-any.whl`, but the corresponding hash-based address still works: `https://pypi.python.org/packages/89/2a/950938408b4eb49649802e49646c37a7caa57364e54dc2d832a71923475d/numericalunits-1.17-py2.py3-none-any.whl`

**Comment by alhirzel** [comment]
I believe something about this interface recently became case-sensitive (noticed when packaging OMPython).
