### ISSUE TITLE
Unable to open my package's "releases" page

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#448]
Originally reported by: **Ian Zimmerman (Bitbucket: [nobrowser](https://bitbucket.org/nobrowser), GitHub: [nobrowser](https://github.com/nobrowser))**

----------------------------------------

Each time I try to go to my package's page via the following URL

https://pypi.python.org/pypi?%3Aaction=pkg_edit&name=tuxfeeder

(for example, simply by clicking on the link under "your packages"), I get the infuriatingly vague "Something went wrong" page.  I can get to the top-level package page via

https://pypi.python.org/pypi/tuxfeeder

but then, when I click on "releases", again I get an error.  What is going on?  How can I manage my package??

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/448

**Comment by ckauhaus** [comment]
Same problem here. 

I've tried to open "releases" for [fc.agent](https://pypi.python.org/pypi?:action=pkg_edit&name=fc.agent) or [backy](https://pypi.python.org/pypi/backy/2.1.5) - the browser is waiting for quite a time, then I get this "Something went wrong" page.

*Sometimes* it is just working (albeit slow).

**Comment by ewdurbin** [comment]
resolved by asyncing a slow process that was being invoked. some things just get slower with time i suppose.

See: https://github.com/pypa/pypi-legacy/commit/1682ee7376cb1500addbc0ce11f93cbe17c70d68
