### ISSUE TITLE
Installation fails with --target option on centos7

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#449]
Originally reported by: **chandu-atina (Bitbucket: [chandu-atina](https://bitbucket.org/chandu-atina), GitHub: [chandu-atina](https://github.com/chandu-atina))**

----------------------------------------

I tried to install mysql-python==1.2.5 on centos7 using --target option with the following command and it failed.

$pip install --target=/var/tmp/ mysql-python==1.2.5

The issue is that the files are downloaded into "/tmp/{random_string}/lib64/python" but pip checks the files in "/tmp/{random_string}/lib/python" and throws no such file error

OS : CentOS7 (Docker Container)
Python version: 
         [root@ip-1]# python       
         Python 2.7.5 (default, Nov 20 2015, 02:00:19) 
         [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
         Type "help", "copyright", "credits" or "license" for more information.
          >>> exit()
pip --version
         pip 7.1.0 from /usr/lib/python2.7/site-packages (python 2.7)

Note : pip install myql-python==1.2.5 successfully installs the file.

Regards,
Chandu 

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/449

**Comment by berkerpeksag** [comment]
Thanks for the report, but this is not a problem in PyPI. I'd say it's a problem in both distutils and pip. There is also an open pull request against pip at https://github.com/pypa/pip/pull/3730.
