### ISSUE TITLE
Universal wheel says 2.7 in Python version field

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#450]
Originally reported by: **randomdude999 (Bitbucket: [randomdude999](https://bitbucket.org/randomdude999), GitHub: [randomdude999](https://github.com/randomdude999))**
---

I have a project that is both Python 2 and Python 3 compatible. In the "Downloads" section of the project, I have a single universal wheel and a source distribution. Even though the filename of the wheel is `rule_n-0.1-py2.py3-none-any.whl`, the Py version still says 2.7.

I tried deleting the file and reuploading but now PyPI says that the filename has been used and I need to use a different filename and the project doesn't have a wheel anymore.

Package: rule_n <https://pypi.python.org/pypi/rule_n>
---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/450

**Comment by mjpieters** [comment]
That specific value is set by the tool doing the uploading; it is the `pyversion` column in the database, and it is taken unparsed and unchanged from the data sent to the `file_upload` call.

So if this is a bug, it is a bug in the tool that does the uploading.

**Comment by mjpieters** [comment]
Ah, this is a bug in [`bdist_wheel`](https://bitbucket.org/pypa/wheel/src/54ddbcc9cec25e1f4d111a142b8bfaa163130a61/wheel/bdist_wheel.py?at=default&fileviewer=file-view-default#bdist_wheel.py-250); it uses `distutils.sysconfig.get_python_version()` to set that field (so using the Python version that built the wheel, not the Python version for which the wheel is valid).

**Comment by berkerpeksag** [comment]
@mjpieters thanks for triaging this! Closing this since it needs to be fixed in `bdist_wheel`. You can probably use an alternative tool like `twine` as a workaround (not tested)

**Comment by mjpieters** [comment]
Yes, twine sets `pyversion` to `py2.py3` for universal builds.
