### ISSUE TITLE
Unable to register package that doesn't have a page on pypi

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#456]
Originally reported by: **Peter Inglesby (Bitbucket: [inglesp](https://bitbucket.org/inglesp), GitHub: [inglesp](https://github.com/inglesp))**

----------------------------------------

https://pypi.python.org/pypi/spider/ returns a 404, but I am unable to register a package called "spider".

Here's some of the output from `python setup.py register`:

```
Registering spider to https://pypi.python.org/pypi
Server response (403): You are not allowed to store 'spider' package information
```

https://pypi.io/project/spider/ also returns a 404.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/456

**Comment by berkerpeksag** [comment]
That means that the package name *spider* has already been taken by someone else, but no release has uploaded yet. Perhaps this can be improved in Warehouse. Could you create a new issue at https://github.com/pypa/warehouse ?

**Comment by inglesp** [comment]
Thanks for looking at this @berkerpeksag.
