### ISSUE TITLE
Wishing to reclaim abandoned, code-free project named "tada"

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#458]
Originally reported by: **TomRitchford (Bitbucket: [TomRitchford](https://bitbucket.org/TomRitchford), GitHub: Unknown)**

----------------------------------------

Good day, and sorry to bother you!

We have a project called "tada" - Time Arts Data. https://github.com/rec/tada  

It offers today extremely fast and powerful DSP color arithmetic using Cython, and soon fast DSP processing for other Time Arts Data, like audio, DMX, OSC and MIDI.

There's an existing "tada" project on PyPi https://pypi.python.org/pypi/tada/ but it seems to be abandoned - the link leads nowhere.  I was unable to install this package under either Python 2 or Python 3.  I searched for the code in the usual places but didn't find it!

I sent a letter to the maintainer from the contact form on the site a week ago but have heard nothing yet.  We're in no hurry, but figured that we might as well try to move forward with this!

Thanks in advance.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/458

**Comment by rec** [comment]
Thanks for doing this!  (And sorry for putting it on the wrong buglist).  

I understand you're a) busy and b) understandably might be reluctant to transfer.  Luckily, we don't need to launch until the autumn and that would even give us plenty of time for a name change if it came to that.  

Thanks in advance.

**Comment by rec** [comment]
We've run into another name conflict with our name, so I'd like to apologize and close this issue.  Sorry about that!   Hopefully our contribution later will be worth this time.
