### ISSUE TITLE
package "petrophysics" not in search results

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#468]
Originally reported by: **petrophysics (Bitbucket: [bit000user](https://bitbucket.org/bit000user), GitHub: Unknown)**

----------------------------------------

I can install the package https://pypi.python.org/pypi/petrophysics/ with "pip install petrophysics", but when I search for it I have got: "There were no matches." Please help with this issue.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/468

**Comment by kernc** [comment]
Duplicate of https://github.com/pypa/pypi-legacy/issues/397
