### ISSUE TITLE
pypi search results link to old version of package

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#470]
Originally reported by: **Jeremy McMillan (Bitbucket: [jeremymcm](https://bitbucket.org/jeremymcm), GitHub: Unknown)**

----------------------------------------

If I search for my package datasize using the pypi web UI search form with "data size" query the top weighted result is the (old) 0.1 version of the datasize package, which should be the latest (eg. 0.3) version available.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/470

**Comment by kernc** [comment]
Duplicate of https://github.com/pypa/pypi-legacy/issues/397
