### ISSUE TITLE
Insert or update on table "journals" violates foreign key constraint

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#48]
Originally reported by: **Mikołaj Siedlarek (Bitbucket: [msiedlarek](https://bitbucket.org/msiedlarek), GitHub: [msiedlarek](https://github.com/msiedlarek))**

----------------------------------------

Trying to delete my old account, after confirmation, I receive the following error message:

```
Error...

There's been a problem with your request

: insert or update on table "journals" violates foreign key constraint "journals_submitted_by_fkey" DETAIL: Key (submitted_by)=(deleted user) is not present in table "users".
```

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/48

**Comment by berkerpeksag** [comment]
I was able to delete my account without getting an error on https://testpypi.python.org/pypi
