### ISSUE TITLE
Taking over MySQL-python maintainer

### ISSUE THREAD

**Issue by methane** [pypa/pypi-legacy#483]
original issue here: https://sourceforge.net/p/pypi/support-requests/553/

[MySQL-Python](https://pypi.python.org/pypi/MySQL-python/) is famous MySQL driver for Python.
Unfortunately, it doesn't support Python 3 and development is stalled for long time.
I've made for of it, named [mysqlclient](https://pypi.python.org/pypi/mysqlclient).
It is drop-in replacement of MySQL-python. Import path of them are same.
It support Python 3 and have some improvements and bugfix.

Some people including me tried to contact to Andy, MySQL-python owner.
But we failed to get response from him.
Could you add me to MySQL-python admin?
My account name on PyPI is naoki.

**Comment by berkerpeksag** [comment]
You need to ping PyPI admins at https://sourceforge.net/p/pypi/support-requests/553/ This tracker is for issues with pypi.python.org source code. Your original issue was reported to the correct tracker.
