### ISSUE TITLE
Restore download statistics using BigQuery

### ISSUE THREAD

**Issue by mahmoud** [pypa/pypi-legacy#485]
My use case is that I'm teaching early-stage Python developers how to evaluate their library dependencies. One step of this is evaluating the degree of usage. The statistics on PyPI provided the clearest and fastest way to do this, but they've been permanently removed in favor of BigQuery (per discussion in #484).

Google BigQuery might be a great tool for advanced developers, but it's not really appropriate to get Pythonists looking to install their first libraries signed up with Google APIs and teach them BigQuery syntax. And the BigQuery database feels unofficial, even impermanent.

My enhancement request would be to make it clear that BigQuery is here to stay (if that is indeed the case) through documentation, and ideally restore traffic statistics based on the new datastore, at least until Warehouse is ready to go.

Traffic statistics was one of three really useful features the PyPI project pages had. At this point, legacy PyPI does not answer many questions, and Warehouse raises more questions than it answers (with all of the test/build/coverage "unknown" elements in the unfinished site).

**Comment by ewdurbin** [comment]
please either query BigQuery directly or use https://pypi.io for now. I'm sorry this won't be restored in pypi-legacy.

**Comment by mahmoud** [comment]
That's too bad. In that case, would you mind providing on this issue or #484 a bit of transparency into the mutual exclusivity of linehaul and legacy pypi statistics?
