### ISSUE TITLE
pypi does not prevent uploading of wheels using local version identifiers, despite PEP440's explicit disallowance

### ISSUE THREAD

**Issue by anntzer** [pypa/pypi-legacy#486]
pyzmq 15.3.0 (https://pypi.python.org/pypi/pyzmq/15.3.0) recently uploaded some wheels using a local version identifier (e.g., `pyzmq-15.3.0+fix-cp35-cp35m-win_amd64.whl`).  Note that PEP440 (https://www.python.org/dev/peps/pep-0440/#local-version-identifiers) explicitly disallows this:

> As the Python Package Index is intended solely for indexing and hosting upstream projects, it MUST NOT allow the use of local version identifiers.

(This breaks a tool I wrote that automatically converts PyPI packages into Arch Linux packages.)

**Comment by ewdurbin** [comment]
the version checking in legacy pypi is pretty simple/mundane. i came across @Carreau's https://github.com/Carreau/pep440 and would happily implement it in legacy PyPI if it were python 2.7 compatible.

@Carreau is that something you'd accept as a PR into the project?

**Comment by Carreau** [comment]
> @Carreau is that something you'd accept as a PR into the project?

No need to, version 0.0.3 released, with python-annotation stripped, and marked as python 2 compatible.  (haven't tested with 2.6 though, but seem to work with 2.7)

Note that the package is super small, and there is literally just 20 lines to vendorize.

**Comment by Carreau** [comment]
> Note that the package is super small, and there is literally just 20 lines to vendorize.

Note, I think  that pep440 should get an update with a canonical regex that match valid releases numbers.

**Comment by di** [comment]
All uploads are now done through pypi.org, which will not allow local version identifiers.
