### ISSUE TITLE
Cannot claim OpenID self-hosted via SimpleID

### ISSUE THREAD

**Issue by ssokolow** [pypa/pypi-legacy#487]
When I attempt to claim my OpenID, which I self-host via [SimpleID](http://simpleid.koinic.net/) 1.0, I receive the following error

```
Discovery failed. If you think this is in error, please submit a bug report.
```

This occurs whether or not I'm already logged into the OpenID provider and whether I use my usual http://ssokolow.com/ OpenID or the https://ssoid.nfshost.com/ URL it delegates to.

It works with all of the other OpenID-compatible sites I've tried.

**Comment by ssbarnea** [comment]
Same with me but only on testpypi. On the production server it happens that I already have a Google Open Id configured which seems to be working.

I tried to copy/paste this url from pypi to testpypi, hopping that this would also enable me to login to that server but surprise, it does not work.

**Comment by di** [comment]
Closing, [we are no longer supporting federated authentication](https://github.com/pypa/warehouse/issues/61).
