### ISSUE TITLE
bitcoinrpc is out of date and have bug

### ISSUE THREAD

**Issue by zabisky** [pypa/pypi-legacy#491]
python-bitcoinrpc (https://pypi.python.org/pypi/python-bitcoinrpc/0.3) package is out of date. It returns empty answer from rpc server and completely do not work. You can find information about it here: https://github.com/jgarzik/python-bitcoinrpc/issues/62 

The github version is fixed(https://github.com/jgarzik/python-bitcoinrpc), could you please update it in pypi repo?

**Comment by jamadden** [comment]
This project is for the development and maintenance of the PyPI server itself. It does not have any control over the projects posted there. If you have issues with a third party project, please discuss it with the maintainers of that project. It seems you already linked to such a discussion.

**Comment by zabisky** [comment]
Yea, wrong place to post, I am sorry

**Comment by berkerpeksag** [comment]
@jamadden is correct, please ask for a new release at https://github.com/jgarzik/python-bitcoinrpc/issues
