### ISSUE TITLE
"login with google" silently fails, no login occurs

### ISSUE THREAD

**Issue by smemsh** [pypa/pypi-legacy#492]
try to register with the site, it says if you want to use google, just use "login with google" instead of registering.  ok so do that...

"login with google" appears to work (select which google account, agree to the lookup), but just puts me on the same page again without having logged in (unchanged from appearance prior to login).  going to any other page, not logged in, shows the login link, login with google, etc just like it was never done.

after login the url looks like: `https://pypi.python.org/pypi`
with these parameters (sanitized):
- `action=openid_return`
- `state=<obfuscated>`
- `code=<obfuscated>`
- `authuser=1`
- `hd=<my_google_auth_domain>`
- `session_state=<obfuscated>`
- `prompt=none#`

may be related to #113, #215, #240, could not tell if duplicate (those appeared to have errors, mine shows no error, just doesn't work)

**Comment by ewdurbin** [comment]
have you previously logged in with google?

**Comment by unixnut** [comment]
Nope

**Comment by michalnik** [comment]
I have the same problem. Click on the "https://pypi.python.org/google_login" and no result there. Is it temporarily out of order?

**Comment by michalnik** [comment]
https://developers.google.com/identity/protocols/OpenID2Migration
Is it a problem with protocol which were changed at the start of the year?

**Comment by zerothi** [comment]
I have the same problem... For several months now!

:+1:

**Comment by davidhrbac** [comment]
The very same here....

**Comment by alisonken1** [comment]
Deleted my old account - reset google authorizations for pypi - but trying to use google login just returns me to the login page without logging in.

**Comment by AlassaneNdiaye** [comment]
The same thing happened to me. Is there a fix yet?

**Comment by ewdurbin** [comment]
We do not support new account creation via Google, or associations with existing accounts. Only previously associated accounts can be used with when logging in with google.

**Comment by zerothi** [comment]
Could you then please notify that the login has failed due to non-support?

**Comment by ewdurbin** [comment]
@zerothi sure thing: https://github.com/pypa/pypi-legacy/commit/b84dbd09a993ed34fbac4816be4dc9a46cddded9
