### ISSUE TITLE
Upload failed (413): Request Entity Tool Large // package size~2MB

### ISSUE THREAD

**Issue by radjkarl** [pypa/pypi-legacy#498]
Hi there,

I currently cannot update some of my packages [e.g. https://pypi.python.org/pypi?:action=display&name=imgProcessor&version=0.2.4]
It looks like, there is a file size limit of about 2MB.

Can you confirm that?

server: https://www.python.org/pypi
command: python setup.py bdist_wheel upload -r pypi

**Comment by ewdurbin** [comment]
We currently limit the upload size to 100MB at the nginx layer and 60MB within PyPI itself.

If you can provide steps to reproduce I'll investigate what is limiting your upload size.

**Comment by ewdurbin** [comment]
@radjkarl it appears the issue is trying to use `https://www.python.org/pypi` as your server. that isn't pypi as it turns out.

you need to use `https://pypi.python.org/pypi` as the previously indicated URL is just a redirect.

**Comment by radjkarl** [comment]
@ewdurbin: changing the address to https://pypi.python.org/pypi did the trick!
thank you so much!
