### ISSUE TITLE
[Request] Package documentation link(s)

### ISSUE THREAD

**Issue by stantond** [pypa/pypi-legacy#501]
I'm following up [this issue on ReadTheDocs about browsing docs offline with 3rd party apps](https://github.com/rtfd/readthedocs.org/issues/662) - it looks like no one asked anyone here for help, but the issue is still outstanding.

There's currently no way to map from here to documentation in a format other applications can use. Details of why this would be useful are in the above ticket, but essentially there are examples of documentation names being different to the package names.

`pypi-legacy` accepts three URLs from a user, `Home page`, `Download URL` and `Bugtrack url`. `warehouse` only takes `url`, meant for the homepage.

Is there room for optional documentation URLs (plural as docs may be in multiple places and a user can choose which they prefer)?

[Also on warehouse here](https://github.com/pypa/warehouse/issues/1419), as if this makes it in, it should of course be in the `warehouse`.

**Comment by ewdurbin** [comment]
@stantond i think this is an excellent idea, but we'll need to implement it in warehouse first since it owns the database schema now. (they're sharing).

if you want to champion or implement this on the warehouse side, I'd encourage that. once implemented we can expose the field for edit/view within pypi-legacy easily.

**Comment by di** [comment]
This is now possible with the [`Project-URL`](https://packaging.python.org/specifications/core-metadata/#project-url-multiple-use) metadata field, [see an example here](https://github.com/pypa/sampleproject/blob/master/setup.py#L181-L195).
