### ISSUE TITLE
The test site should be able to upload the same package.

### ISSUE THREAD

**Issue by cnobile2012** [pypa/pypi-legacy#502]
No being able to upload the same package on the test site makes iterating fixes very difficult. It also causes versions between the test site and production PyPi site to be different.

Please fix this.

**Comment by ewdurbin** [comment]
@cnobile2012 as PyPI and TestPyPI use identical codebase and logic, this is infeasible at this point in time. please weigh in on https://github.com/pypa/warehouse/issues/918 with any thoughts for how this can be improved once pypi-legacy is superseded by warehouse.
