### ISSUE TITLE
Move ownership of 'domaintools' package to timothycrosley

### ISSUE THREAD

**Issue by timothycrosley** [pypa/pypi-legacy#503]
- We do not maintain individual packages installed from PyPI, please seek out the maintainer
Hi!

I read and took note of this, however the maintainer of https://pypi.python.org/pypi/domaintools/0.3.7 has not responded to my inquiries over an extended period of time and the package is currently not operational or serving any purpose. I would like to gain control of this package in order to make it a usable pip installable package, as is currently not the case.

Thank you!

~Timothy Crosley

**Comment by berkerpeksag** [comment]
Thanks for the report! We do have a separate tracker for queries like this: https://sourceforge.net/p/pypi/support-requests/

I will send a PR to mention about https://sourceforge.net/p/pypi/support-requests/ this week.
