### ISSUE TITLE
Request for new trove classifier for Plone 5.1

### ISSUE THREAD

**Issue by mauritsvanrees** [pypa/pypi-legacy#504]
We have a first alpha release for Plone: https://pypi.python.org/pypi/Products.CMFPlone/5.1a1
So on behalf of the Plone Release Team: can we have this new classifier?

`Framework :: Plone :: 5.1`

Thanks!

**Comment by ewdurbin** [comment]
@mauritsvanrees will do, i'll confirm here when we're all set.

**Comment by ewdurbin** [comment]
@mauritsvanrees Complete.

**Comment by mauritsvanrees** [comment]
And I have released the first package with this classifier: https://pypi.python.org/pypi/plone.namedfile/4.0

Thanks for the quick help!
