### ISSUE TITLE
units 0.06 - Integer division causes silent error

### ISSUE THREAD

**Issue by mfa5147** [pypa/pypi-legacy#507]
Using the invert() method of a unit multiple that was initialized with an integer multiplier greater than one erroneously returns a unit with a multiplier of zero due to integer division. I am using Python 2.7.11 on 64-bit Ubuntu 16.04 LTS. The code below shows that inverting the kilometer, a unit that comes predefined with the package, causes this error.

`>>> from units import unit`
`>>> from units.predefined import define_units`
`>>> define_units()  # define common units, such as the kilometer (km)`
`>>> # These next lines show that km has been defined as a ComposedUnit equal`
`>>> # to 1000 times the LeafUnit "m", which represents a meter. Note that 1000`
`>>> # is an int, not a float.`
`>>> km = unit("km")`
`>>> km`
`NamedComposedUnit('km', ComposedUnit([LeafUnit('m', True)], [], 1000), False)`
`>>> # An inverse km equals 0.001 m^-1, but the invert method returns 0 m^-1.`
`>>> km.invert()`
`ComposedUnit([], [LeafUnit('m', True)], 0)`
`>>> # Dividing a kilometer by a meter returns 1000, as it should.`
`>>> m = unit("m")`
`>>> km / m`
`1000`
`>>> # But the multipler of the unit returned from a m / km is 0, not 0.001.`
`>>> m / km`
`ComposedUnit([LeafUnit('m', True)], [LeafUnit('m', True)], 0)`

This error can be corrected by changing the line within the invert method of the ComposedUnit class in units/composed_unit.py from
`return ComposedUnit(self.denom, self.numer, 1 / self.squeeze())`
to
`return ComposedUnit(self.denom, self.numer, 1.0 / self.squeeze())`
to force floating-point division.

**Comment by berkerpeksag** [comment]
Thanks for the report! Unfortunately, this tracker is for issues with pypi.python.org. units is a separate project developed by someone else. unit's source code is hosted at https://bitbucket.org/adonohue/units but I couldn't find an issue tracker so you may want to contact its author.
