### ISSUE TITLE
Deterministic source download links not working?

### ISSUE THREAD

**Issue by madscientist** [pypa/pypi-legacy#509]
In the past we've been able to download source to packages from pypi using a deterministic URL pattern, https://pypi.python.org/packages/source/<L>/<PKG>/<FILE> where <L> is the first letter of the package name, <PKG> is the package name, and <FILE> is the complete filename of the source tarball or zip file.

There are even links embedded in package documentation (such as the psutil "Timeline" section).

However, attempting to wget these URLs currently results in a 404.

This is not good for me, since I rely on these deterministic source URLs in an embedded build system (which can't use pip etc.)  Any hope of reconstituting this capability?

**Comment by dstufft** [comment]
Use ``https://files.pythonhosted.org/packages/source/...``.

**Comment by madscientist** [comment]
That worked, thanks!
