### ISSUE TITLE
Fix and/or bump jupyter-1.0.0: Upstream moved file jupyter.py

### ISSUE THREAD

**Issue by holgersson32644** [pypa/pypi-legacy#514]
Hello everyone,
I’m running into a conflict with _jupyter_ and _jupyter_core_ installed via my distribution’s package manager**[1]**,
because upstream moved the location**[2]** of **jupyter.py** from _jupyter_ to _jupyter_core_, and while _jupyter_core_ is fetched somewhere from upstream (and updated now), _jupyter_ via pypi.python.org has the old structure.

So please update _jupyter_ as soon as possible! :-)

**[1]** Gentoo/Linux bugtracker thread: https://bugs.gentoo.org/show_bug.cgi?id=589750
**[2]** Upstream thread: https://github.com/jupyter/jupyter_core/issues/55

**Comment by jamadden** [comment]
This tracker is for managing issues with the software that runs PyPI itself. It has nothing to do with the packages that are distributed on PyPI. Please report this issue to the maintainers of jupyter (it seems like you've already found their issue tracker).

**Comment by holgersson32644** [comment]
Thanks and sorry for spamming your tracker then! I’m closing this bug here.
