### ISSUE TITLE
Package now showing up in search

### ISSUE THREAD

**Issue by Idolf** [pypa/pypi-legacy#517]
When I [search for pwntools](https://pypi.python.org/pypi?%3Aaction=search&term=pwntools&submit=search), I get no results, even though there are two active versions of pwntools:

- https://pypi.python.org/pypi/pwntools/3.0.1
- https://pypi.python.org/pypi/pwntools/3.1.0b0

This did not use to be the case, and as far as I know, we did not change anything with regards to how to upload our packages. Are we doing something wrong or is this a bug?

**Comment by Idolf** [comment]
We just did a new release. Now a single entry shows up -- the second-newest pre-release.

Would it be possible to always show both the newest release and the newest pre-release?

**Comment by zachriggle** [comment]
That it shows the latest non-hidden version is, I expect, perfectly normal behavior.

**Comment by zachriggle** [comment]
We are now not showing again, at all, in search
