### ISSUE TITLE
Problems in RPi.GPIO file "py_gpio.c" file: causes failure to install/update in VS 2015 using Python

### ISSUE THREAD

**Issue by mystic12** [pypa/pypi-legacy#518]
I am working on the Raspberry Pi 3 ("PI 3") to create a new motion control "hat".  I decided to try cross compile a simple program that I tested and ran on the Pi 3 on VS 2015 running Python.  The code debugged correctly on VS 2015, except that there was a general exception for this statement: "import RPi.GPIO as GPIO".  See attached screen print.

I updated the PIP installer on VS 2015 to "pip 8.1.2" and then tried to install RPi.GPIO from the Python webpage for GPIO which has this download: "RPi.GPIO-0.6.2.tar.gz".  The install failed (see attached output file from VS 2015) because the C++ source file "py_gpio.c" has several bugs.  (as shown in the attached output file).  I am not skilled enough in C to be certain of fixing this correctly, so I am reporting this bug.

Hopefully, someone capable will get this fixed soon.

Thank you!
pdwyer@fidelityhorns.com
PS: I am new to Python and to github, so it may be best to copy me at my email.

[Output from trying to Install RPi.GPIO in VS 2015.txt](https://github.com/pypa/pypi-legacy/files/465763/Output.from.trying.to.Install.RPi.GPIO.in.VS.2015.txt)
![screenshot 17](https://cloud.githubusercontent.com/assets/14785915/18415197/42fff01a-779e-11e6-8aab-d12c581e9021.png)

**Comment by jamadden** [comment]
Thank you for your report,  but this issue tracker is for the software that runs PyPI itself. It has nothing to do with the packages that are distributed via PyPI or any other website. Issues you encounter with such packages need to be reported to their maintainers (presumably the raspberry pi folks, in this case, but that's just a guess, check the package docs for more details).
