### ISSUE TITLE
Maintainer contact information not visible on the package page

### ISSUE THREAD

**Issue by ganeshsatpute** [pypa/pypi-legacy#525]
I'm facing one issue while installing `prioritized_methods`. On their [page](https://pypi.python.org/pypi/prioritized_methods) on _PyPi_ , I don't find any contact information. Shouldn't be this present on the page itself?

**Comment by Carreau** [comment]
Hi @ganeshsatpute 

I'm not a maintainer here, but the contact info appear on PyPI only if the author set them explicitely to be show. 

They are in the TGZ though I found the following: 

```
Author: Alberto Valverde Gonzalez
Author-email: alberto(at)toscat.net
```

I would suggest contact them directly. Hope that helps.

**Comment by berkerpeksag** [comment]
Matthias is right. There is nothing we can do here. I'd suggest sending an email to the email address that Matthias shared above.

Thanks!
