### ISSUE TITLE
IPv6 status button in footer has an empty url

### ISSUE THREAD

**Issue by thomwiggers** [pypa/pypi-legacy#526]
There are two images in the footer of pypi.python.org:

https://github.com/pypa/pypi-legacy/blob/54a9b3e1ed078ce9bcd6f2ac79720d58a1beb0d7/templates/standard_template.pt#L213-L214

These have `href=''`. This leads to them being able to be followed, but they go nowhere. Perhaps remove the `<a>` tag?

**Comment by berkerpeksag** [comment]
Thanks for the report. Links were removed in https://github.com/pypa/pypi-legacy/commit/203f3325fff6c9f765ece71dad945993c224fd23. I've opened https://github.com/pypa/pypi-legacy/pull/534 to remove empty `<a>` tags.
