### ISSUE TITLE
Address boundary error when trying to use Image.putdata(array)

### ISSUE THREAD

**Issue by TriRpi** [pypa/pypi-legacy#528]
Got a signal boundary error.

Steps to reproduce:
open python console

    Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
    [GCC 4.9.2] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from PIL import Image
    >>> im = Image.open('HKJL.jpg')
    >>> import numpy as np
    >>> arr = np.array(im)
    >>> arr[arr < 10] = 0
    >>> im.putdata(arr)
    fish: “python” terminated by signal SIGSEGV (Address boundary error)

[The image I used.](http://i.imgur.com/hnuzhFj.jpg)

**Comment by berkerpeksag** [comment]
Thanks for the report, but the correct place to ask questions like this is [python-list](https://mail.python.org/mailman/listinfo/python-list). This tracker is for issues with pypi.python.org.
