### ISSUE TITLE
JPype entry contains no packages

### ISSUE THREAD

**Issue by seidenberg** [pypa/pypi-legacy#530]
Trying to fetch JPype from the repository, I found that its entry in the repository at https://pypi.python.org/simple/jpype/ is empty.

I hope to be posting this at the adequate place. Thanks for your great work, I appreciate it a lot!

Best,
Ephraim

**Comment by jamadden** [comment]
The [PyPI entry for JPype](https://pypi.python.org/pypi/JPype) is just a placeholder to reserve the name. You'll need to manually follow the link to the JPype homepage to find out how to download and install JPype.
