### ISSUE TITLE
pyserial won't install on my windows 10 (64 bit) machine says no python in registry

### ISSUE THREAD

**Issue by flagtrax** [pypa/pypi-legacy#532]
Before opening an issue for PyPI, please note the following:
  - This is for the codebase currently running pypi.python.org
  - [Warehouse](https://github.com/pypa/warehouse) is soon to replace this codebase. Some issues may be deferred to the issue tracker for [Warehouse](https://github.com/pypa/warehouse/issues) rather than be addressed here.
  - We do not maintain individual packages installed from PyPI, please seek out the maintainer

**Comment by berkerpeksag** [comment]
Please report your problem to pyserial developers: https://github.com/pyserial/pyserial/issues
