### ISSUE TITLE
Incorrect 'Home Page' entry for pytest-autochecklog on https://github.com/steven004/pytest-autochecklog

### ISSUE THREAD

**Issue by sharad1087** [pypa/pypi-legacy#533]
The 'Home Page' for pytest-autochecklog is listed incorrectly at:
https://github.com/steven004/pytest-autochecklog

Current entry:
Home Page: https://github.com/steven004/python-autochecklog

Correct entry:
Home Page: https://github.com/steven004/pytest-autochecklog

**Comment by berkerpeksag** [comment]
Thanks for the report, but please a file a new issue at https://github.com/steven004/pytest-autochecklog/issues PyPI uses the data provided by the projects's `setup.py`.
