### ISSUE TITLE
Not possible to view package  PyQt5

### ISSUE THREAD

**Issue by edi9999** [pypa/pypi-legacy#537]
If I run 

```
pip3 -vvv show PyQt5
```

It shows nothing and returns with exit code 1

If I run 

```
pip3 -vvv show requests
```

I get : 

```

---
Metadata-Version: 2.0
Name: requests
Version: 2.11.1
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
Installer: pip
License: Apache 2.0
Location: /home/edgar/.local/lib/python2.7/site-packages
Requires:
Classifiers:
  Development Status :: 5 - Production/Stable
  Intended Audience :: Developers
  Natural Language :: English
  License :: OSI Approved :: Apache Software License
  Programming Language :: Python
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Programming Language :: Python :: Implementation :: CPython
  Programming Language :: Python :: Implementation :: PyPy
```

Both have their page on pypi : https://pypi.python.org/pypi/PyQt5 and https://pypi.python.org/pypi/requests, so I don't understand why the show command doesn't work for PyQt5.

The install command doesn't work either, the package is "not found"

**Comment by edi9999** [comment]
From the docs of pyqt5 : 

> If you get an error message saying that no downloads could be found that satisfy the requirement then you are probably using an unsupported version

http://pyqt.sourceforge.net/Docs/PyQt5/installation.html

So this seems to be the reason of my issue.

However, I think it is still a bad thing not to show the user what is happenning, especially when using the -vvv flag.

**Comment by ewdurbin** [comment]
please file this issue with https://github.com/pypa/pip regarding lack of verbosity.
