### ISSUE TITLE
requests send https request by apache-proxy may don't work

### ISSUE THREAD

**Issue by lirenke** [pypa/pypi-legacy#539]
python 2.7.5+ httpd 2.4.6 + requests 2.10.0

Send a http request with setting http_proxy environment-variable, the request will go to httpd server first.
But, we found apache server ouput ""\x16\x03\x01" 400 226 "-" "-"" , and client fail.

Reason is that the request don't have tunnel info including tunnel_host and tunnel_port.
I think we should add _prepare_proxy method after _get_conn in HTTPAdapter().send method.

**Comment by berkerpeksag** [comment]
Thanks for the report, but the more appropriate place to report this is https://github.com/kennethreitz/requests/issues. This tracker is for issues with pypi.python.org only.
