### ISSUE TITLE
pypi server is spammed:

### ISSUE THREAD

**Issue by jenisys** [pypa/pypi-legacy#540]
SCOPE: official pypi server (not an issue related to pypi codebase)

The official pypi server seems currently to be spammed with ``BAD package entries``, like:

* 1-8OO-681-7208_Outlook_Mail_Customer_Support_Phone_Number 440
* QuickBooks_POS_Technical_Support_Telephone_Number 423
* 1-8OO-...    (with letter O instead of digit 0 (zero))
* 1-844-...
* I8OO...

PACKAGE NAME SCHEMES:
* U.S. telephone like names containing misspelled letters (O (like Oscar) instead of digit 0 (zero)).
* 1-8...

The registered packages do not provide any files for downloads (at least I have not seen any).

**Comment by ewdurbin** [comment]
@jenisys thank you for the report! we'll be tracking progress on this cleanup here.

**Comment by ewdurbin** [comment]
see: https://status.python.org/incidents/ry2q26575x75

**Comment by jenisys** [comment]
Seems to start again. At least one entry was added today (with very long description):

* QuickBooks_technical_Support_Number_1844_307_0998_QuickBooks_customer_Support_Number 0.1

**Comment by ewdurbin** [comment]
thanks again @jenisys we're continuing to attempt to mitigate.
