### ISSUE TITLE
Rounding malfunction

### ISSUE THREAD

**Issue by mfpqltm** [pypa/pypi-legacy#543]
Python 3.5.1
print("%7.1f" % 123.25)
print("%7.1f" % 123.45)

Python 3.5.2
print("%7.1f" % 123.25)

The statements are not rounded

**Comment by jamadden** [comment]
Thank you for your report. Unfortunately, this is the wrong place for it.

This repository is for the server software that runs http://pypi.python.org, *not* the Python language itself. To report a bug in Python itself, follow [the instructions](https://docs.python.org/3.6/bugs.html) provided.
