### ISSUE TITLE
"Add Package Info" fails

### ISSUE THREAD

**Issue by jakirkham** [pypa/pypi-legacy#545]
When trying to submit a package via the web interface using the "Add Package Info" to manually edit the entry, it fails claiming the `name` is missing. However, no such entry option was ever provided. Tried with Firefox 49.0.2 and Safari 9.1.3. Relevant screenshots below.

<img width="1554" alt="screen shot 2016-10-28 at 12 07 08" src="https://cloud.githubusercontent.com/assets/3019665/19813351/569ae718-9d07-11e6-8a70-4ae1f5c046fd.png">

<img width="1554" alt="screen shot 2016-10-28 at 12 07 20" src="https://cloud.githubusercontent.com/assets/3019665/19813334/3f9dc1f2-9d07-11e6-84da-12146b4284ad.png">

**Comment by ewdurbin** [comment]
this looks to be a byproduct of some changes made to thwart spammers, i'll look into it and get a fix out over the next few days.

**Comment by ewdurbin** [comment]
this error message appears to be errant, @jakirkham. I've confirmed that the PKG-INFO upload does work for _valid_ PKG-INFO files. upon removing the `name` key, I received the same error... which is misleading.

please double check that your PKG-INFO file is valid.

**Comment by rjk40** [comment]
[apache24_manual-2.4.23,REV=2016.10.15-SunOS5.10-all-CSW.pkg.gz](https://github.com/pypa/pypi-legacy/files/629838/apache24_manual-2.4.23.REV.2016.10.15-SunOS5.10-all-CSW.pkg.gz)

**Comment by jakirkham** [comment]
However I would like to add the package name to PyPI before I have a package to upload. The purpose being to reserve a spot while I work on the package. What is the recommended way of doing this if not adding the package name via the browser?
