### ISSUE TITLE
sphinxcontrib-programoutput has gone missing

### ISSUE THREAD

**Issue by mindw** [pypa/pypi-legacy#546]
It was there on a day before (2016/10/30).

Was it deleted?

My apologies if this is not the right place for this.

**Comment by Carreau** [comment]
Hi @mindw, 

I'm not a maintainer here, but https://pypi.python.org/pypi/sphinxcontrib-programoutput works for me and show a version 0.8 uploaded today : 2016-11-01  for Python 2.7 and 35. as wheel.

Can you retry ?

**Comment by jamadden** [comment]
sphinxcontrib-programoutput was deleted by its original maintainer. A new maintainer then stepped in and uploaded a wheel. Slightly later, it was transferred to [another maintainer](https://github.com/NextThought/sphinxcontrib-programoutput) who has produced new releases and is uploading both wheels and sdists.
