### ISSUE TITLE
Missing OSI-approved license classifier

### ISSUE THREAD

**Issue by jodoglevy** [pypa/pypi-legacy#548]
I have a package I'd like to add to PyPI that is dual-licensed under Apache 2.0 and UPL 1.0. However, it doesn't look like there is a valid classifier for UPL on PyPI right now, from looking at [this list](https://pypi.python.org/pypi?%3Aaction=list_classifiers).

Can a classifier for UPL be added? My suggestion would be:
`License :: OSI Approved :: Universal Permissive License (UPL)`

**Comment by ewdurbin** [comment]
Confirmed OSI Approved,

Added:
  - `License :: OSI Approved :: Universal Permissive License (UPL)`
