### ISSUE TITLE
No option to create new directory available in robotframework-ride 1.5.2.1

### ISSUE THREAD

**Issue by ashraf75** [pypa/pypi-legacy#549]
Before opening an issue for PyPI, please note the following:
  - This is for the codebase currently running pypi.python.org
  - [Warehouse](https://github.com/pypa/warehouse) is soon to replace this codebase. Some issues may be deferred to the issue tracker for [Warehouse](https://github.com/pypa/warehouse/issues) rather than be addressed here.
  - We do not maintain individual packages installed from PyPI, please seek out the maintainer

**Comment by Carreau** [comment]
Hi there,

As indicated on the text of the issue that you apparently missed:

 - This is the issue tracker for PyPI, 
 - The maintainer of this repo do not maintain individual packages installed from PyPI, please seek out the maintainer

So if you have issue with robotframework-ride please open issue on [their issue tracker](https://github.com/robotframework/RIDE/). 

Thanks. 

@ewdurbin or @dstufft, would you be willing to click the close button for this issue.
