### ISSUE TITLE
"Framework :: Django :: 1.10" trove classifier is missing on testpypi

### ISSUE THREAD

**Issue by twidi** [pypa/pypi-legacy#550]
The trove classifier for the last Django version, `Framework :: Django :: 1.10` is present on pypi.python.org, but not on testpypi.python.org

**Comment by Flimm** [comment]
I can confirm that this is still an issue.

**Comment by Flimm** [comment]
In addition, we need `Framework :: Django :: 1.11` on both pypi.python.org and on testpypi.python.org now.

**Comment by urda** [comment]
Yeah, it would be nice to have this added for us that are updating our packages since the release of `1.11` !

**Comment by urda** [comment]
It's probably best to not mix the two together, so I opened an issue for `1.11`: #624

**Comment by ewdurbin** [comment]
resolved! working on some other trove classifiers as well.
