### ISSUE TITLE
Can't recover account: Old email address

### ISSUE THREAD

**Issue by BobBall** [pypa/pypi-legacy#553]
Ewan Mellor (https://www.linkedin.com/in/ewanmellor, https://sourceforge.net/u/ewanmellor/profile/) is the owner of the XenAPI package (https://pypi.python.org/pypi/XenAPI), registered with a Citrix email address (ewan.mellor at citrix.com).
Unfortunately Ewan is no longer at Citrix, and no longer has access to this account: https://sourceforge.net/p/pypi/support-requests/682/.

Could the account be updated to connect to ewan at ewanmellor.org (please do reach out to Ewan to get any required confirmation) or the XenAPI pypi package be updated to me (gnomeking / bob.ball at citrix.com) so we can add appropriate package owners to ensure Citrix does not accidentally lose ownership in future.

Thanks!

**Comment by mseri** [comment]
This would be very useful. We have new version and upcoming support for python 3 that would bring a very welcome update

**Comment by di** [comment]
@ewanmellor, could email me at `di@python.org` from a new email address for your account?

**Comment by di** [comment]
I've updated Ewan's email address, so it should be possible to transfer this package now.
