### ISSUE TITLE
not working on rapsbian jessie linux kernel 

### ISSUE THREAD

**Issue by doubleh2** [pypa/pypi-legacy#554]
python scripts from pub nub import Pubnub throws error "no module named pub nub"

scripts work with 3.90 and earlier

**Comment by Carreau** [comment]
Hi @doubleh2, this is the repository for PyPI itself, which host packages, not for pubnub.

From what you are saying, I would suggest asking directly on the pubnub issue tracker, which for Python is likely [this one](https://github.com/pubnub/python). 

Thanks.
