### ISSUE TITLE
Can't re-send confirmation email

### ISSUE THREAD

**Issue by kevinior** [pypa/pypi-legacy#557]
I registered at https://pypi.python.org yesterday but never received the confirmation email.

Checking my mail server logs it seems that the server you were sending from was (temporarily) blacklisted:

    Nov 21 16:10:22 vosill postfix/smtpd[11671]: NOQUEUE: reject: RCPT from rs236.mailgun.us[209.61.151.236]: 554 5.7.1 Service unavailable; Client host [209.61.151.236] blocked using bl.spamcop.net; Blocked - see http://www.spamcop.net/bl.shtml?209.61.151.236; from=<bounce+81246c.6f242-kevin-pypi=caboose.org.uk@mail.pypi.python.org> to=<kevin-pypi@caboose.org.uk> proto=ESMTP helo=<rs236.mailgun.us>

There doesn't seem to be any easy way of requesting that the confirmation email be re-sent. I've tried updating the address to a different one but that didn't seem to cause a new confirmation email to be sent.

**Comment by ewdurbin** [comment]
@kevinior requesting a password reset should resend. please let me know if that doesn't work.

**Comment by kevinior** [comment]
@ewdurbin Thanks, that worked fine.
