### ISSUE TITLE
Dash-to-underscore auto-correction in pkg name does not work in main search

### ISSUE THREAD

**Issue by knaperek** [pypa/pypi-legacy#559]
This in turn causes PyPI search to return empty results for packages that are "misspelled" but can generally be referred to by those "misspelled" names - pip install is robust enough and also accessing the package detail page directly by putting the misspelled name into URL automatically performs redirection to the correct URL.

For example, try to search for this package on the PyPI index page:
`backports-abc`
You get no results. But try accessing https://pypi.python.org/pypi/backports-abc directly and you'll be redirected instantly. Also, installing with `pip install backports-abc` works.

**Comment by ewdurbin** [comment]
@knaperek thank you for the report.

currently the search powering PyPI is relatively.... hrm... _simple_. i'll take a look and see if the dash/underscore handling can be addressed. it appears that search in next-gen PyPI/warehouse does [handle this appropriately](https://pypi.org/search/?q=backports-abc), so unless there is a simple fix for legacy PyPI, this may not be resolved in this codebase.

**Comment by knaperek** [comment]
Thanks @ewdurbin. For what it's worth, I have a feeling this was working a couple of months ago, but I wouldn't bet on it...

**Comment by knaperek** [comment]
Just tried searching for `django-import-export` now. No results. But the package name is obviously correct.

**Comment by ewdurbin** [comment]
this ultimately is boiling down to a fight between standardization on `-` for normalized package names and the fact that the tokenizer used for search in elastic search splitting off the search term into multiple terms:

```
$ curl -s "localhost:9200/_analyze?text=backports-abc" | python -m json.tool
{
    "tokens": [
        {
            "end_offset": 9, 
            "position": 1, 
            "start_offset": 0, 
            "token": "backports", 
            "type": "<ALPHANUM>"
        }, 
        {
            "end_offset": 13, 
            "position": 2, 
            "start_offset": 10, 
            "token": "abc", 
            "type": "<ALPHANUM>"
        }
    ]
}
```

vs

```
$ curl -s "localhost:9200/_analyze?text=backports_abc" | python -m json.tool
{
    "tokens": [
        {
            "end_offset": 13, 
            "position": 1, 
            "start_offset": 0, 
            "token": "backports_abc", 
            "type": "<ALPHANUM>"
        }
    ]
}
```

unfortunately modifying the analyzer/tokenizer would indeed make exact matching on name much better, but would render more general searches nearly useless.

i'm going to look a little deeper, but am at a bit of an impasse on this issue currently.

**Comment by viktor-ferenczi** [comment]
This issue affects my package as well: [https://pypi.python.org/pypi/genshi_compiler/](https://pypi.python.org/pypi/genshi_compiler/)

It cannot be found on package search as "genshi-compiler".

Searching for "genshi compiler" works, however.

Trying to fix the package name in the PKG-INFO (from genshi_compiler to genshi-compiler) and uploading it again does not work either. It results in a error message complaining about package name conflict with genshi_compiler.

**Comment by ewdurbin** [comment]
made some minor improvements to ensure that dash and underscore trivialities don't completely skip over packages that will match after normalization. _however_ it doesn't boost a match of `my-package` to `my_package` or a match of `my_package` to `my-package` up as dramatically as an exact match in the results.

**Comment by ewdurbin** [comment]
alright, boosting now taking effect in web ui searches.

that's as far as i'm going to push this :)
