### ISSUE TITLE
fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by tbasl** [pypa/pypi-legacy#561]
Hello folks,
I'm trying to install the latest version of RPi.GPIO (on RaspberryPi3) which is RPi.GPIO 0.6.3.  

When I run:
sudo python setup.py install

I get this error:
fatal error: Python.h: No such file or directory
 #include "Python.h"
.........................................^

Is this a legitimate bug or am I doing something stupid?

Thanks for any help.
Tim

PS. this is how far it gets before it fails:

pi@raspberrypi:~/gpio/RPi.GPIO-0.6.3 $ sudo python setup.py install
running install
running build
running build_py
creating build
creating build/lib.linux-armv7l-2.7
creating build/lib.linux-armv7l-2.7/RPi
copying RPi/__init__.py -> build/lib.linux-armv7l-2.7/RPi
creating build/lib.linux-armv7l-2.7/RPi/GPIO
copying RPi/GPIO/__init__.py -> build/lib.linux-armv7l-2.7/RPi/GPIO
running build_ext
building 'RPi._GPIO' extension
creating build/temp.linux-armv7l-2.7
creating build/temp.linux-armv7l-2.7/source
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c source/py_gpio.c -o build/temp.linux-armv7l-2.7/source/py_gpio.o
source/py_gpio.c:23:20: fatal error: Python.h: No such file or directory
 #include "Python.h"
........................................^
compilation terminated.
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

**Comment by berkerpeksag** [comment]
Hi, thanks for the report, but https://sourceforge.net/projects/raspberry-gpio-python/support might be a better place to ask questions like this (I think you need to install Python headers from your distro's package manager) This tracker is for issues with pypi.python.org only.

**Comment by bennuttall** [comment]
For anyone who finds this in future, the solution is to install the dev package required for building:

```bash
sudo apt install python3-dev
```

(or `python-dev` for Python 2)
