### ISSUE TITLE
xlrd: list index out of range when loading xlsx file through pandas.ExcelFile()

### ISSUE THREAD

**Issue by cperlmutter** [pypa/pypi-legacy#563]
After loading ~10 files correctly, pandas.ExcelFile() threw an exception on a new excel file

  File "C:\Python27\lib\site-packages\pandas\io\excel.py", line 227, in __init__
    self.book = xlrd.open_workbook(io)
  File "C:\Python27\lib\site-packages\xlrd\__init__.py", line 422, in open_workbook
    ragged_rows=ragged_rows,
  File "C:\Python27\lib\site-packages\xlrd\xlsx.py", line 839, in open_workbook_2007_xml
    x12sheet.process_stream(zflo, heading)
  File "C:\Python27\lib\site-packages\xlrd\xlsx.py", line 548, in own_process_stream
    self_do_row(elem)
  File "C:\Python27\lib\site-packages\xlrd\xlsx.py", line 703, in do_row
    value = self.sst[int(tvalue)]
IndexError: list index out of range

I did some debugging of the xlrd code and it seems the xml file sharedstrings.xml moved up a level from 'xl/sharedstrings.xml' to 'sharedstrings.xml'

I added the commented-out code below and it fixed the problem:

xlsx.py line 820:
    sst_fname = 'xl/sharedstrings.xml'
    x12sst = X12SST(bk, logfile, verbosity)
    if sst_fname in component_names:
        zflo = zf.open(component_names[sst_fname])
        x12sst.process_stream(zflo, 'SST')
        del zflo

#cperlmutter added this to fix
    # sst_fname = 'sharedstrings.xml'
    # if sst_fname in component_names:
    #     zflo = zf.open(component_names[sst_fname])
    #     x12sst.process_stream(zflo, 'SST')
    #     del zflo

the excel file that caused the problem was generated by Microsoft Great Plains 2016.  I believe all of the working excel files were generated with a previous version of great plains

I am using xlrd version 1.0.0

**Comment by cperlmutter** [comment]
Sorry if I didn't put this in the right place... I don't typically debug open source code

**Comment by jamadden** [comment]
Thank you for the report. Unfortunately, yes, this is the wrong place. This reporter is only for bugs relating to the PyPI software itself, not the third party packages hosted on it. You might try the [xlrd reporter](https://github.com/python-excel/xlrd/issues). (How did I find that? Starting on the [PyPI page for xlrd](https://pypi.python.org/pypi/xlrd), I followed the link to the [xlrd home page](http://www.python-excel.org) which pointed me to its github.)

**Comment by jamadden** [comment]
(Also, FWIW, I found [this bug](https://github.com/python-excel/xlrd/issues/101) that looks to be what you're experiencing. It's claimed to be fixed, but apparently not.)

**Comment by dstufft** [comment]
(Closing for the reasons @jamadden said!)
