### ISSUE TITLE
Windows 10 problems 

### ISSUE THREAD

**Issue by dibifirst** [pypa/pypi-legacy#567]
I have windows 10 env with 3.5.2 python that perfectly running under py shell. When I make exe in windows 7 everythink working properly, but if I make exe in windows 10, pyinstaller give some dipendency error of some API*.dlls.  The program running anyway but on quit return error saying that application end abnormaly.
Can you help?

**Comment by jamadden** [comment]
Thank you for your report, but this tracker is only for issues relating to the software that runs PyPI itself. It cannot help with anything having to do with the software distributed on PyPI or the Python language itself. For issues with pyinstaller, you need to contact [its developers](https://github.com/pyinstaller/pyinstaller).
