### ISSUE TITLE
Upload server uses a StartCom certificate

### ISSUE THREAD

**Issue by marcan** [pypa/pypi-legacy#568]
The upload server at https://upload.pypi.org/legacy/ is using a StartCom OV certificate. Recently, browsers vendors have started revoking or restricting trust in StartCom and its parent company WoSign due to a [string of negligent and malicious behavior](https://wiki.mozilla.org/CA:WoSign_Issues). Due to this, that certificate may stop working on systems in the future. Newer certs from StartCom will not work, as e.g. Chrome has [stopped accepting new StartCom certs](https://security.googleblog.com/2016/10/distrusting-wosign-and-startcom.html) issued after October 21, and many users such as myself have manually revoked trust in StartCom altogether, resulting in the inability to upload to PyPI today (unfortunately, non-browser TLS implementations do not support things like that special cut-off date, so it's all or nothing).

The main PyPI site is using a different certificate. If a free DV certificate is sufficient for upload.pypi.org, it could use Let's Encrypt. Alternatively, it could use different commercial CA.

**Comment by ewdurbin** [comment]
@dstufft now that Heroic supports LetsEncrypt, we could easily migrate to their Automated Certificate Management. if you're not against it, I'm happy to get this done.

**Comment by dstufft** [comment]
huh, didn't know Heroku supports LE now. Switching to LE makes a lot of sense, so +1

**Comment by ewdurbin** [comment]
I just ran through this with numerous apps at $DAY_JOB, it's pretty painless! I'll drop notes on the process here when I tackle it.

**Comment by ewdurbin** [comment]
Resolved

**Comment by ewdurbin** [comment]
This wasn't as seamless since we no longer had access to the original StartCom certificate.

We made the DNS swap to the new `herokudns.com` domain from `herokussl.com` and then started the Heroku ACM verification process.

Unfortunately, this did incur some downtime for upload service when TLS was not working. but all resolved now.
