### ISSUE TITLE
SSHLibrary pulls buggy Paramiko version

### ISSUE THREAD

**Issue by 9us7av0** [pypa/pypi-legacy#569]
If you install sshlibrary version 2.1.2, it will automatically install paramiko version 2.1.1, which has a change that is not backward compatible. 

The paramiko file client.py on version 2.1.1 calls for function t.start_client expecting an attribute "timeout" as input (does not work), while the earlier 2.0.2 version does not expect any input (works).

I had to to uninstall it and re-install paramiko on an older version. 
Commands: 
To uninstall paramiko: 
>pip uninstall paramiko 
To install paramiko version 2.0.2: 
>pip --no-cache-dir install paramiko==2.0.2. 

Before opening an issue for PyPI, please note the following:
  - This is for the codebase currently running pypi.python.org
  - [Warehouse](https://github.com/pypa/warehouse) is soon to replace this codebase. Some issues may be deferred to the issue tracker for [Warehouse](https://github.com/pypa/warehouse/issues) rather than be addressed here.
  - We do not maintain individual packages installed from PyPI, please seek out the maintainer

**Comment by jamadden** [comment]
Thank you for your report. However, this tracker is only for issues with the software that runs pypi.python.org itself. It is not for the software distributed there. The developers here cannot help you with problems in third-party software. You'll need to contact the [sshlibrary developers](https://github.com/robotframework/SSHLibrary/issues) (in fact it looks like there are already issues open about this).

**Comment by 9us7av0** [comment]
Thanks for the feedback and help!
