### ISSUE TITLE
How to update package info submitted by others if that's inactive ? 

### ISSUE THREAD

**Issue by node** [pypa/pypi-legacy#570]
For example , stompy has been submitted on pypi from bitbucket.com for 7 years ago. But some big bugs fixed today  by others, and the original author is inacitve . The developer can not install the new verson from pypi directly .

**Comment by AraHaan** [comment]
There is only 1 way to do that:

1. make a new name for it on pypi for the fixed copy.
2. Let those developers know about that new version with a new name on pypi that has those bug fixes. 

Other than that you are pretty much SOL.

**Comment by benjaminws** [comment]
Hello!

I'm the original author of the stompy package. I've long searched for someone to take this on without success. If I'm honest I abandoned bitbucket some time ago, so I've not been up to date on the issues there.

@node We can fix this! I can arrange the secure transfer of the package namespace and repository to a responsible maintainer. Please get in touch with me directly if you'd like to talk about this further: benjaminwarfield@gmail.com

**Comment by jamadden** [comment]
As this seems to be a matter of coordination among @benjaminws and @node now, there doesn't seem to be anything that PyPI is involved with, so I think we can close this.
