### ISSUE TITLE
New package not showing up in search results

### ISSUE THREAD

**Issue by alexforster** [pypa/pypi-legacy#574]
Hi!

Apologies if it ends up that I've done something stupid, but the [new package](https://pypi.python.org/pypi?name=inparallel&:action=display) that I registered two days ago still doesn't show up in search results and, despite significant research, I can't figure out why.

*Web search*

https://pypi.python.org/pypi?%3Aaction=search&term=inparallel&submit=search

*Pip search*

```
$pip -vvv search inparallel
Starting new HTTPS connection (1): pypi.python.org
"POST /pypi HTTP/1.1" 200 None
```

**Comment by rr-** [comment]
Same for https://pypi.python.org/pypi/urwid-readline/0.1
