### ISSUE TITLE
scholarly not pulling information for Patents

### ISSUE THREAD

**Issue by danielsamfdo** [pypa/pypi-legacy#576]
Before opening an issue for PyPI, please note the following:
  - This is for the codebase currently running pypi.python.org
  - [Warehouse](https://github.com/pypa/warehouse) is soon to replace this codebase. Some issues may be deferred to the issue tracker for [Warehouse](https://github.com/pypa/warehouse/issues) rather than be addressed here.
  - We do not maintain individual packages installed from PyPI, please seek out the maintainer

**Comment by Carreau** [comment]
Thank you for your report. However, this tracker is only for issues with the software that runs pypi.python.org itself. It is not for the software distributed there. The developers here cannot help you with problems in third-party software.

Please see with [scholarly repo itself](https://github.com/OrganicIrradiation/scholarly).

**Comment by danielsamfdo** [comment]
There is no issues link for the scholarly repo

**Comment by berkerpeksag** [comment]
Good point, let's ping @OrganicIrradiation (the repo owner) and hopefully they can active issue tracker on the repo. Thanks for the report!
