### ISSUE TITLE
 Non-gzipped simple index is stale

### ISSUE THREAD

**Issue by dairiki** [pypa/pypi-legacy#578]
I'm currently having trouble installing `setuptools` 32.2.0 (the latest, just came out earlier today) using `zc.buildout`.  I've traced the issue to the fact that if one requests the simple index for setuptools with no `Accept-Encoding` header one gets a stale version of the index.  Requesting with `Accept-Encoding: gzip` appears to yield the up-to-date version.
```
>>> curl -s -I -H "Accept-Encoding: gzip" -H "Cache-Control: no-cache" -H "Pragma: no-cache" https://pypi.python.org/simple/setuptools/ | grep -i last-serial
X-PYPI-LAST-SERIAL: 2534904

>>> curl -s -I -H "Cache-Control: no-cache" -H "Pragma: no-cache" https://pypi.python.org/simple/setuptools/ | grep -i last-serial
X-PYPI-LAST-SERIAL: 2534903
```

In this case, the only difference between these two indexes is that the stale one does not include  `setuptools-32.2.0.zip`, while the later one does.  (Buildout is getting stale index, and is looking for the source package.)

Things have been in this state for a few hours now.

**Comment by ewdurbin** [comment]
@dairiki thanks for report, i'm checking on the workers/jobs that are supposed to handle cache invalidation on update.

**Comment by dairiki** [comment]
Thank you!

The non-compressed version appears to be up-to-date now.
