### ISSUE TITLE
Cannot add or change a package's bug track url anymore.

### ISSUE THREAD

**Issue by AraHaan** [pypa/pypi-legacy#581]
Please add back online editing of package bug tracking urls. This is because no library in python especially setuptools, distutils, nor even distribute support feeding in ``bugtrack_url``'s in ``setup.py``'s which is kinda lame as packages with them now cant change the urls if their bug tracker moves to another place nor can others add a bug track url to their package if they noticed that some packages have it. It is lame if I say so myself. At least add an option in ``PKG-INFO`` or something that the site would accept for setting it or something so that way we can manage it under a ``setup.py`` file if we want to.

**Comment by ewdurbin** [comment]
@AraHaan ah, this is indeed an accidental regression. the same form which was used for package submission (and prone to spam) was also used for edit.

I'll look into if we can easily add back the form for editing individual packages.

**Comment by The-Compiler** [comment]
Thanks for the fix! 👍 Is there any plan on when this is going to be available on pypi.python.org (or is it just me who can't find it? 😆)?

**Comment by ewdurbin** [comment]
@The-Compiler ah, apologies that didn't go past testpypi until just now.

**Comment by AraHaan** [comment]
ah I see, thanks. I hope we can get it into setuptools / twine soon to so it can add it as an field to PKG-INFO as well as it would be nice to set it there as well.
