### ISSUE TITLE
Login with Google not working

### ISSUE THREAD

**Issue by patrikhuber** [pypa/pypi-legacy#582]
Hi!

On the main page https://pypi.python.org/pypi, I'm clicking "Login with Google", and then the page just refreshes, but nothing happens - I don't get logged in.

The very first time I did this, I got the sign-in window from Google where you have to click the "Accept" button to allow the sign-in via your Google account to happen. After clicking "Accept", I don't remember exactly but there was either a blank page or I just got back to the pypi page, without being signed in. Now the behaviour is as I outlined above - the page just refreshes and I can't log in or anything.

After the refresh the URL changes to: 

https://pypi.python.org/pypi?:action=openid_return&state=28b5fZZZb5&code=4/VfhZZZ529_U&authuser=0&session_state=c23aZZZc5..151d&prompt=none#

(I replaced some characters with "ZZZ", in case there's sensitive information in there).

**Comment by ewdurbin** [comment]
@patrikhuber google login is only supported for accounts previously created and associated with a google account. creation of new accounts require a "native" PyPI username/password account.

did you previously have a PyPI account which was associated with the google account?

**Comment by patrikhuber** [comment]
I see! No, this is my first time creating a PyPI account. So I have to create a PyPI account first using "Register", and can then associate it with my Google account using "Login with Google"?

**Comment by ewdurbin** [comment]
@patrikhuber plan is to deprecate federated login (OpenID/Google) in the future, so new google associates are not supported. if this is critical, an issue can be filed with the next-generation PyPI codebase here: https://github.com/pypa/warehouse/issues if one does not currently exist.

**Comment by patrikhuber** [comment]
Ok, I'll just create a normal account then, thanks!
