### ISSUE TITLE
Several packages fail to return a usable version

### ISSUE THREAD

**Issue by jrdemasi** [pypa/pypi-legacy#586]
Namely, at this point I have seen this with PyQt4 and SIP.  Environment info and other information below:

bash:~/custom_software/src/PyQt4_gpl_x11-4.12$ pip install SIP 
Collecting SIP
  Could not find a version that satisfies the requirement SIP (from versions: )
No matching distribution found for SIP

bash:~/custom_software/src/PyQt4_gpl_x11-4.12$ python --version
Python 2.7.12 :: Anaconda 4.2.0 (64-bit)
bash:~/custom_software/src/PyQt4_gpl_x11-4.12$ pip --version
pip 9.0.1 from /home/ubuntu/anaconda2/lib/python2.7/site-packages (python 2.7)

Can also reproduce on el7 with native, system python:

[root@biof-test ~]# python --version
Python 2.7.5
[root@biof-test ~]# pip --version
pip 8.1.2 from /usr/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg (python 2.7)
[root@biof-test ~]# pip install SIP 
Collecting SIP
  Could not find a version that satisfies the requirement SIP (from versions: )
No matching distribution found for SIP
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by ewdurbin** [comment]
it appears that PyQt4 continues to be hosted externally from pypi.python.org, and that SIP was until recently.

when installing via the index PyPI no longer returns links to externally hosted packages. please see https://www.python.org/dev/peps/pep-0470/
