### ISSUE TITLE
Add support to github smileys

### ISSUE THREAD

**Issue by gautamkrishnar** [pypa/pypi-legacy#588]
Currently pypi.python.org doesn't support GitHub smileys. I think it should be implemented in [Warehouse](https://github.com/pypa/warehouse) as well.

**Comment by ewdurbin** [comment]
@gautamkrishnar thanks for the request. given the state of the current PyPI codebase, we will not add this functionality in pypi-legacy. it's possible that it could be implemented in https://github.com/pypa/readme_renderer however.

however, you should feel welcome to open an issue in either https://github.com/pypa/readme_renderer/issues or https://github.com/pypa/warehouse/issues requesting the feature in warehouse.
