### ISSUE TITLE
<b></b> in project removal page title

### ISSUE THREAD

**Issue by jwilk** [pypa/pypi-legacy#593]
Project removal page includes this:
```html
<title>Confirm removal of &lt;b&gt;all&lt;/b&gt; information about &lt;b&gt;and all releases of&lt;/b&gt; project foobar.</title>
```
which browser display as
```
Confirm removal of <b>all</b> information about <b>and all releases of</b> project foobar.
```
This is pretty ugly.
Could you get rid of these `<b>`+`</b>` from the page title?

**Comment by ewdurbin** [comment]
it's not pleasant, but it's what we have until pypa/warehouse takes over as pypi.
