### ISSUE TITLE
TypeError: LoadLibrary() argument 1 must be string, not unicode

### ISSUE THREAD

**Issue by nuhorchak** [pypa/pypi-legacy#594]
Hi,  I am using pulp for an academic project, however with the latest windows update, I receive the following error:

C:\Users\nuhorchak\Anaconda2\lib\site-packages\pulp\solvers.py in <module>()
     39 except ImportError:
     40     import ConfigParser as configparser
---> 41 from . import sparse
     42 
     43 import collections

ImportError: cannot import name sparse

and 

LoadLibrary() argument 1 must be string, not Unicode 

any help is appreciated!

**Comment by berkerpeksag** [comment]
Thanks for the report, but the correct place to report issues with pulp is https://github.com/coin-or/pulp.
