### ISSUE TITLE
Fail to upgrade to version 0.6.2

### ISSUE THREAD

**Issue by F74** [pypa/pypi-legacy#596]
fritzconnection fail to upgrade to new version:

 #  pip install fritzconnection
Collecting fritzconnection
  Using cached fritzconnection-0.6.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-m90phedb/fritzconnection/setup.py", line 4, in <module>
        with open('pypi_description.rst') as file:
    FileNotFoundError: [Errno 2] No such file or directory: 'pypi_description.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-m90phedb/fritzconnection/
pip install fritzconnection  7,09s user 0,55s system 95% cpu 8,018 total

**Comment by jamadden** [comment]
Thank you for the report, but unfortunately this is not the correct place. What you're seeing is a result of an error in the .tar.gz file that the fritzconnection maintainers uploaded to PyPI (the MANIFEST.in file is incorrect). You'll need to contact them to fix it. According to https://pypi.python.org/pypi/fritzconnection, the homepage and issue tracker are located at https://bitbucket.org/kbr/fritzconnection

**Comment by berkerpeksag** [comment]
@jamadden is right. Thank you for the report, but I'm closing this as 'invalid'.
