### ISSUE TITLE
"Login with Google" not working

### ISSUE THREAD

**Issue by remdragon** [pypa/pypi-legacy#597]
I clicked "Login with Google" to create a new account. Google asked for my permission, which I granted. It redirected back to pypi but it still says I'm not logged in. Clicking "Login with Google" keeps bringing me back again without prompting for permission from Google again.

**Comment by ewdurbin** [comment]
We do not support new account creation via Google, or associations with existing accounts. Only previously associated accounts can be used with when logging in with google.
