### ISSUE TITLE
Python 3.6 not listed in drop-down box when uploading packages

### ISSUE THREAD

**Issue by baoilleach** [pypa/pypi-legacy#598]
I'm uploading a binary wheel to PyPi but the dropdown box of Python versions does not list Python 3.6, the latest version.

**Comment by baoilleach** [comment]
I see that this is fixed in pull request #592. Any chance of merging this? My users are hassling me about a Python 3.6 version, and I'm not sure that 3.6's pip will find it if I mark it as Python 3.5.

**Comment by berkerpeksag** [comment]
#592 is now merged and deployed in #600. Closing this as fixed. Thanks for the report!

**Comment by baoilleach** [comment]
Awesome. Just uploaded my files.
