### ISSUE TITLE
I need to seek out the maintainer for they do not maintain individual packages 

### ISSUE THREAD

**Issue by rjkmurray** [pypa/pypi-legacy#601]
Before opening an issue for PyPI, please note the following:
  - This is for the codebase currently running pypi.python.org
  - [Warehouse](https://github.com/pypa/warehouse) is soon to replace this codebase. Some issues may be deferred to the issue tracker for [Warehouse](https://github.com/pypa/warehouse/issues) rather than be addressed here.
  - We do not maintain individual packages installed from PyPI, please seek out the maintainer

**Comment by jamadden** [comment]
I'm sorry, I don't understand what you're trying to ask. Could you please clarify?

**Comment by rjkmurray** [comment]
I am having difficulty with the new changes to  python and pip, I believe it to be possible to upload the file and merge the two.

**Comment by rjkmurray** [comment]
Pip merged with the new addition of pip so on?

**Comment by jamadden** [comment]
I'm sorry, I still do not understand what you're asking. If you're asking how to *upgrade* pip, most of the time you will either use pip to upgrade itself ('pip install -U pip') or use a distribution's package manager ('apt-get' or the like). 

At any rate, questions about pip are out of place for this repository and tracker. This tracker is just about the software that runs pypi.python.org, it is not about pip or any other Python packages in general.

**Comment by rjkmurray** [comment]
I was trapped using a tablet and was in a endless battle to try

**Comment by jamadden** [comment]
I received a baffling email, to my github public address, apparently from the holder of the other account involved in this thread. I could make no sense of it. This other account has very little github activity, as of this date, and it all appears to be without comment. I do most earnestly apologize if we are simply encountering a language barrier, but I find myself wondering about the (bot?) origins of this other account at this point. 

Can anyone chime in? And again, I do not mean to be offensive or insensitive in any way, but I definitely do not understand.

**Comment by berkerpeksag** [comment]
I'm not sure my opinion should be counted as I'm not a native speaker, but I also find the whole thread hard to understand. Judging from the OP's recent activity on GitHub (see https://github.com/Homebrew/homebrew-core/pull/10075#pullrequestreview-22568018 and https://github.com/collectd/collectd/pull/2175#pullrequestreview-22598746) I agree that the OP might be a some kind of bot.

Closing this as 'invalid' for now. We can always reopen if the OP can clarify their problem with PyPI. Thanks!
