### ISSUE TITLE
Address in Package's "Journal" is sometimes an internal IP address

### ISSUE THREAD

**Issue by jacksontj** [pypa/pypi-legacy#603]
If I am signed in on pypi and looking at a package of mine there is a feature that shows the IP Address that various commands came from (add owner, create, remove, etc.). I just added a new package to pypi and I noticed that most of the IP addresses there are private addresses (10.x.x.x) -- but say "user" as me. I assume they are internal addresses as these are internal actions-- and if so, they shouldn't say my username (since I didn't do them) or if they *are* triggered by me they should probably show me the IP address of me (the user) when I requested them.

**Comment by ewdurbin** [comment]
@jacksontj can you provide a package name who's journal exhibits this behavior?

**Comment by ewdurbin** [comment]
@jacksontj I've done some research here, and don't see any private addresses from the `10.0.0.0/8` address space, only from publicly registered addresses outside that CIDR.

**Comment by ewdurbin** [comment]
eh, appears that some certainly reserved addresses are showing up.

**Comment by ewdurbin** [comment]
resolved.
