### ISSUE TITLE
Failed to detect operating system version for linux based.

### ISSUE THREAD

**Issue by mdaleem** [pypa/pypi-legacy#604]
Before opening an issue for PyPI, please note the following:
  - This is for the codebase currently running pypi.python.org
  - [Warehouse](https://github.com/pypa/warehouse) is soon to replace this codebase. Some issues may be deferred to the issue tracker for [Warehouse](https://github.com/pypa/warehouse/issues) rather than be addressed here.
  - We do not maintain individual packages installed from PyPI, please seek out the maintainer

**Comment by ewdurbin** [comment]
@mdaleem can you describe your issue more specifically? if so please reopen this issue with more detail.
