### ISSUE TITLE
Please rename pyCroscopy to pycroscopy

### ISSUE THREAD

**Issue by CompPhysChris** [pypa/pypi-legacy#605]
We have decided that it would be better for the package name to be all lowercase.  Could you please rename?  Thanks

**Comment by berkerpeksag** [comment]
Thanks for the report. I don't think you can rename a package's name. I think the only way to do this is: Delete `pyCroscopy` first; create a new project named `pycroscopy`.

See https://sourceforge.net/p/pypi/support-requests/324/#2478 for the response to a similar request from 2013.

**Comment by berkerpeksag** [comment]
I forgot to close this one after posting my comment. Please let us know if you have any further questions. Thank you for the report!
