### ISSUE TITLE
cxfreeze doesn't work!

### ISSUE THREAD

**Issue by bluishift** [pypa/pypi-legacy#606]
ok so with the last package 64bits for Windows or Linux for Python 3.6, it's just impossible to use cxfreeze
command line on Windows console: py cxfreeze name_of_my_programm.py
return
ModuleNotFoundError: No module 'named cx_Freeze.util'

same message on Linux...

After 3 days on this problem, I def' don't know what to do...
Help me please.

**Comment by jamadden** [comment]
Thank you for your report, but this is not the right tracker. This tracker is just for the software that runs PyPI itself. It cannot help with problems found in individual packages downloaded from PyPI. You'll need to request help from the cx_Freeze community. You might start at [their website](https://anthony-tuininga.github.io/cx_Freeze/) and consider the mailing lists or the SourceForge tracker.

**Comment by bluishift** [comment]
:) Did you really see their websites? ^^

**Comment by berkerpeksag** [comment]
Jason is right. Please report your problem to their issue tracker at https://github.com/anthony-tuininga/cx_Freeze/issues
