### ISSUE TITLE
Cant register (Incomplete registration; check your email)

### ISSUE THREAD

**Issue by Abdellbar** [pypa/pypi-legacy#607]
Hi Team, 

i am facing this error "Incomplete registration; check your email" whenever i try to register to test or live, this is the first time i register a package in PyPI, i have the file .pypir, i am sure though that my account is active i received the emails and activated my accounts on both servers. any ideas what would be the reason for this error.

Thanks
```
>sparkapi$ python setup.py register -r pypitest
running register
running egg_info
writing requirements to sparkapi.egg-info/requires.txt
writing sparkapi.egg-info/PKG-INFO
writing top-level names to sparkapi.egg-info/top_level.txt
writing dependency_links to sparkapi.egg-info/dependency_links.txt
reading manifest file 'sparkapi.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'sparkapi.egg-info/SOURCES.txt'
running check
Registering sparkapi to https://testpypi.python.org/pypi
Server response (401): Incomplete registration; check your email
```

**Comment by Abdellbar** [comment]
ADD : using twin also didn't work same issue, even though i was able to upload the package info on the package submission in the website

```
sparkapi$ twine register dist/sparkapi-0.1-py2-none-any.whl 
Registering package to https://pypi.python.org/pypi
Registering sparkapi-0.1-py2-none-any.whl
HTTPError: 401 Client Error: Incomplete registration; check your email for url: https://pypi.python.org/pypi
```

**Comment by GiriB** [comment]
@Abdellbar I think you forgot to approve your registration. The very first email that you would have received after registering with PyPI had a **confirmation link**. It would take you to a page where you'd have to accept the terms and conditions. Note that even if you hadn't done this step, you'd still be able to login to the site. 'Incomplete registration' indicates you not having accepted the terms and conditions.

**Comment by berkerpeksag** [comment]
@GiriB is correct. Perhaps the error message can be clarified. I'm closing this, but please feel free to suggest an alternative wording. Thanks!

**Comment by yan130** [comment]
Hi @GiriB , I get the same error as Abdellbar, and I did not receive "the very first email" you mention. what should I do to active my account?

**Comment by karask** [comment]
@berkerpeksag @GiriB  I seem to have the same issue. I did not receive any email (checked inbox, spam, etc.). Login is valid and email is the correct one.

I have registered a package in the past. Now I am trying another one and I have this issue.

**Comment by berkerpeksag** [comment]
@karask thanks for the report. You should receive an email titled "Complete your PyPI registration" when you've registered to PyPI. If you still can't find it, sending a password reset request will resend the confirmation email as described at https://github.com/pypa/pypi-legacy/issues/557#issuecomment-262270009.

@yan130 could you please try the same step if you still can't find the email?

**Comment by karask** [comment]
@berkerpeksag worked, thanks!

**Comment by yan130** [comment]
@berkerpeksag Thanks!
