### ISSUE TITLE
Misleading error message "HTTPError: 401 Client Error: You must login"

### ISSUE THREAD

**Issue by MartinThoma** [pypa/pypi-legacy#608]
I was trying to register a new package via `python setup.py` / `twine` (see https://github.com/pypa/twine/issues/234). When you use the wrong password, the error message

> HTTPError: 401 Client Error: You must login to access this feature for url: https://pypi.python.org/pypi

appears. This is missleading. There should be at least a notice that one might currently use the wrong credentials.

**Comment by berkerpeksag** [comment]
Thank you for your report. I have two comments:

1. Registering a package via `python setup.py register` or `twine` is not needed anymore.
2. Both distutils and twine don't use legacy PyPI to upload packages anymore. They now use https://github.com/pypa/warehouse (even if we improve that message in legacy PyPI, it will going to return the following message after a successful login: https://github.com/pypa/pypi-legacy/blob/23589fbc11a051e8f8e8583940f2cdf45047ccc2/webui.py#L2206-L2217) If you still see the same problem with pypi.org, I'd suggest report it to Warehouse maintainers.
