### ISSUE TITLE
 Unable to list or find packages contributed by me in pypi.

### ISSUE THREAD

**Issue by nirajKpanda** [pypa/pypi-legacy#609]
My pypy id is : nirajKpanda

I am unable to list or find all packages being contributed by me.Is there any back end api or way available to find those ?

**Comment by berkerpeksag** [comment]
What do you mean by "contributed by me"? There are two options If want to see packages that you've uploaded to PyPI:

* On pypi.python.org, login to your account and you will see the "Your packages:" section on the right sidebar.
* On pypi.org, you can see them at https://pypi.org/user/nirajKpanda/

If you want to see a list of packages that you've contributed to by sending patches, I don't think there is a way to track this information in both legacy and next generation PyPIs. I suggest opening an issue at https://github.com/pypa/warehouse/issues
