### ISSUE TITLE
"pypi stat" does not report numbers for releases after Dec'16

### ISSUE THREAD

**Issue by rvprasad** [pypa/pypi-legacy#610]
`pypi stat pytest` reports 0 downloads for  the last release on 17/01/22.  `pypi stat pytest-finer-verdicts` reports 0 downloads for the last release on 17/02/25.  `pypi stat thinc` reports 0 downloads for last seven releases dating back to 17/01/09.  

This data does not seem to be correct as I have installed the latest version of all of the above modules via pip in the last month.

**Comment by ewdurbin** [comment]
download stats have been broken or inaccurate on legacy-pypi for well over a year. please see https://mail.python.org/pipermail/distutils-sig/2016-May/028986.html for more information on download statistics via the public dataset.
