### ISSUE TITLE
googlefinance doesn't work due to 'ImportError: No module named demjson'

### ISSUE THREAD

**Issue by os101** [pypa/pypi-legacy#611]
The instructions in https://pypi.python.org/pypi/googlefinance couldn't be followed due to the lack of demjson module. I tried on mac, radhat and ubuntu. 

{code}
>>> from googlefinance import getQuotes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "googlefinance/__init__.py", line 3, in <module>
    import demjson
{code}

**Comment by Carreau** [comment]
Thank you for your report. However, this tracker is only for issues with the software that runs pypi.python.org itself. It is not for the software distributed there. The developers here cannot help you with problems in third-party software.

Please contact the google finance developers, likely at https://github.com/hongtaocai/googlefinance
