### ISSUE TITLE
Question regarding the specific platform/Python version checking on PyPi

### ISSUE THREAD

**Issue by ukrit-himakoon** [pypa/pypi-legacy#612]
Hello team,

We're planning to upload our project to PyPi but our software has some specific conditions below:
1. Each software releases will depends on Platform (Such as Unix and Windows)
2. Each software releases also depends on the specific Python version (Python 2 and Python 3)

What our goal is that when user type `pip install software` he'll got the compatible software for their environment with the correct python version.

Any recommendation for this?

**Comment by Carreau** [comment]
hi @ukrit-himakoon  I'm guessing the question is better suited for [distutil-sig](https://mail.python.org/mailman/listinfo/distutils-sig), or setuptools.

Your sofware should have only a single source (.tgz or zip file) , then at build time it have to generate generate the wheel for each (python-version, os, architecture) group. See for example for [matplotlib](https://pypi.python.org/pypi/matplotlib). 

You should find most information in the [python packaging guide](https://packaging.python.org/)

**Comment by di** [comment]
I think @Carreau has answered the question here, so I'll close the issue. Distutils-sig is definitely the more appropriate place to ask this type of question.
