### ISSUE TITLE
Request trove classifer Framework :: Odoo

### ISSUE THREAD

**Issue by sbidoul** [pypa/pypi-legacy#613]
The [Odoo Community Association (OCA)](https://odoo-community.org) is coordinating the maintenance of a large number of open source [Odoo](https://www.odoo.com) addons. They are currently hosted at https://wheelhouse.odoo-community.org/oca. We would like to host them on pypi to facilitate installation and increase awareness.

On behalf of the board of the Odoo Community Association, I would like to request a new trove classifier for the Odoo framework: `Framework :: Odoo`.

Thanks in advance.

[updated] to mention OCA addons are open source

**Comment by pedrobaeza** [comment]
:+1:

**Comment by PCatinean** [comment]
:+1:

**Comment by adrienpeiffer** [comment]
:+1:

**Comment by lmignon** [comment]
👍

**Comment by rvalyi** [comment]
:+1:

**Comment by sbidoul** [comment]
@dstufft is this the right place and procedure to request new trove classifiers?

**Comment by ewdurbin** [comment]
Added:
  - `Framework :: Odoo`

**Comment by pedrobaeza** [comment]
:clap: :clap: :clap:

**Comment by sbidoul** [comment]
Wonderful, thanks!
