### ISSUE TITLE
pip-9.0.1-py2.py3-none-any.whl (md5, pgp) - BUG

### ISSUE THREAD

**Issue by BigIron67** [pypa/pypi-legacy#614]
When using visual studio, this pip creates "Import error" when using Intellisense. Microsoft Bitdefender also identifies it in the malware family and its now labeled as such. The only fix I was able to use for this is VS Update 2 and now 3 seems to overcome this. 
Note: I cannot use Intellisense to "pip install PyPI" this will create the "Import error" for your modules

**Comment by berkerpeksag** [comment]
I think this needs to be reported to Microsoft. I'm not sure what do you mean by "pip install PyPI", but the PyPI package at https://pypi.python.org/pypi/pypi is just a placeholder and it won't install anything.

Closing this for now. We can reopen this if you can provide more information to reproduce the problem. Thanks for the report!
