### ISSUE TITLE
Recover account rgrp

### ISSUE THREAD

**Issue by rufuspollock** [pypa/pypi-legacy#615]
Hi I reported this here: https://sourceforge.net/p/pypi/support-requests/685/ back in November

I lost access to the recover account email address for rgrp user on pypi.

Please could I have the email addressed changed to: reghigh@rufuspollock.org

I have a fair number of packages or pypi I'd like to update asap.

Many, many thanks in advance.

**Comment by ewdurbin** [comment]
@rufuspollock can you confirm the previous email address for the user `rgrp`?

**Comment by rufuspollock** [comment]
@ewdurbin yes - i've emailed this to you privately.

**Comment by ewdurbin** [comment]
@rufuspollock complete.

**Comment by ewdurbin** [comment]
@rufuspollock you should just need to execute a password reset now.

**Comment by rufuspollock** [comment]
@ewdurbin thanks so much!
