### ISSUE TITLE
Claim package FIAT

### ISSUE THREAD

**Issue by johannesring** [pypa/pypi-legacy#616]
For a while ago I tried to claim the package FIAT on PyPI by registering a support request here: https://sourceforge.net/p/pypi/support-requests/702/. Unfortunately, there has been no response so far and it seems that no one is working on solving the support requests. Can someone here please help transferring the ownership of the FIAT package to my account `johannr` on PyPI?

**Comment by ewdurbin** [comment]
@johannesring  the name `fiat` has been registered by another user.

we currently do not have an established process for releasing a name and will not perform such an administrative action until a process is agreed upon. there is currently discussion regarding this matter here: https://mail.python.org/pipermail/distutils-sig/2017-January/029998.html

**Comment by garth-wells** [comment]
@ewdurbin We have the user who registered the project onboard (rckirby), but he registered using an email address at a former employer which is no longer active.

**Comment by garth-wells** [comment]
@ewdurbin Can we move this along somehow? The process under discussion for releasing a name is not relevant in this case - we can ask the maintainer and put you in touch with him. The simple issue is that the email under which he registered is no longer active.

**Comment by ewdurbin** [comment]
@garth-wells does the author still own their @uchicago.edu email address? if so, please have them respond to the message i just sent with `Subject: FIAT package on PyPI`.

**Comment by garth-wells** [comment]
@ewdurbin No, they no longer have the @uchicago.edu email address. That's the problem we're having. The person in question is @rckirby (<http://sites.baylor.edu/robert_kirby/>).

**Comment by chrisrichardson** [comment]
@ewdurbin - can you take another look at this? We will otherwise have to make a new package with the same content, but a different name... if nothing else, maybe you can just delete the package entry: it is totally defunct, and does not work anyway.

**Comment by rckirby** [comment]
I'm the original author of the package, but haven't been at UChicago for over 10 years.  The email address is defunct.  I'd be glad to have this package claimed and re-registered under a different email address.  FEniCS are attempting to get packages registered under a generic FEniCS address to prevent problems like this in the future.
