### ISSUE TITLE
Please delete or rename the "wx" package

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#62]
Originally reported by: **Skip Montanaro (Bitbucket: [skip_montanaro](https://bitbucket.org/skip_montanaro), GitHub: Unknown)**

----------------------------------------

There is a fairly useless PyPI package named "wx" which is apparently confusing a fair number of people who really want to install "wxPython".  From a post to comp.lang.python, I quote:

*I was trying to install wxPython earlier today.  Not RTFMing, I tried 'easy_install wx', which ended up installing this strange module: https://pypi.python.org/pypi/wx

Looking at the download stats, it seems to be confusing ~1000 users a month, while not providing any significant functionality.

I don't really have any way to contact the author of the module.  Is there any way to have this deleted/renamed?*

Can you please delete or rename it?  I see no way to contact the author.

Thanks,

Skip

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/62

**Comment by berkerpeksag** [comment]
Closing this since the wx package has already been removed as stated by https://github.com/pypa/pypi-legacy/issues/62#issuecomment-226939044.
