### ISSUE TITLE
Can't reuse name of package I deleted

### ISSUE THREAD

**Issue by benlindsay** [pypa/pypi-legacy#620]
I uploaded a package called "simtree", and I was making a bunch of little changes to learn how to work with pypi. Once I figured I had a working distribution, I wanted to start fresh with version 0.1, so I deleted simtree with the intent to start over with that name. I saw the big scary red box that says "Do NOT use this button. There is no undo. Remove this project completely." It looked like the remove repo buttons on Bitbucket and GitHub. Then I tried reusing that name, but it wouldn't let me! Then I read [this post](https://www.reddit.com/r/Python/comments/35xr2q/howto_overwrite_package_when_reupload_to_pypi/cr8ui6t/) which suggests that after deleting a package, that name is forever after unusable.

Is this true? If so, then why doesn't the big red box mention somewhere that not only will the content be gone forever, but the name will be forever unusable? That is a very important piece of information that definitely would have kept me from pushing that button. Is there any way I can use that name again?

**Comment by dstufft** [comment]
You should be able to reuse the name, but not the versions.

**Comment by benlindsay** [comment]
OK, thanks, good to know!
