### ISSUE TITLE
install pyre2 fatal error 'mutex' file not found.

### ISSUE THREAD

**Issue by johnnybeale** [pypa/pypi-legacy#621]
followed instructions for downloading and installing pyre2 and received fatal error.

$ sudo python setup.py install
running install
running build
running build_ext
building 're2' extension
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/re2.cpp -o build/temp.macosx-10.6-intel-2.7/src/re2.o -std=c++11
In file included from src/re2.cpp:202:
/usr/local/include/re2/re2.h:186:10: fatal error: 'mutex' file not found
#include <mutex>
         ^
1 error generated.
error: command '/usr/bin/clang' failed with exit status 1

please let me know further information you would like me to provide.

**Comment by ewdurbin** [comment]
hello @johnnybeale! this is an issue with the pyre2 package itself, please reach out with your issue over at the project's page: https://github.com/facebook/pyre2#id5

**Comment by apiro** [comment]
Has been fixed this issue? 
thanks is really important

**Comment by ewdurbin** [comment]
@apiro, please see https://github.com/facebook/pyre2#id5
