### ISSUE TITLE
TypeError when calling release_urls from XML-RPC API

### ISSUE THREAD

**Issue by cedk** [pypa/pypi-legacy#625]
Since today, XML-RPC calls to release_urls return this error:
` xmlrpclib.Fault: <Fault 1: "<type 'exceptions.TypeError'>:datetime.datetime(2009, 10, 12, 19, 8, 2, 603359) is not JSON serializable">`
I guess it is linked to 6b0e95c8344744773691767441714b82037fc2c5 because RedisLru uses json dump but datetime can not be dumped in json.

**Comment by cedk** [comment]
@ewdurbin maybe the cache decorator could be removed until a solution to dump datetime in json is found.

**Comment by ewdurbin** [comment]
oof, sorry about this! Fix will be live shortly

**Comment by cedk** [comment]
If you want I can propose a solution to support datetime in RedisLru ?
