### ISSUE TITLE
nupic.bindings has wheel files , which are not installing in rhel 6.7 , i used pip

### ISSUE THREAD

**Issue by manahnmed** [pypa/pypi-legacy#630]
Hi Guys,

 pip install -U root nupic.bindings-0.6.1-cp27-cp27mu-manylinux1_x86_64.whl
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
nupic.bindings-0.6.1-cp27-cp27mu-manylinux1_x86_64.whl is not a supported wheel on this platform.

Need a quick resolution , please help me out

**Comment by ewdurbin** [comment]
@manahnmed please file an issue with the packager at https://github.com/numenta/nupic.core/issues

In the meantime, you can use `pip install --no-binary nupic.bindings nupic.bindings` to force pip to pass on the wheel and install the package from source, compiling any necessary extensions with your local environment.

**Comment by manahnmed** [comment]
Thanks ewdurbin, 
For some reason my machine do not have outbound connectivity , I'm press to install it locally
