### ISSUE TITLE
Cannot rename a package to be named PEP8 compliant because the new name conflicts with itself... (what?)

### ISSUE THREAD

**Issue by Pomax** [pypa/pypi-legacy#631]
I'm trying to rename my published package `filebrowser-s3`, which uses not PEP8 compliant naming, to `filebrowser_s3`, which *is* PEP8 compliant. However, when I do so, the pypi system goes "forbidden. This conflicts with package filebrowser-s3"..... which, yeah, of course it does, *that's the package I'm trying to rename* =)

(all the manifest files, the repo, etc. already all say that the name is `filebrowser_s3`, the only thing that doesn't right now is the registry itself)

Also, why do the pypi test and live registries allow people to submit packages with names that are not PEP8 compliant if you cannot safely rename them after realizing your mistake? Both servers should probably send back a "409 Rename your package, only alphanumeric characters and underscores are permitted" instead of a "200 HTTP OK" when people forget to make sure their package follows the proper naming conventions, to prevent this from happening in the future.

**Comment by ewdurbin** [comment]
@Pomax thanks for the report.

Package names and module names are not held to the same validation rules.

PyPI does not inspect the module itself for importable names/namespaces, so we cannot perform the validation you are requesting. If you think this should be implemented, please open an issue at https://github.com/pypa/warehouse/issues.

Regarding the conflict in package name on PyPI, we don't have a process for renaming packages at this time. Although this was performed in the past, we are trying to minimize the amount of this kind of administration being done while we transition from this codebase to warehouse for PyPI.

I've filed an issue on warehouse, and you can track progress on the project renaming there. https://github.com/pypa/warehouse/issues/1919

**Comment by Pomax** [comment]
thanks @ewdurbin - shame to hear renaming is not possible, that might be worth pointing out when users edit their entry (perhaps present the name as a fixed string rather than an input element?)
