### ISSUE TITLE
Improve error message for non-PEP-527-compliant files

### ISSUE THREAD

**Issue by jdemeyer** [pypa/pypi-legacy#634]
I am trying to upload a package to pypi. I managed to register it correctly: https://pypi.python.org/pypi/cypari2

However, when uploading with `twine`, I get
```
$ twine upload dist/cypari2-1.0.0.tar.bz2 
Uploading distributions to https://pypi.python.org/pypi
Enter your password: 
Uploading cypari2-1.0.0.tar.bz2
[================================] 99002/99002 - 00:00:00
HTTPError: 400 Client Error: invalid distribution file for url: https://pypi.python.org/pypi
```

Is there any way to get more feedback about why this file is refused? This is a standard tarball generated with `python setup.py sdist --formats=bztar`

You can find a copy of the tarball on http://sage.ugent.be/www/jdemeyer/sage/cypari2-1.0.0.tar.bz2

CC @defeo

**Comment by di** [comment]
The `.tar.bz2` extension is no longer a valid distribution format. See https://github.com/pypa/pypi-legacy/commit/4b1b95382de2116da03444a39f036c621653c6fa and https://www.python.org/dev/peps/pep-0527/.

**Comment by jdemeyer** [comment]
> The .tar.bz2 extension is no longer a valid distribution format. See 4b1b953 and https://www.python.org/dev/peps/pep-0527/.

At least the error message could have been more clear for people not reading every PEP :-)

**Comment by jdemeyer** [comment]
I guess a minimal patch would be to change the message to something like
```
invalid distribution filename (see https://www.python.org/dev/peps/pep-0527/)
```

**Comment by ewdurbin** [comment]
resolved in https://github.com/pypa/warehouse/pull/2387
