### ISSUE TITLE
Can't download an 3.3x versions of supervisor

### ISSUE THREAD

**Issue by repoocaj** [pypa/pypi-legacy#636]
I'm setting up a Yocto recipe to download supervisor.  It's attempting to download https://pypi.python.org/packages/source/s/supervisor/supervisor-3.3.1.tar.gz and failing with a 404 error.

Going to https://pypi.python.org/simple/supervisor/ lists that version as one of the available versions.

Using wget to manually retrieve the file also results in a 404 error:
```
jcooper@jcooper-linux:~/projects/kcp/dragonboard$ wget https://pypi.python.org/packages/source/s/supervisor/supervisor-3.3.1.tar.gz
--2017-05-03 17:04:55--  https://pypi.python.org/packages/source/s/supervisor/supervisor-3.3.1.tar.gz
Resolving pypi.python.org (pypi.python.org)... 151.101.192.223, 151.101.0.223, 151.101.64.223, ...
Connecting to pypi.python.org (pypi.python.org)|151.101.192.223|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-05-03 17:04:55 ERROR 404: Not Found.
```

The last file that I can successfully wget is supervisor-3.2.3.tar.gz.

**Comment by ewdurbin** [comment]
@repoocaj you must use the url linked in the simple index. the format you are using has been deprecated.
