### ISSUE TITLE
What if someone submitted a almost same package to pypi.

### ISSUE THREAD

**Issue by huxuan** [pypa/pypi-legacy#637]
Hi PyPI admins,

I am currently the maintainer of Python SDK for Microsoft Cognitive Face API [1] and one of the owners of `cognitive_face` package [2]. But accidentally I find someone else has forked the repo [3] and submit a new package on PyPI with name `cognitive_face_latest` [4] which is actually outdated. I wonder how should we deal with this kind of condition.

[1] https://github.com/microsoft/Cognitive-Face-Android
[2] https://pypi.python.org/pypi/cognitive_face
[3] https://github.com/levchik/Cognitive-Face-Python
[4] https://pypi.python.org/pypi/cognitive-face-latest

**Comment by di** [comment]
Hi @huxuan, sorry for the late reply. Have you tried contacting the creator of this fork?

**Comment by huxuan** [comment]
@di Thanks for your attention. I have not tried to contact the creator. And the latest version of that package is uploaded more than 1 year ago. So you suggest me to contact the creator directly?

**Comment by di** [comment]
@huxuan Yes, I'd recommend doing that first. Let us know if they don't respond and we'll take it from there.

**Comment by huxuan** [comment]
@di, I tried to send an email to the guy according to the email address he noted on Github, but it seems that the email address is not reachable. Do you have any other suggestions on this?

**Comment by MarkMangoba** [comment]
@huxuan can you forward us your communication attempt?  Although the email bounced back, it would be good to keep it handy for documentation that you tried.

**Comment by huxuan** [comment]
@MarkMangoba I have forwarded the email to you. Please let me know if there is anything wrong.

**Comment by di** [comment]
@huxuan I've removed the project.

**Comment by huxuan** [comment]
@di Confirmed! Thanks for the efforts!
