### ISSUE TITLE
scipy 0.19 for win is lost

### ISSUE THREAD

**Issue by chuxiyue** [pypa/pypi-legacy#641]
look at this list ,

 

File

Type

Py Version

Uploaded on

Size

scipy-0.19.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (md5, pgp)   Python Wheel  cp27  2017-03-09 15MB 
scipy-0.19.0-cp27-cp27m-manylinux1_i686.whl (md5, pgp)   Python Wheel  cp27  2017-03-09 36MB 
scipy-0.19.0-cp27-cp27m-manylinux1_x86_64.whl (md5, pgp)   Python Wheel  cp27  2017-03-09 42MB 
scipy-0.19.0-cp27-cp27mu-manylinux1_i686.whl (md5, pgp)   Python Wheel  cp27  2017-03-09 36MB 
scipy-0.19.0-cp27-cp27mu-manylinux1_x86_64.whl (md5, pgp)   Python Wheel  cp27  2017-03-09 42MB 
scipy-0.19.0-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (md5, pgp)   Python Wheel  cp34  2017-03-09 15MB 
scipy-0.19.0-cp34-cp34m-manylinux1_i686.whl (md5, pgp)   Python Wheel  cp34  2017-03-09 37MB 
scipy-0.19.0-cp34-cp34m-manylinux1_x86_64.whl (md5, pgp)   Python Wheel  cp34  2017-03-09 43MB 
scipy-0.19.0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (md5, pgp)   Python Wheel  cp35  2017-03-09 15MB 
scipy-0.19.0-cp35-cp35m-manylinux1_i686.whl (md5, pgp)   Python Wheel  cp35  2017-03-09 38MB 
scipy-0.19.0-cp35-cp35m-manylinux1_x86_64.whl (md5, pgp)   Python Wheel  cp35  2017-03-09 45MB 
scipy-0.19.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (md5, pgp)   Python Wheel  cp36  2017-03-09 15MB 
scipy-0.19.0-cp36-cp36m-manylinux1_i686.whl (md5, pgp)   Python Wheel  cp36  2017-03-09 39MB 
scipy-0.19.0-cp36-cp36m-manylinux1_x86_64.whl (md5, pgp)   Python Wheel  cp36  2017-03-09 46MB 
scipy-0.19.0.zip (md5, pgp)  

Before opening an issue for PyPI, please note the following:
  - This is for the codebase currently running pypi.python.org
  - [Warehouse](https://github.com/pypa/warehouse) is soon to replace this codebase. Some issues may be deferred to the issue tracker for [Warehouse](https://github.com/pypa/warehouse/issues) rather than be addressed here.
  - We do not maintain individual packages installed from PyPI, please seek out the maintainer

**Comment by jamadden** [comment]
Thank you for your report, but this tracker is for issues with PyPI itself, *not* the software hosted there. You'll need to reach out to the scipy maintainers directly to request different wheels.
