### ISSUE TITLE
cx_Oracle-5.3-11g.win-amd64-py3.5-2.exe  seems to be the wrong version

### ISSUE THREAD

**Issue by C0ppert0p** [pypa/pypi-legacy#642]
Hopefully, I'm just an idiot, but
when I run cx_Oracle-5.3-11g.win-amd64-py3.5-2.exe the console indicates I need to be running Python 3.4:
UnsatisfiableError: The following specifications were found to be in conflict:
  - cx_oracle 5.2* -> python 3.4*
  - python 3.5*

I'm running Anaconda and have Python 3.5 using the root environment
    H:\>python --version
    Python 3.5.3 :: Anaconda custom (64-bit)

so, is cx_Oracle-5.3-11g.win-amd64-py3.5-2.exe really what it claims to be?

**Comment by jamadden** [comment]
Thank you for the report, but this tracker is just for the software that runs pypi.python.org itself. It can't help you with issues specific to the software distributed there. You'll need to contact the cx-oracle maintainers for further assistance.

**Comment by C0ppert0p** [comment]
Thanks. I opened up another one under **oracle/python-cx_Oracle**

**Comment by berkerpeksag** [comment]
I'm closing this since you've reported this to cx-oracle developers, thank you! (and thank you for doing triage work, Jason!)
