### ISSUE TITLE
docutils latest version contains string

### ISSUE THREAD

**Issue by kfirilani** [pypa/pypi-legacy#646]
docutils latest package version is 0.14rc1
while other packages try to parse the version (such as sphinx), it fails due to parse error for int()

 File "/Users/ci/workspace/wrk_automation_utils_mac_debug/.eggs/Sphinx-1.3.1-py2.7.egg/sphinx/util/compat.py", line 17, in <genexpr>
    docutils_version = tuple(int(x) for x in _du_version.split('.')[:2])
ValueError: invalid literal for int() with base 10: '14rc1'

Can you please update docutils version to contains only integers (as universal format)

Thanks

**Comment by jamadden** [comment]
Thank you for your report!

Unfortunately, this is not the place to report it. This tracker is only for the software that runs pypi.python.org itself. It cannot help with the packages that are simply hosted there. You'll need to get in touch with the maintainers of docutils itself. [Their webpage](http://docutils.sourceforge.net) has instructions on how to do this.
