### ISSUE TITLE
Where to report bugs of pypi packages?

### ISSUE THREAD

**Issue by kenorb** [pypa/pypi-legacy#647]
You advice to 'seek out the maintainer', but how?

I'm trying to report bug for [quartz package](https://pypi.python.org/pypi/quartz), but there isn't any option on the website to contact the package owner. How should I do it normally?

**Comment by jamadden** [comment]
Try here: https://github.com/vladcalin/quartz

If the pypi.python.org page doesn't directly list enough information to find the maintainers, you'll have to look for yourself. In some cases, if you download and unpack the sdist it will include a README file or some other information not published to PyPI. 

In other cases, you can try looking for other packages the user has published to PyPI. I did that by going to https://pypi.org/user/vcalin/. Then look at the other packages for URLs; I was easily able to find the github account for this user from those other packages, and from there it was easy to find the quartz repository.

In the worst case scenario you'll just have to resort to some web searches.

Good luck in the future!
