### ISSUE TITLE
claim package: kobo

### ISSUE THREAD

**Issue by ktdreyer** [pypa/pypi-legacy#648]
I've agreed with original [kobo](https://github.com/release-engineering/kobo) upstream author (@dmach) to take over the maintenance of kobo on PyPI, however it is owned by somebody else on PyPI. Unfortunately I was not able to find any contacts for this user (zichengge). Is it possible either to transfer ownership to me (PyPI id ktdreyer) or at least to get contacts for zichengge?

I've requested this in [sourceforge](https://sourceforge.net/p/pypi/support-requests/632/) and the [distutils-sig mailing list](https://mail.python.org/pipermail/distutils-sig/2017-March/030337.html). It's discussed upstream as well at https://github.com/release-engineering/kobo/issues/24

I understand PyPI administration is a volunteer effort, and if there is any sort of reciprocal work I can do for PyPI to help out the admins in return for this favor, please let me know!

**Comment by xuanjia** [comment]
Hi Ken.  
I have added 'ktdreyer' as a owner for 'kobo' in Pypi.  I think you have the permission to manage it.

Thanks

**Comment by berkerpeksag** [comment]
Thank you for the response, @xuanjia. It looks like everything is set and we can now close this issue. Please let me know if it's not so we can reopen it.

**Comment by ktdreyer** [comment]
You guys rock.
:guitar: :heart: :bowing_man:
