### ISSUE TITLE
问题1：无法使用正确的凭据进行身份验证  我可以使用我的用户名密码登录https://pypi.python.org/pypi，以确保它们是正确的  但是我无法上传我的包。我总是得到  Upload failed (403): Invalid or non-existent authentication information. error: Upload failed (403): Invalid or non-existent authentication information.

### ISSUE THREAD

**Issue by northplxh** [pypa/pypi-legacy#649]
问题1：无法使用正确的凭据进行身份验证

我可以使用我的用户名密码登录https://pypi.python.org/pypi，以确保它们是正确的

但是我无法上传我的包。我总是得到

Upload failed (403): Invalid or non-existent authentication information.
error: Upload failed (403): Invalid or non-existent authentication information.

**Comment by berkerpeksag** [comment]
Please use English to report your problem or use a local Python support channel. You need to create a `~/.pypirc` file with your login information in it. For example, here is mine:

```ini
[distutils]
index-servers =
    pypi

[pypi]
repository = https://pypi.python.org/pypi
username = YOUR_USERNAME
password = YOUR_PASSWORD
```

**Comment by northplxh** [comment]
I create a /.pypirc as yours.But I still can't  upload.Here is my computer show me. I can't understand it.

D:\Python36\lib\distutils\dist.py:261: UserWarning: Unknown distribution option:
 'auther'
  warnings.warn(msg)
D:\Python36\lib\distutils\dist.py:261: UserWarning: Unknown distribution option:
 'auther_email'
  warnings.warn(msg)
running sdist
running check
warning: check: missing meta-data: either (author and author_email) or (maintain
er and maintainer_email) must be supplied

warning: sdist: manifest template 'MANIFEST.in' does not exist (using default fi
le list)

warning: sdist: standard file not found: should have one of README, README.txt

writing manifest file 'MANIFEST'
creating dk_nester001-1.0.0
making hard links in dk_nester001-1.0.0...
hard linking nester.py -> dk_nester001-1.0.0
hard linking setup.py -> dk_nester001-1.0.0
Creating tar archive
removing 'dk_nester001-1.0.0' (and everything under it)
running upload
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    description = 'A simple printer of nested lists',
  File "D:\Python36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Python36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Python36\lib\distutils\dist.py", line 973, in run_command
    cmd_obj.ensure_finalized()
  File "D:\Python36\lib\distutils\cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "D:\Python36\lib\distutils\command\upload.py", line 46, in finalize_optio
ns
    config = self._read_pypirc()
  File "D:\Python36\lib\distutils\config.py", line 57, in _read_pypirc
    config.read(rc)
  File "D:\Python36\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "D:\Python36\lib\configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'C:\\Users\\DeKun\\.pypirc', line: 1
'index-servers = pypi\n'

**Comment by jamadden** [comment]
The error message you're getting, ``configparser.MissingSectionHeaderError: File contains no section headers,`` **strongly** suggests that your 'C:\Users\DeKun\.pypirc' is not formatted correctly. It appears to be missing the first line, which should be `[distutils]`.
