### ISSUE TITLE
"python -v -m pip install fpdf" hangs at "setuptools"

### ISSUE THREAD

**Issue by Arie-vw** [pypa/pypi-legacy#651]
Had bad luck trying to install fpdf using pip.

I did a verbose run and it seems to hang here:

import setuptools # loaded from Zip E:\Programs\python\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\__init__.py

I am using latest miniconda (3.6.1) on Windows 10 latest updates.
[ BTW: I also tried (earlier) vanilla Python install, but that alsohangs on installing pip (booptstrap). ]

**Comment by jamadden** [comment]
Thank you for the report, but unfortunately this is the wrong place for it. This repository is *only* for issues affecting the software that runs pypi.python.org itself. It cannot help with issues installing packages distributed from there or with general issues with your python installation. You might seek out the maintainers of the package, or the maintainers of miniconda, or python-list, or the pip maintainers for further help.

**Comment by Arie-vw** [comment]
OK. Thx!
