### ISSUE TITLE
The site http://pythonhosted.org is not available

### ISSUE THREAD

**Issue by bgaifullin** [pypa/pypi-legacy#659]
The site http://pythonhosted.org is not available since June 30 2017
The following information is showed instead of content:

```
Service Unavailable

The service is temporarily unavailable. Please try again later.
```

**Comment by berkerpeksag** [comment]
Thank you for the report! According to [this tweet](https://twitter.com/dstufft/status/882002342509522944) it's now working fine. Closing this as 'fixed'.
