### ISSUE TITLE
pypi.python.org or package issue?

### ISSUE THREAD

**Issue by rogerguess** [pypa/pypi-legacy#660]
I am attempting to install tensorflow_gpu for Windows. I have had a few issues. First was time outs. I added --timeout 10000 to pip to get around those. Next I started getting hash errors:

pip install --upgrade tensorflow_gpu --timeout 1000000
Collecting tensorflow_gpu
  Downloading tensorflow_gpu-1.2.1-cp35-cp35m-win_amd64.whl (51.3MB)
    1% |                                | 952kB 756bytes/s eta 18:28:51
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    tensorflow_gpu from https://pypi.python.org/packages/96/2f/add5d94ea25811a0f53d2b19b656b3ed36e9f2a87ecc0702b0b60d0f24ec/tensorflow_gpu-1.2.1-cp35-cp35m-win_amd64.whl#md5=558e3a2a7c0e3508117bd9996a5c416f:
        Expected md5 558e3a2a7c0e3508117bd9996a5c416f
             Got        b24096216b1dec84a25ab78216a8c302

How can I tell if this is pypi, or if an issue with the package, or even possibly a caching issue from my ISP? 

my connection: http://beta.speedtest.net/result/6430541487.png

a ping and some traces:

C:\Windows\system32>ping pypi.python.org

Pinging prod.python.map.fastly.net [151.101.64.223] with 32 bytes of data:
Reply from 151.101.64.223: bytes=32 time=30ms TTL=55
Reply from 151.101.64.223: bytes=32 time=29ms TTL=55
Reply from 151.101.64.223: bytes=32 time=29ms TTL=55
Request timed out.

Ping statistics for 151.101.64.223:
    Packets: Sent = 4, Received = 3, Lost = 1 (25% loss),
Approximate round trip times in milli-seconds:
    Minimum = 29ms, Maximum = 30ms, Average = 29ms

C:\Windows\system32>tracert pypi.python.org

Tracing route to prod.python.map.fastly.net [151.101.64.223]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  192.168.0.1
  2     1 ms    <1 ms    <1 ms  dsldevice.attlocal.net [192.168.1.254]
  3   369 ms    25 ms    24 ms  76-222-216-1.lightspeed.rcsntx.sbcglobal.net [76.222.216.1]
  4    25 ms    26 ms    24 ms  71.155.70.165
  5     *        *        *     Request timed out.
  6    29 ms    27 ms    28 ms  12.83.80.221
  7    28 ms    30 ms    28 ms  gar25.dlstx.ip.att.net [12.122.85.233]
  8    33 ms    26 ms    26 ms  192.205.37.50
  9    27 ms    27 ms    27 ms  ae-1.fastly.dllstx09.us.bb.gin.ntt.net [130.94.195.54]
 10    29 ms    27 ms     *     151.101.64.223
 11    28 ms    28 ms    29 ms  151.101.64.223

Trace complete.

C:\Windows\system32>tracert pypi.python.org

Tracing route to prod.python.map.fastly.net [151.101.48.223]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  192.168.0.1
  2    <1 ms     1 ms    <1 ms  dsldevice.attlocal.net [192.168.1.254]
  3    28 ms    32 ms    24 ms  76-222-216-1.lightspeed.rcsntx.sbcglobal.net [76.222.216.1]
  4    25 ms    26 ms    24 ms  71.155.70.165
  5    26 ms    27 ms     *     70.143.193.66
  6    32 ms    32 ms    30 ms  12.83.80.217
  7    29 ms    29 ms    28 ms  gar25.dlstx.ip.att.net [12.122.85.233]
  8    31 ms    29 ms    28 ms  192.205.36.222
  9    29 ms    26 ms    27 ms  ae-1.fastly.dllstx09.us.bb.gin.ntt.net [130.94.195.54]
 10     *        *       28 ms  151.101.48.223

Trace complete.

**Comment by dstufft** [comment]
It appears you have some hashes inside of a requirments.txt file, and the package file that pip is downloading doesn't match those hashes. Commonly this can mean that the author of the package uploaded additional files from when the requirements.txt file was created that pip prefers over the original files OR that you're running this on a different OS than the requirements.txt was originally created for.

It could also mean that someone is attacking you by replacing files, but that is the unlikely situation.
