### ISSUE TITLE
Gensim 0.13.4 10 times slower

### ISSUE THREAD

**Issue by marabout2015** [pypa/pypi-legacy#669]
Runtimes for the download of Genism 0.13.4 are 10 times slower than that for 0.12.4 or 2.2.0. Is a debug version of that module what's available on pypi?

**Comment by jamadden** [comment]
Thank you for your report, but unfortunately this is the wrong place for it. This tracker is only for issues with the software that runs PyPI itself. We cannot assist with the packages that are simply distributed there. You'll need to contact the package maintainers (I believe there's information about that at http://radimrehurek.com/gensim/support.html).

**Comment by marabout2015** [comment]
Thanks!
