### ISSUE TITLE
msi signature check seems to fail on seemingly valid msi files

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#67]
Originally reported by: **heng (Bitbucket: [heng](https://bitbucket.org/heng), GitHub: [heng](https://github.com/heng))**

---

Uploading an MSI file created by distutils is rejected as an 'invalid distribution file' even though it seems to be installable just fine by windows.

I think it is the magic string comparison is failing and raising the error as noted.

The check is '\xD0\xCF\x11\xE0\xA1\xB1\x1A\xE1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x3E\x00\x03\x00\xFE\xFF\x09\x00\x06'

The MSI file I have has '\xD0\xCF\x11\xE0\xA1\xB1\x1A\xE1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x3E\x00\x04\x00\xFE\xFF\x0C\x00\x06'

The MSI file was created under Windows 7, with several distinct installations of Python (2.7, 3.2, 3.3). I assume the problem is down to an underlying system library, but I'm notably not a windows person.

Attached is one of the problematic msi files.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/67

**Comment by di** [comment]
It seems like this was fixed & deployed, anyone still having this problem should open a new issue at https://github.com/pypa/warehouse/issues.
