### ISSUE TITLE
Upload fails if classifier is tuple rather than list

### ISSUE THREAD

**Issue by gilessbrown** [pypa/pypi-legacy#670]
This did not used to be the case.  
The error message is confusing as it looks like the classifier value is not correct.

**Comment by berkerpeksag** [comment]
Thank you for the report. Could you paste the exact traceback? Did you see it on PyPI or when you run `python setup.py sdist`? I've opened [issue 19610](issue19610) on bugs.p.o for the latter case a while ago.

**Comment by gilessbrown** [comment]
It doesn't happen with just the `python setup.py sdist`, only when I add the `upload`.

There is no traceback just a message:
```
(wextracto) LM-SJC-00874409:wextracto gsbrown$ python setup.py sdist upload
running sdist
running egg_info
writing requirements to Wextracto.egg-info/requires.txt
writing Wextracto.egg-info/PKG-INFO
writing top-level names to Wextracto.egg-info/top_level.txt
writing dependency_links to Wextracto.egg-info/dependency_links.txt
writing entry points to Wextracto.egg-info/entry_points.txt
reading manifest file 'Wextracto.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'Wextracto.egg-info/SOURCES.txt'
running check
creating Wextracto-0.14.0
creating Wextracto-0.14.0/Wextracto.egg-info
creating Wextracto-0.14.0/wex
creating Wextracto-0.14.0/wex/js
copying files to Wextracto-0.14.0...
<lots of "copying ..." lines snipped>
Writing Wextracto-0.14.0/setup.cfg
Creating tar archive
removing 'Wextracto-0.14.0' (and everything under it)
running upload
Submitting dist/Wextracto-0.14.0.tar.gz to https://upload.pypi.org/legacy/
Upload failed (400): classifiers: 'FieldStorage('classifiers', 'Development Status :: 4 - Beta')' is not a valid choice for this field
error: Upload failed (400): classifiers: 'FieldStorage('classifiers', 'Development Status :: 4 - Beta')' is not a valid choice for this field
```

**Comment by berkerpeksag** [comment]
Perhaps there could be a custom validator to convert tuple to list at https://github.com/pypa/warehouse/blob/57f70e977c979f0ca2a2fe640a9362eaf72898af/warehouse/forklift/legacy.py#L338 But I'm not sure if it's worth to do anything to handle tuples (or if there's a better way). It's ultimately up to @dstufft and @ewdurbin.

**Comment by gilessbrown** [comment]
Your answer makes me think I need to be clearer about why I raised this issue.

Personally, I don’t mind using a list instead of a tuple and I managed to work out why after a couple of minutes of fiddling.

However, the way the error is reported does not convey the actual cause of the error (and so is misleading).

Given that this happened on code that had previously worked fine for years then it seems possible that someone else might be affected.

I raised the issue in case someone else might be affected who did not think to try switching the classifier sequence from tuple to list.

I think you’ll admit it isn’t exactly implied by the error message, right?

Giles

**Comment by ewdurbin** [comment]
howdy!

we recently deprecated upload functionality from this codebase and it is now powered by https://github.com/pypa/warehouse and this is likely a regression introduced during that migration. would you mind filing an issue with warehouse?

**Comment by gilessbrown** [comment]
NP
