### ISSUE TITLE
Upload documentation

### ISSUE THREAD

**Issue by khider** [pypa/pypi-legacy#672]
What happened to the upload documentation button that used to be on the PyPi website? How to upload a doc to pythonhosted without using this route?

**Comment by berkerpeksag** [comment]
Thank you for the report. The recommended way to publish your project's documentation is to use [Read the Docs](https://readthedocs.org/). The ultimate plan is to deprecate pythonhosted.org and recommend Read the Docs explicitly (the initial discussion started at [this distutils-sig thread](https://mail.python.org/pipermail/distutils-sig/2015-May/026327.html)) See [this thread on distutils-sig](https://mail.python.org/pipermail/distutils-sig/2015-May/026381.html) for the roadmap. Step 5 (disable documentation uploads to pythonhosted.org) was done as part of https://github.com/pypa/pypi-legacy/commit/1598e6ea0f7fb0393891f6c6bcbf84c191834a0e in last month.
