### ISSUE TITLE
"499 Client Error: Client Disconnected for url: https://upload.pypi.org/legacy/"

### ISSUE THREAD

**Issue by s-m-e** [pypa/pypi-legacy#675]
I filed a [detailed bug against twine](https://github.com/pypa/twine/issues/263) but eventually learned that it also occurs when using _setuptools_ (setup.py ... upload). So it might be an issue in _pypi-legacy_ instead (?). 

**In a nutshell:** I want to upload a (new) package to _pypi_ after having successfully tested it (many times) with _pypitest_ with identical configuration parameters. Uploading of files to _pypi_ fails with HTTP error 499 (with both, _twine_ and _setuptools_). 

My _.pypirc_ file looks like this:
```
[distutils]
index-servers =
  pypi
  pypitest

[pypi]
username=username
password=password

[pypitest]
repository=https://test.pypi.org/legacy/
username=username
password=password
```

I am using Python 3.6.1 on Linux x86_64 with twine (1.9.1), requests (2.18.2), requests-toolbelt (0.8.0), urllib3 (1.22) and setuptools (36.2.2). 

Even without the _repository=..._ parameter in _.pypirc_, twine defaults to _https://upload.pypi.org/legacy/_ when trying to upload to _pypi_. Fun part: The behavior does not change at all if I provide false login credentials like a wrong password. Logging into _pypi_ via the website works for me, however. 

As far as I can tell, HTTP 499 is an error code specific to _nginx_ indicating that the client "just" disconnected. Is this a timeout issue due to server load on _pypi_ or did I misconfigure _.pypirc_ in some sort of way (masquerading a log-in issue for instance) or is this a bug?

I have also tried to follow outdated instructions and attempted to register my files / project first - no change. 

**EDIT (1)**: I hacked _twine_ a bit to get more detailed debugging output by patching the ``_upload`` routine in ``twine/repository.py``. Now it shows me the full server response, i.e. ``resp.text`` / ``resp.content``. Turns out to be interesting. Error 499 is accompanied by an HTML page: 
```
('<!DOCTYPE html>\n'                                                                                                                                  
 '\t<html>\n'
 '\t  <head>\n'
 '\t\t<meta name="viewport" content="width=device-width, initial-scale=1">\n'
 '\t\t<meta charset="utf-8">\n'
 '\t\t<title>Application Error</title>\n'
 '\t\t<style media="screen">\n'
 '\t\t  html,body,iframe {\n'
 '\t\t\tmargin: 0;\n'
 '\t\t\tpadding: 0;\n'
 '\t\t  }\n'
 '\t\t  html,body {\n'
 '\t\t\theight: 100%;\n'
 '\t\t\toverflow: hidden;\n'
 '\t\t  }\n'
 '\t\t  iframe {\n'
 '\t\t\twidth: 100%;\n'
 '\t\t\theight: 100%;\n'
 '\t\t\tborder: 0;\n'
 '\t\t  }\n'
 '\t\t</style>\n'
 '\t  </head>\n'
 '\t  <body>\n'
 '\t\t<iframe '
 'src="//www.herokucdn.com/error-pages/application-error.html"></iframe>\n'
 '\t  </body>\n'
 '\t</html>')
``` 

The page in the iframe says "An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. " ... My _pypi_ username is "smernst", the package I am trying to upload is named "zugbruecke".

**Comment by s-m-e** [comment]
After a lot of tests I learned the following:

* Baseline: My configuration, which **works just fine with _pypitest_**, no matter what.
* On two of my machines, both running _openSUSE Leap_ 42.2, latest patch level, running various versions of _CPython_ 3.4, 3.5 and 3.6, it always fails with HTTP 499. It's not the version of (C)Python. It's not an outdated Python module (I checked them all).
* In a new & clean VM running _Ubuntu_ 17.04 with its default _CPython_ 3.5, it fails with HTTP 499. 
* Getting a new IP from my ISP does not change anything. (In fact having had more than 5 different IPs over 3 days did not change anything.)
* **Re-routing my traffic through _AWS_ (_SOCKS5_ proxy of my own) works** (wtf)

So, as a (hopefully temporary) **workaround** I can only recommend the following:
```
# first shell
ssh -D 8080 some_server_instance_in_aws
# second shell
pip install -vU requests[socks]
export http_proxy=socks5://127.0.0.1:8080 https_proxy=socks5://127.0.0.1:8080
twine upload $filename $filename.asc
```
The first command connects to my _AWS_ instance via _SSH_ and uses it as a _SOCKS_ proxy on port 8080. You can run this in the background, but I prefer to run it in a separate shell so I see what is going on. 
The second command (in a new shell) adds _SOCKS_ support to _requests_. The third one changes the _http_proxy_ environment variable telling programs about the proxy (_twine_ will honor it) and the fourth one just uploads my package as expected. I **only** need to do this for _pypi_, not for _pypitest_.

**Comment by boazmohar** [comment]
Have the same problem. Could not verify that re-routing works ( I don't have a AWS instance).
Would be happy for any other recommendations.
Recreated in Windows, Mac and Unix.
Again a wrong password in `pypirc` has no effect.

**Comment by s-m-e** [comment]
@boazmohar I had a few chats on freenode#pypa (IRC) with pypi people - the authentication happens after the upload. Since the upload fails, wrong login credentials have no effect. From where / what kind of network / ISP are you trying to upload? Seems like this issue is not an isolated case if you're trying to do this from the other side of the Atlantic. My ISP is Germany's T-Online. 

(Maybe you have access to a university computer or proxy you could use for re-routing traffic through it?)

**Comment by boazmohar** [comment]
@s-m-e I can verify that using my phone as a wifi hotspot I can upload to pypi. My institute is HHMI Janelia research campus. I filed a help-desk ticket for them to unblock the traffic. I will report back if that was indeed the cause.

**Comment by k0rmarun** [comment]
Same over here. 
This issue appears on :
- ubuntu 16.04 
- mageia 6
- win 7 
an in the networks of:
- UnityMedia (German ISP)
- Heidelberg University
- Hetzner

Could not verify Amazon trick due to missing instance

**Comment by Faeriol** [comment]
For those of you with this issue... Can you check what version of `requests` you are using? This didn't work for me until I downgraded from `2.18.4` to `2.14.2`.

**Comment by coldfix** [comment]
@s-m-e I have the same issue, from unitymedia network south germany. I can verify that proxying via my vserver as by your description solves the issue!

Possibly any proxy into a different network may solve the issue.

**Comment by coldfix** [comment]
@Faeriol downgrading requests did not work for me.

**Comment by ewdurbin** [comment]
uploads are no longer accepted by the pypi-legacy codebase.

further discussion of this issue should be filed with https://github.com/pypa/warehouse/issues

**Comment by s-m-e** [comment]
@ewdurbin While I appreciate an answer from someone working on PyPI, I'd like to suggest to update the documentation (in a number of places) of how to upload a Python package, where to file bugs (for certain "sub systems" of PyPI) and what the **current** state of affairs is with regards to "pypi-legacy" and "warehouse". I gathered my info with respect to the current upload process and this bug from all sorts of places, including podcasts (interviews) and irc chats. It is by no means obvious to the outside world, which piece of code is actually responsible for accepting uploads to PyPI and where to file bugs. There is a new website, and an old one, there is a new "pre-production" backend, and there is an old one, there are different upload URLs (not) doing different things ... After all, pypi.org still has a warning at its top ("This is a pre-production deployment of Warehouse"). I suggest to replace it with a line telling people that you need help with updating your documentation and link to where interested folks should go first ;)

**Comment by ewdurbin** [comment]
@s-m-e thanks for the wall of text.

**Comment by ewdurbin** [comment]
@s-m-e Trying to break down your larger concerns:
  - Out of date documentation regarding filing of bugs/issues.
    - Yeah, that is definitely an issue that has become particularly bad as warehouse has started to eclipse this codebase. Can you help us by linking to some of the documentation that you feel is out of date?
  - Unclear current state of the pypi-legacy => warehouse migration.
    - Definitely is, likely due to some (perhaps overzealous) hope that we'll be completing the migration "soon".
  - Banner on pypi.org should read as a call for help on documentation.
    - I think that is a bit hyperbolic, but understand the sentiment. We're trying to do a better job with warehouse itself moving forward by including https://pypi.org/help/ and https://packaging.python.org/ which live at https://github.com/pypa/warehouse/blob/master/warehouse/templates/pages/help.html and https://github.com/pypa/python-packaging-user-guide respectively.

Overall, this is no longer to do with the 499 issue and if you'd like to continue to discuss checkout https://github.com/pypa/packaging-problems
