### ISSUE TITLE
upload documentation impossible

### ISSUE THREAD

**Issue by kklmn** [pypa/pypi-legacy#676]
Hello,
In "releases" section, the documentation upload button has gone. One can only destroy docs. Is it a bug or a new feature i.e. closing time of pythonhosted.org?
I would be grateful for fixing or an explicit deprecation statement.
Thanks!

**Comment by jamadden** [comment]
Thanks for the report. Please see #672, among others, for more information about this. (In short this was officially deprecated---a link is in that issue---and please use readthedocs.org for hosting.)

**Comment by kklmn** [comment]
Thank you for the quick reply!
You could have saved some people's nerves by putting this exact statement where the upload button used to live.
