### ISSUE TITLE
Is README.rst feature broken ?

### ISSUE THREAD

**Issue by FabriceSalvaire** [pypa/pypi-legacy#678]
I uploaded a new release of https://pypi.python.org/pypi/PySpice and the README was not converted to HTML on pypi legagy and pypi.org.

**Comment by jamadden** [comment]
Most often that's because of a syntax error in your `long_description`. You can diagnose these with `restview --long --pypi` if you install that package, or `python setup.py check` if you have the `readme` package installed:

```
$ wget https://pypi.python.org/packages/00/be/a819b6c953282ede5015ceaed1144ed32d4ceb6490146791fa036779f45f/PySpice-0.4.0.tar.gz
$ tar -xf PySpice-0.4.0.tar.gz
$ cd PySpice-0.4.0
$ python setup.py check -r
running check
warning: Check: :273: (WARNING/2) Block quote ends without a blank line; unexpected unindent.

warning: Check: Invalid markup which will not be rendered on PyPI.
```
