### ISSUE TITLE
Can't upload to PyPi a package with CeCILL-B license

### ISSUE THREAD

**Issue by scls19fr** [pypa/pypi-legacy#679]
Hello,

I'd like to [upload a package with CeCILL-B license](https://github.com/python-windrose/windrose/issues/65).

Unfortunately, it can be uploaded to Pypi if `setup.py` have the following classifier

    classifiers=[
        # Pick your license as you wish (should match "license" above)
        'License :: CEA CNRS Inria Logiciel Libre License B (CeCILL-B)',
    ],

Many developers are tricking they put 

    license='CeCILL-B',

in `setup` and 

    classifiers=[
        ...
        'License :: OSI Approved :: CEA CNRS Inria Logiciel Libre License, version 2.1 (CeCILL-2.1)',
        ...
    ]

https://www.google.fr/search?q=CeCILL-B+CeCILL-2.1+pypi

https://pypi.python.org/pypi/pythonnest/1.0.2
https://pypkg.com/pypi/updoc/f/setup.py
https://github.com/d9pouces/django-floor
https://github.com/akaszynski/PyACVD

but this way of doing seems incorrect because CeCILL-2.1 and CeCILL-B are 2 differents licenses.

What string should I put in `classifiers` to upload a package with CeCILL-B license ?

I tried many thinks such as 

        'License :: CeCILL-B',

CeCILL-B (being short identifier for such a license https://spdx.org/licenses/CECILL-B.html )

Any identifier from https://spdx.org/licenses/ should be accepted.

Kind regards

**Comment by jamadden** [comment]
You can view the supported list of license classifiers at https://pypi.python.org/pypi?%3Aaction=list_classifiers . In that list, I only see `License :: OSI Approved :: CEA CNRS Inria Logiciel Libre License, version 2.1 (CeCILL-2.1)` from that family.

I will label this as a request for a new classifier, but I can't make any promise about how long that will take.

**Comment by scls19fr** [comment]
Both CeCILL-B and CeCILL-C are missing in https://pypi.python.org/pypi?%3Aaction=list_classifiers despite they are listed in https://spdx.org/licenses/

According https://github.com/openjournals/joss-reviews/issues/268#issuecomment-318530317
I shouldn't put `License :: OSI Approved :: CEA CNRS Inria Logiciel Libre License, version 2.1 (CeCILL-2.1)` if this software should be released with a CeCILL-B license (and that's true because CeCILL-B has the caracteristics of BSD-like licenses but CeCILL-2.1 is compatible with the GNU GPL (so they are very differents licences!)

So what kind of solution should I use in a short timeframe?

No `License` entry in classifiers?

**Comment by jamadden** [comment]
You could simply use the common prefix, which is also independently an accepted classifier `License :: OSI Approved`.

**Comment by scls19fr** [comment]
I'm not sure it will be correct

Only CeCILL License 2.1 (CECILL-2.1) is listed in
https://opensource.org/licenses/alphabetical
and in https://spdx.org/licenses/ OSI Approved? column is not "Y" for "CeCILL-B Free Software License Agreement"

**Comment by jamadden** [comment]
I am not a lawyer and I haven't researched this license, so I was making an assumption. If it's not OSI approved, then I wouldn't use that as a classifier. 

You could simply choose to leave out that classifier data and use text in your `long_description` to state your licensing terms, consistent with your license.

**Comment by ewdurbin** [comment]
`License :: CeCILL-B Free Software License Agreement (CECILL-B)`
and
`License :: CeCILL-C Free Software License Agreement (CECILL-C)`

classifiers added.
