### ISSUE TITLE
pyftpdlib supported POST command has error

### ISSUE THREAD

**Issue by ZJ780313** [pypa/pypi-legacy#680]
Before opening an issue for PyPI, please note the following:
  - This is for the codebase currently running pypi.python.org
  - [Warehouse](https://github.com/pypa/warehouse) is soon to replace this codebase. Some issues may be deferred to the issue tracker for [Warehouse](https://github.com/pypa/warehouse/issues) rather than be addressed here.
  - We do not maintain individual packages installed from PyPI, please seek out the maintainer

**Comment by ZJ780313** [comment]
pyftpdlib has error with supported POST command. connect timeout.

**Comment by jamadden** [comment]
Thank you for your report, but unfortunately this is not the correct place for it. We cannot assist you with software that is only hosted by PyPI.

To get help with [pyftpdlib](https://pypi.python.org/pypi/pyftpdlib) you'll need to contact the maintainers of that software. Its PyPI [information page](https://pypi.python.org/pypi/pyftpdlib) lists at least two ways in which to attempt that (a github page and a mailing list).
