### ISSUE TITLE
pyftpdlib always connect timeout with supported POST command

### ISSUE THREAD

**Issue by ZJ780313** [pypa/pypi-legacy#681]
Before opening an issue for PyPI, please note the following:
  - This is for the codebase currently running pypi.python.org
  - [Warehouse](https://github.com/pypa/warehouse) is soon to replace this codebase. Some issues may be deferred to the issue tracker for [Warehouse](https://github.com/pypa/warehouse/issues) rather than be addressed here.
  - We do not maintain individual packages installed from PyPI, please seek out the maintainer

**Comment by jamadden** [comment]
Thank you for the report, but this appears to be a duplicate of #680. Please contact the maintainers using the links posted there.
