### ISSUE TITLE
Recommended upload method

### ISSUE THREAD

**Issue by lahwaacz** [pypa/pypi-legacy#683]
The [PyPI front page](https://pypi.python.org/pypi) says:

> __Package Authors__
> Submit packages with "python setup.py upload". The index hosts package docs. You may also use the web form. You must register. Testing? Use testpypi.

But following the link to [python setup.py upload](https://packaging.python.org/tutorials/distributing-packages/#uploading-your-project-to-pypi) reveals this warning:

> __Warning:__ In other resources you may encounter references to using python setup.py register and python setup.py upload. These methods of registering and uploading a package are strongly discouraged as it may use a plaintext HTTP or unverified HTTPS connection on some Python versions, allowing your username and password to be intercepted during transmission.

Well, yesterday it made my day :smile: Now it's time to fix that...

**Comment by ewdurbin** [comment]
updated to recommend `twine` as an alternative on the home page.
