### ISSUE TITLE
Stochpy latest package index is 32 instead of 3.2

### ISSUE THREAD

**Issue by margaritakop** [pypa/pypi-legacy#687]
Before opening an issue for PyPI, please note the following:
  - This is for the codebase currently running pypi.python.org
  - [Warehouse](https://github.com/pypa/warehouse) is soon to replace this codebase. Some issues may be deferred to the issue tracker for [Warehouse](https://github.com/pypa/warehouse/issues) rather than be addressed here.
  - We do not maintain individual packages installed from PyPI, please seek out the maintainer

**Comment by jamadden** [comment]
Thanks for the report. It's unclear to me what issue it is you are raising. However, if it is an issue with the `stochpy` package, we cannot help you. "We do not maintain individual packages installed from PyPI, please seek out the maintainer." Please seek out the maintainer of that package for any issues with it.

**Comment by margaritakop** [comment]
Hi Jason,
This is regarding the index of the package when installing with pip. I am
not sure if the bug is on yours or their side. Anyway, I contacted the
maintainers of the stochpy package too.
Best,
Margarita


On 17 Aug 2017 18:52, "Jason Madden" <notifications@github.com> wrote:

Thanks for the report. It's unclear to me what issue it is you are raising.
However, if it is an issue with the stochpy package, we cannot help you.
"We do not maintain individual packages installed from PyPI, please seek
out the maintainer." Please seek out the maintainer of that package for any
issues with it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pypa/pypi-legacy/issues/687#issuecomment-323146048>,
or mute
the thread

**Comment by jamadden** [comment]
Thanks again but this is also not the place to report issues with pip.
