### ISSUE TITLE
seqpy

### ISSUE THREAD

**Issue by febrigunawan48** [pypa/pypi-legacy#692]
Hi, my name is Febri. I want to use seqpy module. Is it already discontinued?

Thank you

**Comment by jamadden** [comment]
Thank you for your report. Unfortunately, this is not the correct place for it; this repository is only for issues with the software that runs pypi.python.org itself. We cannot help with issues for packages just distributed from that source.

That said, unfortunately you may be correct as the github links from https://pypi.python.org/pypi/seqpy are dead. Furthermore that page notes "This software is currently unpublished", so it may never have been available. All I can suggest is searching for it.
