### ISSUE TITLE
Please help me to install cycler / dateutil

### ISSUE THREAD

**Issue by EugeneShin2** [pypa/pypi-legacy#695]
When I download cycler / dateutil and start to install these library,
I got messages like below.

Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 
'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03788C10>: Failed to establish a new Cnnection: [WinError 10051] ~~~ : /simple/six/

Maybe my computer have some block to special network. Do I need any special network connection for installing these libraries?

**Comment by jamadden** [comment]
Thank you for your report! This tracker is just for issues that involve the software that runs `pypy.python.org` itself. It seems unlikely that this is such an issue, but it's hard to say unless you can post a complete traceback. You seem to be running windows; what version of Python and what version of pip are you using? You may get more help posting in the forums dedicated to pip.

**Comment by berkerpeksag** [comment]
Do you have any firewall or antivirus software installed? It may block `python.exe` from making any HTTP request.

**Comment by EugeneShin2** [comment]
Thanks, jamadden, I'm using python 3.6.2 / pip 9.0.1 / setuptools 28.8.0.

**Comment by jamadden** [comment]
Thank you. To follow on from the question @berkerpeksag asked, can you access `https://pypi.python.org/pypi` in a browser? (This still seems unlikely to actually be a pypi issue suitable for this repository, rather, some sort of network or SSL configuration issue.)

**Comment by di** [comment]
Closed due to inactivity.
