### ISSUE TITLE
HTTP 410 on https://pypi.python.org/pypi?:action=submit_form

### ISSUE THREAD

**Issue by kbirkeland** [pypa/pypi-legacy#696]
I want to update the description on my package, but when I try from the pypi.python.org interface, I get a 410 error.  I don't currently see a way to edit this through pypi.org.  Is this behavior expected, and if so, where should I update this data?

Full error response:

`Gone (This API has been deprecated and removed from legacy PyPI in favor of using the APIs available in the new PyPI.org implementation of PyPI (located at https://pypi.org/). For more information about migrating your use of this API to PyPI.org, please see https://packaging.python.org/guides/migrating-to-pypi-org/#uploading. For more information about the sunsetting of this API, please see https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html)`

**Comment by jamadden** [comment]
Yes, unfortunately the error is expected. There is no longer a way to edit the data of existing packages through the web. The only option I am aware of is to upload a new version of the package with updated information. 

I know this is an inconvenience, I’ve struggled with it myself. I don’t really understand the reasons either, but I do apologize.

**Comment by kbirkeland** [comment]
Gotcha.  Do you know any sort of ETA on when that will be available on the new interface?

**Comment by jamadden** [comment]
Unfortunately I do not know of any eta. It’s a volunteer project.

**Comment by jamadden** [comment]
I will go ahead and close this now as it seems theres nothing for pypi legacy to do.

**Comment by kbirkeland** [comment]
I realize it's a volunteer project and it has limited resources, but I'm going to reopen this ticket.  The service is not fully available and it seems that both pypi and pypi-legacy are pointing fingers at each other, according to this issue and pypa/warehouse#2342.  Considering the difference in opinion between the projects, is there a planned solution for this?

**Comment by jamadden** [comment]
Both projects are run by the same people. As I understand it, there is eventually a plan to make pypi.org provide everything that the old service did, but that's clearly not done yet. Opening issues here is probably not going to help pypi.org move forward (what is? I don't know. I can only recommend patience...or code contributions 😄 ).

**Comment by di** [comment]
Please see https://github.com/pypa/warehouse/issues/2170, specifically [this recent comment](https://github.com/pypa/warehouse/issues/2170#issuecomment-326271729).

**Comment by dstufft** [comment]
This issue can stay closed, it's not going to come back in pypi-legacy. If it comes back it will be as part of Warehouse, but you can see the issue @di linked about that.
