### ISSUE TITLE
nagios-cloudwatch-plugin 0.2.6 throws "CLOUDWATCHMETRIC UNKNOWN: AttributeError"

### ISSUE THREAD

**Issue by mayurkadam24** [pypa/pypi-legacy#698]
Hi Team,

I have tried installing the Nagios to Cloudwatch API given on below link:

https://pypi.python.org/pypi/nagios-cloudwatch-plugin/0.2.6

However, while executing the below script to check the output, i get below error:

 ./check_cloudwatch.py -R us-east-2 -n AWS/EC2 -m CPUUtilization -p 600 -d InstanceId=i-0305354ba3f9cd1b1 -w 0:75 -c 0:90
CLOUDWATCHMETRIC UNKNOWN: AttributeError: 'NoneType' object has no attribute 'get_metric_statistics'

I'm using following version of phython boto:
python-boto-2.34.0-6.el6.noarch

The credentials for the AWS cloudwatch access are stored in /etc/boto.cfg file

Can someone please check why this error is thrown ? Appreciate a quick response.

**Comment by jamadden** [comment]
Thank you for your report, but unfortunately this is not the correct place to report it. This tracker is only for issues with the software that runs pypi.python.org itself and we cannot help with issues for the packages that are simply distributed there. Instead, you'll need to check with the maintainers of that software. Based on the Home Page link from the page you linked to, that appears to be https://github.com/FastSociety/nagios-cloudwatch-plugin
