### ISSUE TITLE
xattr fails with error UnicodeDecodeError on Ubuntu 17.04

### ISSUE THREAD

**Issue by naynajain** [pypa/pypi-legacy#699]
Hi
I have recently installed Ubuntu 17.04, and when I ran xattr, it fails with the following error

Traceback (most recent call last):
  File "/usr/local/bin/xattr", line 11, in <module>
    load_entry_point('xattr==0.9.0', 'console_scripts', 'xattr')()
  File "/usr/local/lib/python2.7/dist-packages/xattr-0.9.0-py2.7-linux-x86_64.egg/xattr/tool.py", line 187, in main
    attr_value = attr_value.decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa2 in position 3: invalid start byte

I have tried using Python 2.7 or 3.5, it still fails.
Can someone please help me with how to fix this ?

Thanks & Regards,
    - Nayna

**Comment by berkerpeksag** [comment]
Thank you for the report, but this tracker is for issues with pypi.python.org only. Please report your problem to https://github.com/xattr/xattr (https://github.com/xattr/xattr/issues/36 may be related to your problem)
