### ISSUE TITLE
Request for new trove classifier for Castle CMS

### ISSUE THREAD

**Issue by tkimnguyen** [pypa/pypi-legacy#701]
I work for [Wildcard Corp.](https://wildcardcorp.com), the maintainer of [Castle CMS](https://castlecms.io) ([repo](https://github.com/castlecms/castle.cms)), a GPL2 distribution of [Plone](https://plone.org) ([marketing site](https://plone.com) and [repo](https://github.com/plone/Products.CMFPlone)). 

Could we get two new classifiers, "Framework :: CastleCMS" and "Framework :: CastleCMS :: Theme"? Thank you!

**Comment by jamadden** [comment]
I can’t promise any action, but I can (and did) add a label to help bring this to the attention of the appropriate people. Thanks for your report!

**Comment by ewdurbin** [comment]
Done.

`Framework :: CastleCMS` and `Framework :: CastleCMS :: Theme` added.
