### ISSUE TITLE
Claim package 'lenses'

### ISSUE THREAD

**Issue by ingolemo** [pypa/pypi-legacy#702]
I'm the author of a package called [lenses](https://github.com/ingolemo/python-lenses). I wish to make a release and upload my package to PyPI under that name. However it seems that someone else has already uploaded [a very old commit of my package](https://pypi.python.org/pypi/lenses). The page claims that the package index owner is called `tek`, but I don't know who this is or how to contact them about this issue. Can you guys help contact this person, or give ownership to me, or something?

I have an account on PyPI under the name `ingolemo`.

**Comment by jamadden** [comment]
I wonder if ‘tek’ on pypi is @tek on github. That user has a fork of the repo in question that dates to about the time of pypi publication.

**Comment by tek** [comment]
yes. I'm happy to transfer ownership, just advise how to do it.

**Comment by jamadden** [comment]
It seems to me the first step would be to contact the owner. The GitHub account is not inactive or impossible to contact. Perhaps you should try reasonable means before making an appeal to authority.

**Comment by ingolemo** [comment]
I'm sorry. I don't understand. Who are we supposed to contact? @tek is here and has given their consent. Is there a button they can press to do the transfer or something? I don't have an active package on PyPI so I don't know what that part of the interface looks like.

**Comment by berkerpeksag** [comment]
Hi @ingolemo, @tek can add you to the project by clicking the "roles" link at https://pypi.python.org/pypi/lenses (they need to be logged in to see the link) but you need to give them your PyPI username in order to be added as 'owner' or 'maintainer' on PyPI.

**Comment by tek** [comment]
done.

**Comment by ingolemo** [comment]
Awesome. I want to thank you all for your help, and I apologise for the inconvenience.

**Comment by tek** [comment]
pleasure!
