### ISSUE TITLE
Fix process of reference count during GC

### ISSUE THREAD

**Issue by y-fujisaki2** [pypa/pypi-legacy#703]
When we subtract reference counter of an object, the destructor is automatically called if the value of counter is 0. 
At the same time an error occurs, as the GC executed while the destructor is still in running phase.
To eliminate the error, we have added below program which exclude objects from GC in the destructor in line 4.

static void
Wrapper_dealloc(Wrapper *self)
{
  PyObject_GC_UnTrack((PyObject *)self); //Add this line to eliminate self from GC
  Wrapper_clear(self);
  self->ob_type->tp_free((PyObject*)self);
}

Patch: [ZODB3-3.10.7.zip](https://github.com/pypa/pypi-legacy/files/1291382/ZODB3-3.10.7.zip)

**Comment by jamadden** [comment]
Thank you for your report, but this repository is not the place for it. This is only for issues with the software that runs pypi.python.org itself, not the packages delivered there. You would need to report this to the maintainers of the package with the issue.

**Comment by y-fujisaki2** [comment]
Thank you so much for your confirmation.
If you know, could you tell me. Which URL should I have contributed this report to?
I'd like to know how to access to maintainers of package.

**Comment by jamadden** [comment]
ZODB lives at http://github.com/zopefoundation/ZODB. However, it no longer has any C code (3.10.7 is a very very old version---it seems that most of the patches that have been posted for this issue are against very very old versions and many no longer apply). The C extensions that were split from it are http://github.com/zopefoundation/persistent and http://github.com/zopefoundation/BTrees

**Comment by y-fujisaki2** [comment]
Thank you for your advice! I posted to these community.
