### ISSUE TITLE
Uploaded new version of package to PyPI is not available from pip client

### ISSUE THREAD

**Issue by richpsharp** [pypa/pypi-legacy#704]
I recently uploaded a new version of my project `taskgraph`, but `pip` on my machine only shows the old version available.  However, the website shows the new version.  Specifically:

https://pypi.python.org/pypi/taskgraph is at 0.2.4, the correct release.  But on my console:

```
> pip search taskgraph -v
Starting new HTTPS connection (1): pypi.python.org
"POST /pypi HTTP/1.1" 200 None
taskgraph (0.2.2)  - Parallel task graph framework.
```

I've tried this on other computers and they also only show version 0.2.2.  Is there possibly something I did wrong in uploading the package, or could it be an issue on the PyPI side?

**Comment by richpsharp** [comment]
Also, I spot checked this on a couple of other recent packages I've seen uploaded to PyPI and observe the same behavior.  Such as 0.3.1 of `fishbowl` uploaded a couple of minutes ago of this writing: https://pypi.python.org/pypi/fishbowl/0.3.1

But shows on my console as the older 0.3.0 version:

```
> pip search fishbowl -v
Starting new HTTPS connection (1): pypi.python.org
"POST /pypi HTTP/1.1" 200 None
fishbowl (0.3.0)  - Customizable matplotlib style extension
```

**Comment by jamadden** [comment]
I suspect you are encountering this issue in `pip` itself: https://github.com/pypa/pip/issues/4219 (In a nutshell, pip <= 9.0.1 arbitrarily picks a version to show in the results of 'search'.)

I suspect this because I can verify that 0.2.4 is installed by default:
```
$ pip install taskgraph
Collecting taskgraph
  Downloading taskgraph-0.2.4-py2-none-any.whl
Installing collected packages: taskgraph
Successfully installed taskgraph-0.2.4
```
And it is listed in the index:
```
$ http https://pypi.python.org/simple/taskgraph/
HTTP/1.1 200 OK
Accept-Ranges: bytes
Age: 1032
Cache-Control: max-age=600, public
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 1146
Content-Type: text/html; charset=utf-8
Date: Tue, 19 Sep 2017 20:37:28 GMT
...

<!DOCTYPE html><html><head><title>Links for taskgraph</title></head><body><h1>Links for taskgraph</h1>
...
<a href="../../packages/5d/24/f8c514ee7c75e2b73e4d7ba679fae374a5379dfc8434fc28371a4186e045/taskgraph-0.2.4.tar.gz#md5=46ac09eae093eda04e9eff9b2d44be52" rel="internal">taskgraph-0.2.4.tar.gz</a><br/>
<a href="../../packages/d3/2a/ef09488cbc53f9f6e042ac2b3c9d6ff1cc557bece2a07ad7121c1d6aad49/taskgraph-0.2.4-py2-none-any.whl#md5=1143bee95c5ccc7d03e49c275a1ba6fe" rel="internal">taskgraph-0.2.4-py2-none-any.whl</a><br/>
...
</body></html>
```

**Comment by jamadden** [comment]
Thanks again for this report. I will go ahead and close this as a dup of the mentioned issue. Please feel free to reopen if you don’t believe that’s the case.

**Comment by richpsharp** [comment]
Great, that seems to be the issue.  Thanks for following up!

**Comment by richpsharp** [comment]
Hi, I just ran across this issue again via Google and learned that PyPI also has about a 15 minute cache. I had assumed since a new version showed up on the webpage it would also be available on the `pip` client, but not so. (A friend mentioned he heard about this on "Talk Python to Me"). So just FYI for anyone who runs across this issue.

**Comment by capooti** [comment]
yes I confirm the problem (15 minute cache)

**Comment by ewdurbin** [comment]
Note that the cache being specified is `pip`'s cache. PyPI attempts real time cache invalidation via our CDN.
