### ISSUE TITLE
Built-in functions max bug

### ISSUE THREAD

**Issue by ruancheng77** [pypa/pypi-legacy#711]
```pycon
>>> l = ["4","2","3", "111"]
>>> print(max(l))
得到的结果是：4
```

**Comment by jamadden** [comment]
Thank you for your interest. The string '4' is the correct answer. Strings are sorted lexicographically; numbers of course are sorted by numeric value:
```pycon
>>> l = ["4","2","3", "111"]
>>> sorted(l)
['111', '2', '3', '4']
>>> sorted(l)
[2, 3, 4, 111]
```

However this is not the correct place for this issue. This tracker is only for issues with the software that runs pypi.python.org itself. If you have questions about Python the language and how to use it, you may look at [python-help](https://mail.python.org/mailman/listinfo/python-help), [python-list](https://mail.python.org/mailman/listinfo/python-list), or sites such as stackoverflow.
