### ISSUE TITLE
Issue with PySFTP trying to install Cryptography package

### ISSUE THREAD

**Issue by sineo** [pypa/pypi-legacy#712]
This was working until this morning, when all of a sudden the cryptography module seems missing or broken.

`Collecting cryptography>=1.5 (from paramiko>=1.17->pysftp==0.2.9->-r /opt/python/ondeck/app/requirements.txt (line 40))
Using cached cryptography-2.1.1.tar.gz
Complete output from command python setup.py egg_info:
error in cryptography setup command: Invalid environment marker: platform_python_implementation != 'PyPy'`

**Comment by jamadden** [comment]
Thank you for your report, but this tracker is only for issues with the software that runs pypi.python.org itself. For issues with software packages hosted there, you'll need to contact the maintainers. 

This particular issue [was already reported](https://github.com/pyca/cryptography/issues/3959) to [the maintainers](https://github.com/pyca/cryptography/) of Cryptography. Hopefully the solution there will work for you too.
