### ISSUE TITLE
Links to diveintopyton3.net are broken

### ISSUE THREAD

**Issue by AartGoossens** [pypa/pypi-legacy#713]
The links to documentation about packaging on `https://wiki.python.org/moin/ProjectFileAndDirectoryLayout` are broken. Apparently the content is moved from `diveinto.org/python3` to `diveintopython3.net`. The correct urls are:
- `http://www.diveintopython3.net/packaging.html`
- `http://www.diveintopython3.net`

**Comment by berkerpeksag** [comment]
Thank you for the report. This tracker is for issues with pypi.python.org. I've updated the broken links for now. You can also do it yourself by following the instructions at https://wiki.python.org/moin/FrontPage#use

**Comment by AartGoossens** [comment]
I couldn't find where to file a bug for the website itself and this repo was the closest I could find. Sorry for misplacing the issue and thanks for fixing it anyway.
