### ISSUE TITLE
pyautogui setup.py fails  [error: no commands supplied]

### ISSUE THREAD

**Issue by bobsdavenport** [pypa/pypi-legacy#717]
downloaded pyautogui 
their doesn't appear to be any install instructions  in the readme and the setup.py fails

**Comment by jamadden** [comment]
Thank you for the report. Unfortunately, this is not the correct place for it. This tracker is only for issues with the software that runs pypi.python.org itself. It cannot help with the packages distributed from there. You'll need to seek out the maintainers of `pyautogui`; according to the PyPI page for that project, they can be found at https://github.com/asweigart/pyautogui
