### ISSUE TITLE
pyautogui doubleclick() not working on OSX

### ISSUE THREAD

**Issue by bobsdavenport** [pypa/pypi-legacy#718]
pyautogui.doubleClick() appears ineffective even though item has focus etc.

pyautogui.click(clicks='2', interval=0.5) and alike also ineffective
as above the folder has focus [via pyautoguiclick()]  so would be interested for help in why the function doesn't work on OSX 

unfortunately 

re downloading  newest version of pyautogui  is problematic too
 the  setup.py fails.
presumably i need to copy the files manually [not a good idea]

**Comment by jamadden** [comment]
Thank you for the report. Unfortunately, this is still not the correct place for it. This tracker is only for issues with the software that runs pypi.python.org itself. It cannot help with the packages distributed from there. You'll need to seek out the maintainers of `pyautogui`; according to the PyPI page for that project, they can be found at https://github.com/asweigart/pyautogui

**Comment by bobsdavenport** [comment]
Thanks for the info,
Re listed on their list

I’m sure i'm missing something / searched to no avail, hope they respond as promptly as yourself.

Bob
