### ISSUE TITLE
Recover account 'beorn'

### ISSUE THREAD

**Issue by beorn** [pypa/pypi-legacy#719]
I have been idle on pypi for many years, and when I tried to log into my pypi account 'beorn' I don't have the password nor do I get the recovery email.  The account may have been connected to one of these which I don't have access to: (DELETED)

**Comment by ewdurbin** [comment]
@beorn one of your noted current addresses _is_ already associated with your account, but is not accepting email. please email me at ernest@python.org and we'll work to confirm your account and restore access.

**Comment by beorn** [comment]
@ewdurbin thanks, that set me in the right direction!  I found the culprit (old domain that had lost all the MX's), fixed it, and was able to log in and change my email address.  Thanks! :)
