### ISSUE TITLE
PyPI SSL Cert problem prevents downloads-- cert expired or config problem?

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#72]
Originally reported by: **Chris Lee-Messer (Bitbucket: [cleemesser](https://bitbucket.org/cleemesser), GitHub: [cleemesser](https://github.com/cleemesser))**

----------------------------------------

Using pip (1.4.1) with PyPI today and noted that I get the error 

"there was a problem confirming the ssl certificate <urlopen error [Errno 218603680]"

**Here is the full error message when I try for example, BeautifulSoup**

$ pip install BeautifulSoup
Downloading/unpacking BeautifulSoup
  Could not fetch URL https://pypi.python.org/simple/BeautifulSoup/: There was a problem confirming the ssl certificate: <urlopen error [Errno 218603680] _ssl.c:554: error:0D07A0A0:asn1 encoding routines:ASN1_mbstring_copy:unknown format>
  Will skip URL https://pypi.python.org/simple/BeautifulSoup/ when looking for download links for BeautifulSoup
  Could not fetch URL https://pypi.python.org/simple/: There was a problem confirming the ssl certificate: <urlopen error [Errno 218603680] _ssl.c:554: error:0D07A0A0:asn1 encoding routines:ASN1_mbstring_copy:unknown format>
  Will skip URL https://pypi.python.org/simple/ when looking for download links for BeautifulSoup
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not fetch URL https://pypi.python.org/simple/BeautifulSoup/: There was a problem confirming the ssl certificate: <urlopen error [Errno 218603680] _ssl.c:554: error:0D07A0A0:asn1 encoding routines:ASN1_mbstring_copy:unknown format>
  Will skip URL https://pypi.python.org/simple/BeautifulSoup/ when looking for download links for BeautifulSoup
  Could not find any downloads that satisfy the requirement BeautifulSoup
Cleaning up...
No distributions at all found for BeautifulSoup

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/72

**Comment by ewdurbin** [comment]
PyPI's TLS has been dramatically improved since this issue was initially filed. This issue is resolved.

**Comment by kart12345** [comment]
Downgrade pip.  use command
easy_install pip==1.2.1

**Comment by ewdurbin** [comment]
downgrading pip is almost certainly the wrong answer, if anything i'd recommend upgrading to the latest available version.

**Comment by dstufft** [comment]
Agreed.
