### ISSUE TITLE
pypi mirrors dowwn for 2 days now

### ISSUE THREAD

**Issue by iamit** [pypa/pypi-legacy#721]
The pypi mirrors site is down for 2 days now, not sure where else to report this than on the pypi site. 

link: [https://www.pypi-mirrors.org/](https://www.pypi-mirrors.org/)

Linked from pypi: [https://pypi.python.org/mirrors](https://pypi.python.org/mirrors)

**Comment by iamit** [comment]
I got (different times i tried): 502, 503 and 504 errors for 2 days in a row now.

**Comment by berkerpeksag** [comment]
Thank you for the report, bu we don't maintain pypi-mirrors.org. It seems like the correct place to contact its maintainers is https://github.com/ibigbug/pypi-mirrors (you could probably use their Twitter profile too: https://twitter.com/pypimirrors)
