### ISSUE TITLE
Request for new trove classifier for EUPL 1.2 license

### ISSUE THREAD

**Issue by amotl** [pypa/pypi-legacy#722]
Dear PyPI team,

we are using the EUPL license in one of our projects and we recognized the version 1.2 of this license finally got approved on 18 May 2017 by the corresponding EU commitee.

The list already contains an entry for version 1.1:
`License :: OSI Approved :: European Union Public Licence 1.1 (EUPL 1.1)`

So, could we include the classifier for the new version?
`License :: OSI Approved :: European Union Public Licence 1.2 (EUPL 1.2)`

Thanks in advance!

[1] https://en.wikipedia.org/wiki/European_Union_Public_Licence
[2] https://joinup.ec.europa.eu/page/eupl-text-11-12

**Comment by ewdurbin** [comment]
@amotl I'm unable to confirm that EUPL 1.2 is in the OSI approved list: https://opensource.org/licenses/alphabetical

**Comment by amotl** [comment]
Dear @ewdurbin,

thanks for your quick reply. I see your point. Given this isn't really a priority thing, do you know of any preferred way to ping the OSI about the updated license version?

I can take the job to contact them via https://opensource.org/contact, but there might be better ways already unlocked, e.g. you or one of your colleagues might know someone working for them and already have her email address?

Spoiler: The update to the license version 1.2 is really marginal, they just updated the appendix to reflect the compatibility with newer licenses like the GNU GPLv3 and AGPLv3, as far as i can tell. See also: https://en.wikipedia.org/wiki/European_Union_Public_Licence#Version_1.2

Thanks for your efforts,
Andreas.

**Comment by amotl** [comment]
Hi there,

just wanted to let you know that i submitted an informal request for review of the updated license using their contact form on https://opensource.org/contact.

If this was the wrong way, i will follow up using the guidelines for the formal process as outlined on https://opensource.org/approval.

With kind regards,
Andreas.

**Comment by ewdurbin** [comment]
@amotl thanks! i'm not actually super educated on how licenses end up on the approved list :)

Thanks for doing the research and following through. Let us know when/if the license is approved and we'll add a trove classifier.

**Comment by brainwane** [comment]
@amotl Hi there. [The new PyPI is in beta](https://pyfound.blogspot.com/2018/03/warehouse-all-new-pypi-is-now-in-beta.html) and will launch on Monday, April 16th. I figured now is a good time to ask: has the license been approved?

**Comment by amotl** [comment]
Dear Sumana,

thanks for getting back on this.

> I figured now is a good time to ask: has the license been approved?

As far as i can see, the [list of Trove classifiers for PyPI](https://pypi.python.org/pypi?%3Aaction=list_classifiers) now contains the "EUPL 1.2" license. Nice!

> The new PyPI is in beta and will launch on Monday, April 16th.

This is good news. Good luck to you and all the people of the [Python Packaging Authority](https://www.pypa.io/). You are doing an amazing job, thank you so much!

Oh, and by the way: Thanks for maintaining [Twine](https://twine.readthedocs.io/), we are using it extensively.

With kind regards,
Andreas.
