### ISSUE TITLE
Should appdynamics be hosted on the public opensource mirrors?

### ISSUE THREAD

**Issue by Isszul** [pypa/pypi-legacy#723]
As this is a privately licensed paid-for library why is this hosted on an opensource mirror?

**Comment by jamadden** [comment]
Thank you for your question, but this tracker is only for issues with the software that runs pypi.python.org itself. It has nothing to do with the packages that are hosted there.

You might look for an answer to your question on packaging.python.org, or, failing that, the [distutils-sig mailing list](https://mail.python.org/mailman/listinfo/distutils-sig).

**Comment by Isszul** [comment]
Fair enough. thanks for the pointer, I was at a loss as to whom manages what is hosted.
