### ISSUE TITLE
The google-auth-httplib2 installation command is syntax error.

### ISSUE THREAD

**Issue by thala321** [pypa/pypi-legacy#724]
From this page https://pypi.python.org/pypi/google-auth-httplib2 the installation command is syntax error.
$ pip install google-auth-httlib2
But it should be:
$ pip install google-auth-httplib2

**Comment by jamadden** [comment]
Thank you for your report. Unfortunately, this tracker is just for the software that runs pypi.python.org itself. It cannot help with the packages that are distributed there. You'll need to contact the maintainers of that package. (That same page lists the maintainers as https://github.com/GoogleCloudPlatform/google-auth-library-python but I'm not sure if that's correct or not.)
