### ISSUE TITLE
string index out of range

### ISSUE THREAD

**Issue by nitznazri** [pypa/pypi-legacy#728]
I am getting this particular error while installing MySQL-python-1.2.5 both via pip and building through source code.

The error is as follows ::

File "setup.py", line 17, in <module>
    metadata, options = get_config()

File  MySQL-python-1.2.5/setup_posix.py", line 53, in get_config
    libraries = [ dequote(i[2:]) for i in libs if i.startswith(compiler_flag("l")) ]

File MySQL-python-1.2.5/setup_posix.py", line 8, in dequote
    if s[0] in "\"'" and s[0] == s[-1]:
IndexError: string index out of range

**Comment by berkerpeksag** [comment]
Thank you for the report, but this tracker is for issues with pypi.python.org only. We don't have any control over the packages listed on PyPI. Please report your problem to https://github.com/farcepest/MySQLdb1.
