### ISSUE TITLE
Improve error message "home_page: Invalid URI"

### ISSUE THREAD

**Issue by joernheissler** [pypa/pypi-legacy#732]
I tried to upload a package to pypi for the first time.
The error I got with "python3 setup.py bdist_wheel upload" was

    Upload failed (400): home_page: Invalid URI

And with twine:

    HTTPError: 400 Client Error: home_page: Invalid URI for url: https://upload.pypi.org/legacy/

My first guess was that I must had configured my ~/.pypirc wrong, somehow. And this "legacy" was confusing too, perhaps this API endpoint was removed?

It turned out that I had double quotes in the `url` inside my `setup.cfg`.

Could the error message be improved to say that the problem is in the *package metadata* and perhaps even show the erroneous value?

    HTTPError: 400 Client Error: package metadata: home_page: Invalid URI "%22https://github.com/username/project%22" for url: https://upload.pypi.org/legacy/

**Comment by ewdurbin** [comment]
Hey @joernheissler thanks for the report!

Uploads are all handled by pypa/warehouse now, can you file this issue over at https://github.com/pypa/warehouse/issues.

Sorry for the confusion during this transition.
