### ISSUE TITLE
issue with bcrypt encryption and #(hash character)

### ISSUE THREAD

**Issue by sidnaik03** [pypa/pypi-legacy#733]
package name - bcrypt
The bcrypt.hashpw() method doesn't support **'#'** (hash). Whenever I encrypt string which contain ' # '. Its failed to validate original string with hash string

Ex:
My normal string is 'asdfghj#'
Hash generated by bcrypt.hashpw() = '$2b$12$IhYljX7isircm26.oBdjG.vLSFTzBYpPNBG22CV8889aEHkC.qnCa'

But its failed to validate 'asdfhj#'

But if I replaced the value of '#' with  any other special character , its get validate properly.
Note: I used default salt. (bcrypt.gensalt())

**Comment by jamadden** [comment]
Thank you for your report. Unfortunately this is not the correct place for it. This tracker is only for issues with the software that runs pypi.python.org itself. It cannot help with packages that are distributed there. You'll need to contact the [bcrypt maintainers](https://pypi.python.org/pypi/bcrypt/3.1.4).

FWIW, I cannot produce this issue using bcrypt 3.1.3 using a new salt:
```pycon
In [1]: import bcrypt

In [2]: password = b'asdfghj#'

In [3]: hashed = bcrypt.hashpw(password, bcrypt.gensalt())

In [4]: bcrypt.checkpw(password, hashed)
Out[4]: True
```

I also cannot produce it using the salt you used:
```pycon
In [1]: import bcrypt

In [2]: hashed = b'$2b$12$IhYljX7isircm26.oBdjG.vLSFTzBYpPNBG22CV8889aEHkC.qnCa'

In [3]: password = b'asdfghj#'

In [4]: bcrypt.checkpw(password, hashed)
Out[4]: True
```
