### ISSUE TITLE
exifread supports not panasonic's RW2 files

### ISSUE THREAD

**Issue by wilmarusb** [pypa/pypi-legacy#734]
The panasonic RW2 files begins with 'IIU\x00' and not with 'II*\x00' or 'MM\x00'.
line 30,31,32 of __init__.py in directory exifread are:
30   # determine whether it's a JPEG or TIFF
31    data = f.read(12)
32    if data[0:4] in [b'II*\x00', b'MM\x00*']:
if you change line 32 to:
   if data[0:4] in [b'II*\x00', b'MM\x00*', b'IIU\x00']:
exifread runs also with Panasonic's RW2

**Comment by jamadden** [comment]
Thank you for your report. Unfortunately, this is not the correct place for it. This tracker is only for issues with the software that runs pypi.python.org itself. It cannot help with packages distributed there.  You'll need to contact [exifread's maintainers](https://github.com/ianare/exif-py)
