### ISSUE TITLE
sqlite3 is not supported on python 3.6.0

### ISSUE THREAD

**Issue by Abinayasandhiya** [pypa/pypi-legacy#737]
Hi,

We have installed python-3.6.0 on our RedHat 6 machine.
when we are trying to import sqlite module in python_v36 we could see below issue,

********************************************************************
[root@euca-10-254-72-197 rpmbuild]$ python
Python 3.6.0 (default, Nov 23 2017, 12:46:54)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-18)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python/x86_64/3.6.0-1/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/opt/python/x86_64/3.6.0-1/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
**************************************************************

While installing the python manually we could see below line on installation log

*****************************************************************
Failed to build these modules:
_hashlib              _ssl

Following modules built successfully but were removed because they could not be imported:
_sqlite3
*******************************************************************
It seems to be sqlite is getting broken.

Below sqlite versions are already installed on my machine:
**********************************************************************
[root@euca-10-254-72-197 rpmbuild]$ rpm -qa | grep sqlite
qt-sqlite-4.6.2-28.el6_5.x86_64
sqlite-devel-3.6.20-1.el6_7.2.x86_64
sqlite-3.6.20-1.el6_7.2.x86_64
libdbi-dbd-sqlite-0.8.3-5.1.el6.x86_64
***********************************************************************

Also sqlite3 seems to be working fine without any issue on python2.
Can anyone please help me on this.

Regards,
Abinaya

**Comment by jamadden** [comment]
Thank you for your report, but unfortunately this is not the correct tracker. This tracker is only for issues with the software that runs pypi.python.org itself. You might try python-list.
