### ISSUE TITLE
MD5 hash is not enough to provide security

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#74]
Originally reported by: **anatoly techtonik (Bitbucket: [techtonik](https://bitbucket.org/techtonik), GitHub: [techtonik](https://github.com/techtonik))**

----------------------------------------

MD5 hashes are not safe. They should probably be replaced by 'sha1_size' checksums.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/74

**Comment by wt** [comment]
Would love to see sha256 or some other modern hash being posted along side the md5 data. That way at least the data is available when I am browsing around pypi. Would that be reasonable even if all the tools aren't switched at this time?

**Comment by ewdurbin** [comment]
this will not be addressed in this codebase. you can further lobby for this as a feature on distutils-sig or in the warehouse project.
