### ISSUE TITLE
Can't receive confirmation email

### ISSUE THREAD

**Issue by hubertokf** [pypa/pypi-legacy#743]
I registered at https://pypi.python.org but never received the confirmation email.

I've tried to request a password reset and no email again. Then I tried to create another account with another gmail email and everything went fine.

What am I missing? Maybe i have typed my email incorrectly?

**Comment by ewdurbin** [comment]
@hubertokf can you provide a username or the email address you signed up with?

**Comment by hubertokf** [comment]
Yes! My username is hubertokf and my email is hubertokf@gmail.com

**Comment by ewdurbin** [comment]
@hubertokf looks like there was a clear typo in your email address. It's been resolved and a new confirmation email dispatched.
