### ISSUE TITLE
Request for new trove classifier for Plone 5.2

### ISSUE THREAD

**Issue by tkimnguyen** [pypa/pypi-legacy#746]
We are going to be releasing Plone 5.1 very shortly.  We'd like to be able to mark core packages with 5.2 already, especially when they are not compatible with 5.1 anymore.

On behalf of the Plone Release Team, can we have this new classifier?

`Framework :: Plone :: 5.2`

Thanks!

**Comment by ewdurbin** [comment]
Done!
