### ISSUE TITLE
Cant seem to include valid package as requirement

### ISSUE THREAD

**Issue by Bachmann1234** [pypa/pypi-legacy#747]
When trying to upload a package to pypi using twine I get this error which I assume is coming from the pypi server

"HTTPError: 400 Client Error: requires: Must be a valid Python identifier. for url: https://upload.pypi.org/legacy/"

Its a bit hard to understand but Im looking though my requirements and I do have one that is not a valid identifier "twitter.common.rpc" 

But this package _does_ exist so in theory its valid right? https://pypi.python.org/pypi/twitter.common.rpc/0.3.9

If it helps here is the full setup.py im working with https://github.com/Bachmann1234/thriftcli/tree/pypi

**Comment by Bachmann1234** [comment]
Small context. Im not the original author but work for fitbit who manages the project and am trying to get the package into pypi

**Comment by ewdurbin** [comment]
Hello @Bachmann1234!

Uploads are managed by the pypa/warehouse codebase now, sorry for the confusion.

I'd recommend filing this issue over at https://github.com/pypa/warehouse/issues or https://github.com/pypa/packaging-problems/issues to get assistance.

**Comment by Bachmann1234** [comment]
KK, thanks!
