### ISSUE TITLE
Download link not available

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#75]
Originally reported by: **bhumish (Bitbucket: [bhumish](https://bitbucket.org/bhumish), GitHub: [bhumish](https://github.com/bhumish))**
---

Today I created and uploaded a module named 'simplyhash' on PyPI, but it is not having the Download link. I checked other modules which were uploaded just during the time I uploaded my module, others were having the download link, but my module is not having any link to download the package.
Please let me know if I need to modify anything in the package. The link for the uploaded module is: https://pypi.python.org/pypi/simplyhash/1.0.1
---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/75

**Comment by berkerpeksag** [comment]
Hi @bhumish, can you share which commands did you run? Without seeing them, I'm inclined to think that this isn't an issue with PyPI itself. Please read the guide at https://packaging.python.org/distributing/#uploading-your-project-to-pypi if you haven't yet.
