### ISSUE TITLE
Claim PyFFI package

### ISSUE THREAD

**Issue by psi29a** [pypa/pypi-legacy#750]
We've been trying, without success, to contact Amorlia who is the PyFFI PyPI package maintainer for the past 2 years. Amorilia is a member (missing in action) of Niftools and we hope he is OK. We don't have much in the way of contact information from him however. Would you be able to try to reach him by his registered email address?

We (Niftools) would like to be able to at least to update/upload new packages since the current one is several years old now and we've several releases since then with a major one coming up soon.

I've been able to help other projects to do the same in the past, such as PyPi packages for Ldaptor and for TxMongo where the initial uploader went MIA while development went forward.

Thanks for your help.

Cheers,
Bret

Resources:
Project page: https://github.com/niftools
Amorilia as top contributor: https://github.com/niftools/pyffi/graphs/contributors
The PyPi package: https://pypi.python.org/pypi/PyFFI
Ldaptor maintainer transfer request: https://sourceforge.net/p/pypi/support-requests/386/
SourceForge Request: https://sourceforge.net/p/pypi/support-requests/707/

**Comment by neomonkeus** [comment]
Just adding comment as admin for @niftool org here on github.
Also commented previously on sf.net

**Comment by ewdurbin** [comment]
Indeed, I hope that the user amorilia is OK wherever they are :/

Email ernest@python.org and we'll get a niftool org member on the maintainer list.

**Comment by ewdurbin** [comment]
added owner `neomonkeus` to package `pyffi`

**Comment by neomonkeus** [comment]
Added successfully. 
Thanks @ewdurbin for the support.

**Comment by psi29a** [comment]
Super! Thank you! :)
