### ISSUE TITLE
wrong C++ function parsing when #if directive is used

### ISSUE THREAD

**Issue by bistMania** [pypa/pypi-legacy#751]
If you have code with #if 0 directive the tool is confused

int abc() {
 int xya=0;
 int www=0;
 int xxx;
#if 0
 if(www)
   xxx=1;
 else {
#endif
    xxx=2;
    //}
}

================================================
  NLOC    CCN   token  PARAM  length  location
------------------------------------------------
1 file analyzed.
==============================================================
NLOC    Avg.NLOC  AvgCCN  Avg.token  function_cnt    file
--------------------------------------------------------------
      9       0.0     0.0        0.0         0     ../source/abc

=============================================================================================
No thresholds exceeded (cyclomatic_complexity > 15 or length > 1000 or parameter_count > 100)
==========================================================================================
Total nloc   Avg.NLOC  AvgCCN  Avg.token   Fun Cnt  Warning cnt   Fun Rt   nloc Rt
------------------------------------------------------------------------------------------
         9       0.0     0.0        0.0        1            0      0.00    0.00

**Comment by berkerpeksag** [comment]
Please report your problem to https://github.com/terryyin/lizard This tracker is for issues with pypi.python.org only. Thank you!
