### ISSUE TITLE
Impossible to download a package (problem URL?)

### ISSUE THREAD

**Issue by Tclemento** [pypa/pypi-legacy#752]
Hello,

Relevant page : https://pypi.python.org/pypi/catcli/0.1

When I click on the file "catcli-0.1-py3 # only python3-none-any.whl", I have a 404 error.

I had this during my daily synchronization of PyPI libraries.

Could you solve the problem?

Thanks in advance.

Regards

**Comment by jamadden** [comment]
The package author has [identified the problem](https://github.com/deadc0de6/catcli/commit/c87b324f978dbefb87206ef08fba41eaf216cfa0) and [uploaded a fixed version 0.2](https://pypi.python.org/pypi/catcli/0.2). 

You could ask the author to remove the old broken file.

**Comment by deadc0de6** [comment]
Hello,

I'm the author of catcli and the one who pushed those bad formatted files. I didn't know `setup.cfg` didn't like comments on the same line, I'm sorry. I fixed it in version 0.2 and above and removed the old broken packages, that is 0.1, 0.1.1 and 0.1.2.

Again, I'm sorry for that!

**Comment by Tclemento** [comment]
Thank you for your actions! :)
