### ISSUE TITLE
Tkinter application fullscreen bug on the Mac OSX

### ISSUE THREAD

**Issue by uka-jisc** [pypa/pypi-legacy#758]
Tkinter applications on the Mac doesn't have a true fullscreen mode.

When the zoom button(green) is clicked on a mac osx Tkinter app it has a black background border.

This should not be the case. This also has an impact on the mouse cursor as it goes out of alignment.

Test it out with the python IDE(pre installed with python)

**Comment by jamadden** [comment]
Thank you for your report, but this is not the correct place. This tracker is only for the software that runs pypi.python.org itself.

You might try looking for a similar issue on https://bugs.python.org or asking on the python [mailing list](https://mail.python.org/mailman/listinfo/python-list).
