### ISSUE TITLE
package "gi" causes much trouble

### ISSUE THREAD

**Issue by sigoa** [pypa/pypi-legacy#759]
[https://pypi.python.org/pypi/gi](https://pypi.python.org/pypi/gi)

is probably more trouble than it is worth. For one, it is py2 only, but installs for py3 as well, where it breaks immediately.

Then the name "gi" usually is used by pygtk and should not be used by a next to worthless breaking package like https://pypi.python.org/pypi/gi

having this secondary "fake gi" installed breaks all gtk apps.
This "fake gi" should be removed, since it does no longer exist on github as py source.
If this "fake gi" was deleted, everyone would benefit.

**Comment by jamadden** [comment]
You seem frustrated, and I can understand, but I think that calling the package "fake" and "next to worthless" is a bit of an overstatement. It may cause issues for your particular installation (in which case, don't install it! 😄 ) but it's a package that someone worked on and contributed to the community. It may not do much that you find useful, but it does *something*.

The package's description states that it is a "Command line to private gist. Example: gi.py myFile". From examining the code, that appears to be exactly what it does. Saying that "everyone would benefit" if it was deleted may be an expression of your frustration, but is probably not accurate. 

> For one, it is py2 only, but installs for py3 as well, where it breaks immediately.

That's a common issue for packages on PyPI, not at all unique to this one. Could the metadata for this package be updated to reflect its state better? Sure. But at the time it was published, pip didn't support `requires_python` so there was little motivation to do so. 

> Then the name "gi" usually is used by pygtk

Package name conflicts are a common issue, and not one that (outside of the standard library) PyPI usually has any role in. The solution is to not install conflicting distributions. 🤷‍♂️ 

> This "fake gi" should be removed, since it does no longer exist on github as py source.

It does appear that the original repository has moved, but the owner still exists at https://github.com/inconditus/ Perhaps you could try contacting them through one of their other repos about this package.

**Comment by ewdurbin** [comment]
@jamadden Thank you for your thoughtful response.

@sigoa, Thanks for your feedback! PyPI does not currently and does not plan to implement any policies regarding removal of packages based on their perceived quality. Once [PEP 541](https://www.python.org/dev/peps/pep-0541/) is implemented there will be recourse for abandoned projects, name conflicts, and legal issues.
