### ISSUE TITLE
pypi register page forces insecure 8 char PGP key ID

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#76]
Originally reported by: **Hans-Christoph Steiner (Bitbucket: [eighthave](https://bitbucket.org/eighthave), GitHub: [eighthave](https://github.com/eighthave))**

---

I just signed up for an account on pypi to upload my python projects.  Its a great site, and I've been happy to see pypi start to take security seriously.  I was happy to see that the registration procedure included a spot to put my PGP key ID.  Unfortunately, when I put in my 16 char key ID, it told me that it wasn't supported.  When I put in the last 8 chars, then it worked.

The problem is that 8 char key IDs are easily spoofable.  Ideally, pypi would request at least 16 chars.  It should definitely allow 16 chars, and not force the insecure 8 char standard.

For more on this topic, including how to generate a PGP that matches any 8 char key ID:
http://www.asheesh.org/note/debian/short-key-ids-are-bad-news.html

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/76

**Comment by nitram2342** [comment]
Same here.

**Comment by amarao** [comment]
I've just registered at pypi and I was really troubled by gpg id field. It rejected my gpg id as invalid format without saying anything helpful.

It took me a bit of googling to understand that 32-bits IDs are still in use, and another round of googling to find how to force gpg to show me 'short id' instead of normal one.

**Comment by dstufft** [comment]
It's OK, GPG is basically worthless on PyPI anyways.

**Comment by gene1wood** [comment]
Related support request
* [#378 GPG key ID is invalid](https://sourceforge.net/p/pypi/support-requests/378/)

**Comment by gene1wood** [comment]
[Here's some more context](https://github.com/pypa/twine/issues/157#issuecomment-170512719) for @dstufft 's comment about GPG being worthless on Pypi in pypa/twine#157

**Comment by ewdurbin** [comment]
I'm going to remove GPG key submission from the registration and user form on PyPI Legacy. It only serves to create additional confusion.

We'll continue to display them as they are if a user has them registered, but new registrations have no bother to display the field.

https://github.com/pypa/warehouse/pull/2172 invalidates GPG key additions as a feature of warehouse, and as that is coming up on being real ([no for real though](http://pyfound.blogspot.com/2017/11/the-psf-awarded-moss-grant-pypi.html)), It seems prudent to remove the functionality from PyPI legacy today.
