### ISSUE TITLE
HTTPError: 400 Client Error: This filename has previously been used, you should use a different version

### ISSUE THREAD

**Issue by mhammond** [pypa/pypi-legacy#763]
This is probably my mistake, but to test a new build, I uploaded a .whl file with a pre-release version of pywin32. After testing I removed the version entirely. I then attempted to upload the "real" release, but I can't re-upload a file with the same name as I used to test.

Is there anything I (or you :) can do to allow me to re-upload the new version?

The release is https://pypi.python.org/pypi/pywin32/222
The problematic filename is pywin32-222-cp37-cp37m-win_amd64.whl

**Comment by berkerpeksag** [comment]
Thank you for your report. This is being discussed at https://github.com/pypa/packaging-problems/issues/74. It's not possible to re-upload a file (you may want to try the method described in https://github.com/pypa/packaging-problems/issues/74#issuecomment-137775034, https://github.com/pypa/packaging-problems/issues/74#issuecomment-137775528, and https://github.com/pypa/packaging-problems/issues/74#issuecomment-137776016 but I don't know whether it still works)

By the way, I use Test PyPI to test a release: https://packaging.python.org/guides/using-testpypi/

**Comment by ewdurbin** [comment]
Resources provided by @berkerpeksag are all spot on! Closing as this is not an issue with pypi-legacy codebase (pypa/warehouse is the codebase accepting uploads anyway).

@mhammond one question, we've been working to improve the error messages on upload. did you by chance remember what you saw, and can you help us understand how it could be better clarified the situation that's going on? commenting on https://github.com/pypa/warehouse/issues/2701 would really help :)
