### ISSUE TITLE
Heroku 500 from https://upload.pypi.org/legacy/ via travis deployment

### ISSUE THREAD

**Issue by cjw296** [pypa/pypi-legacy#764]
I released to pypi using Travis' pypi deployment when tags are pushed.

This morning I pushed a tag and the release job failed:

https://travis-ci.org/Mortar/mortar_mixins/jobs/332671108#L653

Indeed, just going to https://upload.pypi.org/legacy/ gives me an error page.

What needs to happen for this to be resolved?

**Comment by cjw296** [comment]
Looks to have been a blip (5-10 mins), leaving this open in case anyone wants to investigate...

**Comment by jamadden** [comment]
Thanks for your report! 

Uploads are no longer handled by this codebase, though. Instead, the [pypa/warehouse](https://github.com/pypa/warehouse) codebase handles the uploads. If you see this again or have more questions, that would be a better forum.
