### ISSUE TITLE
Cannot assign roles

### ISSUE THREAD

**Issue by marmadukeandbob05** [pypa/pypi-legacy#767]
When I click on the 'roles' link, a pop up asks me to sign in. I give it my correct username and password but it just pops up again.

**Comment by di** [comment]
@marmadukeandbob05 Can you try logging in at https://pypi.python.org/pypi?%3Aaction=login_form instead of via the popup?

You can also manage project roles on pypi.org now FYI: https://pypi.org/manage/projects/

**Comment by Comput3rZ** [comment]
Thanks. It works now.
