### ISSUE TITLE
pyev is not available

### ISSUE THREAD

**Issue by davidokeyode** [pypa/pypi-legacy#769]
https://pypi.python.org/pypi/pyev/ is not available

**Comment by di** [comment]
Hi @davidokeyode, it looks like the maintainer has removed this project from PyPI. Sorry, but we don't have any information as to why. If you are able to, you should reach out to them directly.

**Comment by berkerpeksag** [comment]
Looks like pyev 0.9 is archived at https://github.com/kbandla/pyev Closing this issue since there is nothing we can do on our end. Thank you for your report!
