### ISSUE TITLE
Package name exopy not available, but there is no PyPI package for it

### ISSUE THREAD

**Issue by MatthieuDartiailh** [pypa/pypi-legacy#771]
Hi, after going through a painful renaming process of my project (and some related projects) to use a name available on PyPI, testing everything was ok on TestPyPI I was greeted by 
```HTTPError: 403 Client Error: The user 'mdartiailh' is not allowed to upload to project 'exopy'. See https://pypi.org/help#project-name for more information. for url: https://upload.pypi.org/legacy/```
I cannot find such a name used on PyPI, my twine install is up to date and this name is not part of the standard library or particularly malicious, could someone please let me know why I can't use (I don't want to rename my project, all files, Github, etc again)

**Comment by di** [comment]
@MatthieuDartiailh The project `exopy` exists but looks unmaintained: https://pypi.org/project/exopy/

Perhaps you could reach out to the current owner and see if they would transfer the name to you?

**Comment by MatthieuDartiailh** [comment]
Will try. It is annoying that pypi.python.org did not found this package, I could have avoided this whole issue. Thanks @di

**Comment by di** [comment]
The search on legacy-pypi is not great, I'd recommend using pypi.org instead: https://pypi.org/search/?q=exopy

**Comment by MatthieuDartiailh** [comment]
Yeah I noticed but too late. I contacted @ryanvarley the listed maintainer hopefully, he will answer.

**Comment by ryanvarley** [comment]
I have it, I just transferred ownership to you

**Comment by MatthieuDartiailh** [comment]
Thanks again !
