### ISSUE TITLE
Create banner on homepage linking to Warehouse testers' landing page

### ISSUE THREAD

**Issue by lgh2** [pypa/pypi-legacy#772]
As part of the effort to promote Warehouse to maintainers who would like to test it, we would like to add a banner to the homepage of pypi-legacy, directing maintainers to the testers' landing page: https://wiki.python.org/psf/WarehousePackageMaintainerTesting

This banner will probably be added at some point after we have reached the [Maintainer MVP milestone](https://github.com/pypa/warehouse/milestone/8).  The specific implementation details will be determined and it may be only visible to a subset of users. 

It would also be nice to have a "Warehouse transition" tag in the issue tracker for this site, so we can organize and triage issues related to the transition from pypi-legacy to Warehouse.

**Comment by brainwane** [comment]
@nlhkabu I imagine that you'd be the one who'd create this banner :) so, heads-up.

**Comment by di** [comment]
Heh, I think @ewdurbin or I could spare @nlhkabu from having to dive into the pypi-legacy codebase... it's not as nice to work with as Warehouse.

**Comment by brainwane** [comment]
Let's go ahead and implement this, visible only to logged-in users. It could point to https://pyfound.blogspot.com/2018/02/python-package-maintainers-help-test.html which is formatted a little more nicely, or to https://wiki.python.org/psf/WarehousePackageMaintainerTesting which is easier to update -- leaving that up to y'all. :)

**Comment by brainwane** [comment]
Ernest is working on this today.

**Comment by ewdurbin** [comment]
Done. Hope you like `color: darkviolet;`
