### ISSUE TITLE
Different results when getting the gzipped vs non-gzipped version of the index for boto3

### ISSUE THREAD

**Issue by mpoindexter** [pypa/pypi-legacy#773]
Boto3 version 1.5.29 does not appear in the index if requesting the index with a client that supports gzip encoding vs non-gzip encoding.

Compressed request trace: https://pastebin.com/01GMAzQt
Non-compressed request trace: https://pastebin.com/QD80ZDZH

**Comment by mpoindexter** [comment]
A colleague sees different results on a different machine...it seems like perhaps the CDN caches have different versions of this file out there?

**Comment by ewdurbin** [comment]
@mpoindexter thanks for your report! we're investigating what's up, but your intuition seems valid. I'm double checking a couple settings in our CDN configuration to see how they interact with `Accept` headers.

**Comment by ewdurbin** [comment]
I've confirmed this is not global.

It appears that our CDN provider had an open incident during the time that the PURGE issued for that release was submitted. Nothing the difference in `Age` header for your responses shows that this overlapped with the incident (incident was ongoing ~80000-60000 seconds ago, `Age` headers are in that realm.

We have relatively aggressive caching, and incidents like this would generally resolve after some time as things expire manually.

A purge has been issued which should clear things up, sorry for the trouble and thanks for the report.
