### ISSUE TITLE
Spam packages by user lonatomlin

### ISSUE THREAD

**Issue by meichthys** [pypa/pypi-legacy#774]
Today lots of 'hack' spamp packages were added by user lonatomlin:
examples:
https://pypi.python.org/pypi/paypal-money-adder
https://pypi.python.org/pypi/credit-card-generator
https://pypi.python.org/pypi/Cooking-Fever-Hack-Updated-2018

many others.. 
Can we get these removed?

**Comment by ewdurbin** [comment]
we're aware of spam and are working to put protections in place on the upload and registration apis.

once we have our preventative measures in place, we'll work on cleanup.

**Comment by berkerpeksag** [comment]
Another report about spam packages: https://github.com/python/pythondotorg/issues/1225

Username: demidezucu
Project: https://pypi.python.org/pypi/clash-royale-hack-new-unlimited-gems-gold-hack-2018

**Comment by di** [comment]
Thanks @berkerpeksag, these have been removed.

**Comment by meichthys** [comment]
This issue can be closed.

**Comment by meichthys** [comment]
^ @di
