### ISSUE TITLE
HTTPError: 400 client Error: user 'x' has no verified email addresses while pushing python package

### ISSUE THREAD

**Issue by ydineshy225** [pypa/pypi-legacy#776]
HTTPError: 400 Client Error: User 'sampleuser' has no verified email addresse
s, please verify at least one address before registering a new project on PyPI.
See https://pypi.org/help/#verified-email for more information. for url: https:/
/upload.pypi.org/legacy/

Above is the error I am getting when I run **twine upload dist/***

**Comment by ydineshy225** [comment]
@di, I did verify my email at the time of account creation in PyPi, but some how it says not verified. I logged in again and clicked on verify email option, it worked.

Actually I did the same immediately after raising issue, but forgot to comment here. BTW thanks for the response.

**Comment by rdhyee** [comment]
Even though I verified my email address at pypi.org, I get `User 'rdhyee' has no verified email addresses`, when I try to upload to the https://test.pypi.org/legacy/.  Is there a separate procedure for verifying my email address on the test PyPI repo?

**Comment by di** [comment]
@rdhyee Yes, `pypi.org` and `test.pypi.org` are completely separate. You will need to visit https://test.pypi.org/manage/account/ to resend your verification email.

**Comment by rdhyee** [comment]
@di Thank you for telling me about https://test.pypi.org/manage/account/ -- that did the trick for me.

**Comment by shinalone** [comment]
Hello @di ,
        After read above, I attempted to login in [https://test.pypi.org/manage/account/ ](https://test.pypi.org/manage/account) failed, it told me that my username does not exist, register then raise 'acptcha error', But I can login [https://pypi.org](https://pypi.org) and [https://pypi.python.org/pypi](https://pypi.python.org/pypi), and I don't want to change my account to register new account. So, please read next, help me.

- ***Question:***
        On 2017/10/09, I had already confirmed link in Email, and uploaded 3 modules. But now I can't upload modules, because in [new pypi page](https://pypi.org/manage/account/) I crazily click 'send verifaction-Email' more times, I have not received any emails about pypi untill today.

```
#twine upload dist/*
HTTPError: 400 Client Error: User 'UlionTse' has no verified email addresses, please verify 
at least one address before registering a new project on PyPI. See https://pypi.org/help/#
verified-email for more information. for url: https://upload.pypi.org/legacy/
```

- ***Maybe:***
        I ensure it's not about network, and I looked for spam of my Email. 
        Maybe it causes that old account changed to new account, or pure question of 'send Email', or Manual review, or database, or about [outlook](https://outlook.live.com/)?

***[PLEASE HELP, THANKS!]()***
-------------------------------------------------------------------------
- ***Some Pictures:***

![](https://i.imgur.com/biLgEhS.png)
-------------------------------------------------------------------------
![](https://i.imgur.com/l9blRXj.png)
-------------------------------------------------------------------------
![](https://i.imgur.com/qfwB3Jg.png)
-------------------------------------------------------------------------

***[PLEASE HELP, THANKS!]()***

**Comment by jamadden** [comment]
@shinalone testpypi and pypi are not the same. You must create a separate account to on testpypi. See https://packaging.python.org/guides/using-testpypi/

**Comment by shinalone** [comment]
@jamadden I raise 'ReCaptcha Error', but I don't see  CAPTCHA in China. See below,

![](https://i.imgur.com/sc5c3Kp.png)
![](https://i.imgur.com/wBaUpFL.png)

**Comment by jamadden** [comment]
@shinalone this form is managed by warehouse. If you have issues with it, please raise them on that tracker.

**Comment by shinalone** [comment]
@jamadden ok...

**Comment by ewdurbin** [comment]
tracking in https://github.com/pypa/warehouse/issues/3174

**Comment by mouday** [comment]
veriry your email reference: 
https://blog.csdn.net/mouday/article/details/79875119
