### ISSUE TITLE
Password reset feature currently not sending email?

### ISSUE THREAD

**Issue by kura** [pypa/pypi-legacy#777]
I tried the lost password feature on legacy and warehouse but neither has sent me a new password. Can't get in to my account.

**Comment by ewdurbin** [comment]
@kura what is the account name on PyPI?

**Comment by kura** [comment]
It's kura. The email address should be a gmail.com one.

**Comment by di** [comment]
Hi @kura, that account actually has an email at your `@kura.io` domain, does that sound familiar?

**Comment by kura** [comment]
It does. Is there any way you can change it? If you check the account you'll see a couple of packages like blackhole, which you can also find on this GitHub account. Also there is a PGP signature in use that I can verify with you guys if needed.

**Comment by di** [comment]
@kura Can you send a signed email to me at `di@di.codes` from the new email you'd like added?

**Comment by kura** [comment]
@di on it now.

**Comment by kura** [comment]
@di you should have my email now.

**Comment by 3mp3ri0r** [comment]
Hi @di. I've also account that I forgot the password. I ask password reset but no email from pypi. My Pypi account name is "rekeninghub", the email I forgot about this two: christo@rekeninghub.com or developer@rekeninghub.com. Please resend the link or give another solution. Thank you.

**Comment by ewdurbin** [comment]
@3mp3ri0r errors on our mail service: ```Retry limit reached. Dropped: admin@mail.pypi.org → developer@rekeningub.com 'PyPI Password Reset Request' No MX for rekeningub.com Server response: 498 No MX for rekeningub.com```

It seems that there was a typo, email address has been updated for the user. In the future please open a separate issue.
