### ISSUE TITLE
Version bump: apache-libcloud

### ISSUE THREAD

**Issue by r1chy** [pypa/pypi-legacy#778]
Hi,

we noticed that apache/libcloud bumped version to 2.3.0.

Is it possible to add the new version to "PyPI - the Python Package Index". 
We would like to see the latest version, because it should support shared vpc's in google cloud platform.

Best regards

**Comment by jamadden** [comment]
Thank you for your interest in PyPI.

This tracker is just for issues with the software that runs pypi.python.org itself. It cannot help with issues for the packages hosted there. To get a new version of a package released, you'll need to contact the maintainers of that package. This information is often (although not always) found on the PyPI page for the project, or in the source code of the project.
