### ISSUE TITLE
Remove autofocus from pypi's search box.

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#78]
Originally reported by: **Florian Apolloner (Bitbucket: [apollo13](https://bitbucket.org/apollo13), GitHub: [apollo13](https://github.com/apollo13))**

---

Please remove the autofocus for the search box from pypi again. The issue is as follows:
- Go to a package site
- Hit your "end" button on the keyboard
- Expect your browser to go to the end of the page, nothing happens

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/78

**Comment by di** [comment]
This is WONTFIX for pypi-legacy, but fixed on `pypi.org`.

**Comment by brainwane** [comment]
@apollo13 You may wish to comment at https://github.com/pypa/warehouse/issues/3440 .
