### ISSUE TITLE
errror about pygal_maps_world-1.0.2

### ISSUE THREAD

**Issue by Darren-2018** [pypa/pypi-legacy#781]
Hello,
    When I learn to code the world maps, I found Taiwai isn't in china in '' pygal_maps_world-1.0.2 '' that  I download at 'https://pypi.python.org/pypi/pygal_maps_world/1.0.2' .
    Could you help me to change it ? Actually，Taiwan is part of china. thanks for you can help me do that,
[pygal_maps_world-1.0.2.tar.gz](https://github.com/pypa/pypi-legacy/files/1787668/pygal_maps_world-1.0.2.tar.gz)

**Comment by jamadden** [comment]
Thank you for your report. Unfortunately this is not the correct place for it. This tracker is only for issues with the software that runs pypi.python.org itself. It cannot help with the packages distributed there. You’ll need to contact the package maintainers.
