### ISSUE TITLE
pip-compile fails for matplotlib-2.2.2

### ISSUE THREAD

**Issue by otacky-taka** [pypa/pypi-legacy#786]
Since `matplotlib` was updated from 2.2.0 to 2.2.2, `pip-compile` fails reporting error about `subprocess32.`

* this is the case for virtual env made with `python3.5 -m venv xxx` (on Ubuntu-16.04) and `python3.6 -m venv xxx` (on macOS-10-13-2)
* no problem when the version of matplotlib is fixed to 2.2.0 (`matplotlib==2.2.0` in `requirements.in`)
* after having 2.2.0 installed, 'pip install --upgrade matplotlib` works fine, and it installs `matplotlib-2.2.2` properly.

**Comment by jamadden** [comment]
Thank you for your report. Unfortunately, this is not the place for it. This tracker is only for issues with the software that runs pypi.python.org itself. It cannot help with packages installed from there.

You'll need to open an issue with the source of the problem, probably either [pip-tools](https://github.com/jazzband/pip-tools/) or [matplotlib](https://github.com/matplotlib/matplotlib)
