### ISSUE TITLE
googlefinance.get  is linking the wrong files

### ISSUE THREAD

**Issue by YongBeomKim** [pypa/pypi-legacy#788]
hello...

first of the time. I build the module the name is 
'googlefinance-get' 
but, not satisfied the '-', 
so I deleted the old one, 
and building the New name of 'googlefinance.get'...

and updated the source..
and Page is changed 
https://pypi.python.org/pypi?name=googlefinance.get&version=0.4.1&:action=display

But, whenever I installed the 
"$ pip install googlefinance.get"
set the module is  always olded 'googlefinance-get' 
not the New 'googlefinance.get'

https://pypi.org/project/googlefinance.get/#history
is only left the New module,

Whenever  press the "$ pip install googlefinance.get",
always following the old solder, his name is  'googlefinance-get'  not ".get"

please fix this links...
and have a nice day..

**Comment by jamadden** [comment]
pip normalizes the name before requesting the index:
```
$ pip install -v googlefinance.get
Collecting googlefinance.get
  1 location(s) to search for versions of googlefinance.get:
  * https://pypi.python.org/simple/googlefinance-get/
  Getting page https://pypi.python.org/simple/googlefinance-get/
  Looking up "https://pypi.python.org/simple/googlefinance-get/" in the cache
  Current age based on date: 124
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 124
  Analyzing links from page https://pypi.python.org/simple/googlefinance-get/
    Found link https://pypi.python.org/packages/04/a9/2a7d15704ebee313dfc6ff6ed1c68ee5589abfceeb9504d30c93af37e501/googlefinance_get-0.3-py2.py3-none-any.whl#md5=e066eda6e9bf01a2bd205f4d493a5768 (from https://pypi.python.org/simple/googlefinance-get/), version: 0.3
```

It appears to normalize it differently than this legacy code base does. 

Warehouse, on the other hand, normalizes in the same way:
```
$ pip install -v googlefinance.get --index https://pypi.org/simple/
Collecting googlefinance.get
  1 location(s) to search for versions of googlefinance.get:
  * https://pypi.org/simple/googlefinance-get/
  Getting page https://pypi.org/simple/googlefinance-get/
  Looking up "https://pypi.org/simple/googlefinance-get/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.org
  https://pypi.org:443 "GET /simple/googlefinance-get/ HTTP/1.1" 200 309
  Updating cache with response from "https://pypi.org/simple/googlefinance-get/"
  Caching due to etag
  Analyzing links from page https://pypi.org/simple/googlefinance-get/
    Found link https://files.pythonhosted.org/packages/2f/83/d081dea9f6475199a6492bf66f2e6bd58ecb2fd18ff3cc14529e0612df5e/googlefinance.get-0.4.1-py3-none-any.whl#sha256=420481066070b15ece1b31f71dd0db88f3d14da104fc157ac8c1e359283d4d55 (from https://pypi.org/simple/googlefinance-get/), version: 0.4.1
  Using version 0.4.1 (newest of versions: 0.4.1)
```

Perhaps you can use '--index https://pypi.org/simple/' for the time being.

**Comment by YongBeomKim** [comment]
anyway... Thanks to everyone..

Now it works Correctly ... ^^;;;
I think (maybe)  the Warehouse's Database (or something) is migrated  
Not  by immediately..
But by few hours (or by day).

**Comment by ewdurbin** [comment]
the issue is likely that uploads must trigger purges for pypi.org and pypi.python.org. pypi.org purges are retried, while the purges for pypi.python.org "trust" the legacy system to execute them directly.

this won't be as fragile once pypi.org rollout is completed (in the coming weeks).
