### ISSUE TITLE
Recover account for JoabeMendes (Change email)

### ISSUE THREAD

**Issue by JoabMendes** [pypa/pypi-legacy#792]
I lost access to the recover account email address for `JoabeMendes` user on pypi.

Please could I have the email addressed changed to: 
```
joabe.mdl@gmail.com
```

I have a new release for a [package](https://github.com/JoabMendes/fbbotw) I have maintained for a while but can't upload it since I can't access my account. I also sent an email to @ewdurbin addressing this issue.

**Comment by di** [comment]
Done, let us know if you're having any other issues.

**Comment by JoabMendes** [comment]
I just recovered it, thanks for being so fast @di 🚀
Please @ewdurbin, ignore the email I sent you.

Have a good one!
