### ISSUE TITLE
Request for new trove classifier for Eclipse Public License 2.0 (EPL 2.0)

### ISSUE THREAD

**Issue by amotl** [pypa/pypi-legacy#794]
Dear PyPI team,

i am following up on #722, thanks @brainwane for bringing this up again.

The fine [mqttwarn project](https://github.com/jpmens/mqttwarn) is using the Eclipse Public License 1.0 [1] and is probably about to update this to the version 2.0 [2] of the same license. However, the [list of Trove classifiers for PyPI](https://pypi.python.org/pypi?%3Aaction=list_classifiers) does not include the updated version yet.

The list already contains an entry for version 1.0:
`License :: OSI Approved :: Eclipse Public License 1.0 (EPL-1.0)`

So, could we include the classifier for the new version?
`License :: OSI Approved :: Eclipse Public License 2.0 (EPL-2.0)`

Thanks in advance and keep up the good work on PyPI!

[1] https://www.eclipse.org/org/documents/epl-v10.php
[2] https://www.eclipse.org/legal/epl-2.0/

**Comment by brainwane** [comment]
@amotl I'm going to refile this on the new PyPI issue tracker using https://github.com/pypa/warehouse/issues/new?title=Request+trove+classifier&template=new-trove-classifier.md . Thanks!

**Comment by amotl** [comment]
@brainwane: Thank you so much!
