### ISSUE TITLE
Unable to upload package using twine

### ISSUE THREAD

**Issue by sr-murthy** [pypa/pypi-legacy#795]
I'm a co-author of the oasislmf package, but I'm unable to upload a new version of this. I normally use `twine`. I'm getting the following error message

    HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/

I have checked that my login credentials in the `.pypirc` file are correct, and this is the first time I've had problems in publishing the package.

**Comment by jamadden** [comment]
Uploads are now handled by the [pypa/warehouse](https://github.com/pypa/warehouse/issues/new) project. You might try moving this issue there.

It would be helpful to know your version of twine, your version of Python, and your operating system.

**Comment by sr-murthy** [comment]
Thanks, I'll repost the original issue there, together with the information you requested.
