### ISSUE TITLE
Claim package 'dtrx'

### ISSUE THREAD

**Issue by ChrisJefferson** [pypa/pypi-legacy#801]
The package 'dtrx' provides a simple way of uncompressing a large number of compression formats, and deals with the common problems of spewing files in the current directory.

The package is still useful, but it has not been updated since 2011, so it required --allow-external.

I have tried emailing the author, Brett Smith, ( @brettcs ), but he seems unresponsive.

While I could add a new package with a different name, dtrx is mentioned in many webpages, and I know many people who use the existing name.

**Comment by jamadden** [comment]
Thanks for the report, but unfortunately this is no longer the correct place for it. This tracker isn't monitored by the PyPI admins anymore since https://github.com/pypa/warehouse has replaced it. If you can open this issue on that tracker, I'll tag it for attention.
