### ISSUE TITLE
PyPI serving broken file

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#81]
Originally reported by: **Dimitar Dimitrov (Bitbucket: [mitakas](https://bitbucket.org/mitakas), GitHub: [mitakas](https://github.com/mitakas))**

----------------------------------------

I am trying to install [Products.CustomOverrides](https://pypi.python.org/pypi/Products.CustomOverrides/1.0.3) in Plone, but keep getting the error

```
#!bash

error: Couldn't find a setup script in /tmp/tmpOciXvrget_dist/Products.CustomOverrides-1.0.3.zip
```

Using pdb I then stopped setuptools and tried to unzip the downloaded file manually

```
#!bash
user@server:/tmp/tmpGJp9KQget_dist# unzip Products.CustomOverrides-1.0.3.zip 
Archive:  Products.CustomOverrides-1.0.3.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of Products.CustomOverrides-1.0.3.zip or
        Products.CustomOverrides-1.0.3.zip.zip, and cannot find Products.CustomOverrides-1.0.3.zip.ZIP, period.
user@server:/tmp/tmpGJp9KQget_dist# file Products.CustomOverrides-1.0.3.zip 
Products.CustomOverrides-1.0.3.zip: empty
```

I can, on the other hand, unzip the file, wenn I download it manually from the site.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/81

**Comment by berkerpeksag** [comment]
I think this was caused by a transient error. 1.0.3 is still the latest release of Products.CustomOverrides and I have managed to install it successfully.
