### ISSUE TITLE
Add SSH key PROBLEM  @  "https://pypi.python.org/pypi?%3Aaction=user_form"

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#82]
Originally reported by: **David Kim (Bitbucket: [djkim54143](https://bitbucket.org/djkim54143), GitHub: Unknown)**

---

When I tried to add an SSH key in the 'User profile' form, it sends me to:

https://pypi.python.org/pypi

However, the screen is blank (white color).  When I attempt to refresh the page, I am notified:

Confirm Form Resubmission

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/82

**Comment by berkerpeksag** [comment]
Thank you for the report. "Add SSK key" feature has been removed in https://github.com/pypa/pypi-legacy/commit/e8bdb69d438f197040061d865a53c221d54dc707.
