### ISSUE TITLE
Update nose2-cov owner request, because current maintenair is away since 2013-03

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#84]
Originally reported by: **Stéphane Klein (Bitbucket: [harobed](https://bitbucket.org/harobed), GitHub: [harobed](https://github.com/harobed))**

---

Hi,

I would like get write access on "nose2-cov" package on pypi :https://pypi.python.org/pypi/nose2-cov/1.0a4

My username is : "harobed"

Why this request : because I've did this pull request https://bitbucket.org/memedough/nose2-cov/pull-request/2/improve-readme-append-how-to-enable-nose2/diff

I've no answer from author since 2013-03-24.

I've send bitbucket direct message, I send directly one email at memedough@gmail.com (2013-08-30), no answer :(

So, I would like get write access to this package on pypi.

Best regards,
Stephane

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/84

**Comment by jamadden** [comment]
Coverage support is now included [directly in  nose2](http://nose2.readthedocs.io/en/latest/plugins/coverage.html) (making nose2-cov obsolete) and it appears that the original author of the mentioned PR and this issue [is aware of this](https://bitbucket.org/memedough/nose2-cov/pull-requests/2/improve-readme-append-how-to-enable-nose2/diff#comment-1923026). 

So I believe we can close this issue.
