### ISSUE TITLE
relation "accounts_user" does not exist

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#87]
Originally reported by: **Igor V Churmeev (Bitbucket: [ingvarch](https://bitbucket.org/ingvarch), GitHub: [ingvarch](https://github.com/ingvarch))**

----------------------------------------

Hi!

hg pull && hg update-r default

$ (Venv) pip install-r requirements.txt

$ Python pip.wsgi

Everything works, but when I start to create a user leaves a message

```
#!shell


Error ...

Internal Server Error

Traceback (most recent call last):
   File "webui.py", line 326, in run
     self.inner_run ()
   File "webui.py", line 669, in inner_run
     getattr (self, action) ()
   File "webui.py", line 2885, in user
     if self.store.has_user (name):
   File "store.py", line 1508, in has_user
     safe_execute (cursor, sql, (name,))
   File "store.py", line 227, in safe_execute
     return cursor.execute (sql, safe_params)
ProgrammingError: relation "accounts_user" does not exist
LINE 1: select count (*) from accounts_user where username = 'myuser'
```

Nowhere in the files do not have to create a table 'accounts_user'

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/87

**Comment by berkerpeksag** [comment]
I was able to import the database schema successfully last week so I think we can close this now.
