### ISSUE TITLE
__getitem__ send limit(-1)

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#89]
Originally reported by: **xbsura (Bitbucket: [xbsura](https://bitbucket.org/xbsura), GitHub: [xbsura](https://github.com/xbsura))**

----------------------------------------

db.collection.find().limit(-1) and db.collection.find().limit(1) is 
equivalent in mongo 2.4.7,but our mongo being used is 2.2.*.We found that sometimes limit(-1) is different with limit(1) when querying.

in pymongo,the function __getitem__ send a limit of -1 when getting one document:

```
#!python

if isinstance(index, (int, long)):
            if index < 0:
                raise IndexError("Cursor instances do not support negative"
                                 "indices")
            clone = self.clone()
            clone.skip(index + self.__skip)
            clone.limit(-1)  # use a hard limit
            for doc in clone:
                return doc
            raise IndexError("no such item for Cursor instance")
        raise TypeError("index %r cannot be applied to Cursor "
                        "instances" % index)
```
In large skip,mongo return null,which is expected to return one document.
After changing limit(-1) to limit(1),we got correct result.
I consider limit(-1) is a bug,or does it exist something i did not realized?

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/89

**Comment by berkerpeksag** [comment]
Please use pymongo issue tracker to report your problem.
