### ISSUE TITLE
Missing ipv6 connectivity

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#90]
Originally reported by: **gasimed (Bitbucket: [gasimed](https://bitbucket.org/gasimed), GitHub: Unknown)**

----------------------------------------

pypi.python.org is missing ipv6 connectivity, which make pip unusable for ipv6-only hosts. 
While getting ipv6 connectivity should have the highest priority to fix this problem, ipv6 mirrors could be published on 
https://pypi.python.org/mirrors
as a workaround. At least the missing ipv6 mirrors should be documentated on this site.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/90

**Comment by tiaz** [comment]
As IPv4 addresses become more contested, this is starting to become a problem for my use - I now have to build environments on ipv4-connected hosts and ship them to ipv6 ones, or maintain an RFC1918 network. Is there any progress on the CDN end?

**Comment by ewdurbin** [comment]
Fastly just announced Beta HTTP/2 and IPv6 today, we will follow up for
details on timeline and our candidacy to test the features.


From: tiaz <notifications@github.com> <notifications@github.com>
Reply: pypa/pypi-legacy
<reply@reply.github.com>
<reply@reply.github.com>
Date: July 7, 2016 at 7:47:05 PM
To: pypa/pypi-legacy <pypi-legacy@noreply.github.com>
<pypi-legacy@noreply.github.com>
CC: Ernest W. Durbin III <ewdurbin@gmail.com> <ewdurbin@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [pypa/pypi-legacy] Missing ipv6 connectivity (#90)

As IPv4 addresses become more contested, this is starting to become a

**Comment by zorun** [comment]
From https://www.fastly.com/release-notes/q1-2016-q2-2016 :

> IPv6 support

> IPv6 support is in Limited Availability. IPv6 was developed by IETF to deal with the long-anticipated problem of IPv4 address exhaustion, and is intended to eventually replace IPv4. IPv6 also offers many enhancements to IPv4, such as better performance in mobile networks. If you are interested in enrolling in the LA program, email support@fastly.com to get it turned on for your account.

It would be nice for pypi to enroll in this IPv6 program!

**Comment by ewdurbin** [comment]
we have already submitted requests for IPv6 program and are waiting on a response.

**Comment by zorun** [comment]
Excellent news, thanks!

**Comment by ewdurbin** [comment]
ipv6 is go :)

**Comment by zorun** [comment]
Yeay! Thanks!

**Comment by leiforion** [comment]
Not sure if anyone will see this, but it appears that ipv6 is not working again. My office ISP leases us an IPv6 address, which is completely unable to access pypi (or any pip packages). Has something changed recently? By the looks of this, the issue should have been resolved quite some time ago. Thanks in advance!

**Comment by zorun** [comment]
@leiforion If this is a general issue with your ISP you should contact them.

If other services work with IPv6, then it's probably an issue with Fastly, you can use their debug website and send them a support request: https://www.fastly-debug.com/
