### ISSUE TITLE
Sub classifiers for testing (unit, acceptance, ...)

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#93]
Originally reported by: **Pekka Klärck (Bitbucket: [pekkaklarck](https://bitbucket.org/pekkaklarck), GitHub: [pekkaklarck](https://github.com/pekkaklarck))**

---

There currently is:

```
Topic :: Software Development :: Testing
```

Having these would help categorizing tools like nose (unit level) and Robot Framework (acceptance) better:

```
Topic :: Software Development :: Testing :: Unit
Topic :: Software Development :: Testing :: Acceptance
Topic :: Software Development :: Testing :: Mock (or Mocking)
```

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/93

**Comment by di** [comment]
I've added the following:

```
Topic :: Software Development :: Testing :: Unit
Topic :: Software Development :: Testing :: Acceptance
Topic :: Software Development :: Testing :: Mocking
Topic :: Software Development :: Testing :: BDD
```
