### ISSUE TITLE
Intermittent timeouts and download failures

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#96]
Originally reported by: **Reuben Firmin (Bitbucket: [reubenfirmin](https://bitbucket.org/reubenfirmin), GitHub: [reubenfirmin](https://github.com/reubenfirmin))**

---

I've been encountering intermittent failures (across a range of packages) for the past 36 hours.

Sometimes it's associated with SSL:

Downloading/unpacking distribute from https://pypi.python.org/packages/source/d/distribute/distribute-0.7.3.zip#md5=c6
c59594a7b180af57af8a0cc0cf5b4a

  Error The read operation timed out while getting https://pypi.python.org/packages/source/d/distribute/distribute-0.7.3.zip#md5=c6c59594a7b180af57af8a0cc0cf5b4a

Exception:
Traceback (most recent call last):
...
  File "/usr/lib/python2.7/ssl.py", line 241, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 160, in read
    return self._sslobj.read(len)
SSLError: The read operation timed out

I didn't capture every error from yesterday, but SSL was not the only culprit.

Worse, though:
a) I asked about this in IRC and nobody responded (too much noise)
b) The python status page showed no issues for pypi, so whatever smoke tests there are are insufficient

I think there need to be better automated systems for detecting problems with pypi. How about a bot which simply attempts to pip install everything every 6 hours?

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/96

**Comment by di** [comment]
This is pretty old, the new PyPI at `pypi.org` is much more responsive. Any similar problems going forward should be raised at https://github.com/pypa/warehouse/issues.
