### ISSUE TITLE
The Python 3 logo has a different size than specified in the CSS and is rescaled

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#97]
Originally reported by: **Chris Warrick (Bitbucket: [Kwpolska](https://bitbucket.org/Kwpolska), GitHub: [Kwpolska](https://github.com/Kwpolska))**

----------------------------------------

Python 2 logo: 211×71
Python 3 logo: 210×72

CSS uses 211×71 exclusively, forcing the browser to rescale the Python 3 logo.  The logo is also a bit different in the appearance in style compared to the Python 2 logo, making it look weird.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/97

**Comment by Kwpolska** [comment]
(This is not an issue anymore. Close it.)
